// frontend/src/components/editor/method-flow/FlowHelperLines.tsx
import { useEffect, useRef } from 'react'
import { useStore, useViewport } from '@xyflow/react'
import { colorPrimary } from '../../../theme'
import './FlowHelperLines.css'

export default function FlowHelperLines({
  horizontal,
  vertical,
}: {
  horizontal?: number
  vertical?: number
}) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null)
  const { x, y, zoom } = useViewport()
  const width = useStore((s) => s.width)
  const height = useStore((s) => s.height)

  useEffect(() => {
    const canvas = canvasRef.current
    const ctx = canvas?.getContext('2d')
    if (!ctx || !canvas) return

    const dpi = window.devicePixelRatio || 1
    canvas.width = width * dpi
    canvas.height = height * dpi
    ctx.setTransform(dpi, 0, 0, dpi, 0, 0)
    ctx.clearRect(0, 0, width, height)
    ctx.strokeStyle = colorPrimary
    ctx.lineWidth = 1
    ctx.setLineDash([4, 4])

    if (typeof vertical === 'number') {
      ctx.beginPath()
      ctx.moveTo(vertical * zoom + x, 0)
      ctx.lineTo(vertical * zoom + x, height)
      ctx.stroke()
    }

    if (typeof horizontal === 'number') {
      ctx.beginPath()
      ctx.moveTo(0, horizontal * zoom + y)
      ctx.lineTo(width, horizontal * zoom + y)
      ctx.stroke()
    }
  }, [width, height, x, y, zoom, horizontal, vertical])

  return <canvas ref={canvasRef} className="helper-lines-canvas" />
}

// frontend/src/components/editor/method-flow/FlowHelperLines.vue
<script setup lang="ts">
import { useVueFlow } from '@vue-flow/core'
import { computed, ref, watch } from 'vue'

const props = defineProps<{
  horizontal?: number
  vertical?: number
}>()

const { viewport, dimensions } = useVueFlow()
const canvasRef = ref<HTMLCanvasElement | null>(null)

const width = computed(() => dimensions.value.width)
const height = computed(() => dimensions.value.height)
const x = computed(() => viewport.value.x)
const y = computed(() => viewport.value.y)
const zoom = computed(() => viewport.value.zoom)

function paint() {
  const canvas = canvasRef.value
  const ctx = canvas?.getContext('2d')
  if (!ctx || !canvas) return

  const dpi = window.devicePixelRatio || 1
  canvas.width = width.value * dpi
  canvas.height = height.value * dpi
  ctx.setTransform(dpi, 0, 0, dpi, 0, 0)
  ctx.clearRect(0, 0, width.value, height.value)
  ctx.strokeStyle = '#409eff'
  ctx.lineWidth = 1
  ctx.setLineDash([4, 4])

  if (typeof props.vertical === 'number') {
    ctx.beginPath()
    ctx.moveTo(props.vertical * zoom.value + x.value, 0)
    ctx.lineTo(props.vertical * zoom.value + x.value, height.value)
    ctx.stroke()
  }

  if (typeof props.horizontal === 'number') {
    ctx.beginPath()
    ctx.moveTo(0, props.horizontal * zoom.value + y.value)
    ctx.lineTo(width.value, props.horizontal * zoom.value + y.value)
    ctx.stroke()
  }
}

watch(
  [width, height, x, y, zoom, () => props.horizontal, () => props.vertical],
  () => paint(),
  { immediate: true },
)
</script>

<template>
  <canvas ref="canvasRef" class="helper-lines-canvas" />
</template>

<style scoped>
.helper-lines-canvas {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  pointer-events: none;
}
</style>
