// frontend/src/components/editor/method-flow/TypedBindingCascader.tsx
import { useMemo } from 'react'
import { Cascader } from 'antd'
import type { ProcessorTypeExpr } from '../../../types/backend-services'
import type { DataTypeLibrary } from '../../../types/data-types'
import type { MethodParam } from '../../../types/page-method'
import {
  buildTypedBindingCascaderOptions,
  isSelectableBindingPath,
  joinBindingPath,
  splitBindingPath,
  toElCascaderOptions,
  type BindingCompatibilityMode,
  type TypedBindingCascaderOption,
} from '../../../utils/typed-binding-paths'
import './TypedBindingCascader.css'

export default function TypedBindingCascader({
  value,
  onChange,
  ambientVars,
  targetType,
  typeLibrary,
  placeholder,
  extraRoots,
  compatibility = 'strict',
  className,
}: {
  value: string
  onChange?: (value: string) => void
  ambientVars: MethodParam[]
  targetType: ProcessorTypeExpr | null | undefined
  typeLibrary?: DataTypeLibrary | null
  placeholder?: string
  extraRoots?: TypedBindingCascaderOption[]
  compatibility?: BindingCompatibilityMode
  className?: string
}) {
  const rawOptions = useMemo(
    () =>
      buildTypedBindingCascaderOptions(
        ambientVars,
        targetType,
        typeLibrary,
        extraRoots,
        compatibility,
      ),
    [ambientVars, targetType, typeLibrary, extraRoots, compatibility],
  )

  const options = useMemo(() => toElCascaderOptions(rawOptions), [rawOptions])

  const pathValue = useMemo((): string[] => {
    const segments = splitBindingPath(value || '')
    if (!segments.length) return []
    if (!findInTree(rawOptions, segments)) {
      return segments.length === 1 ? segments : [value]
    }
    return segments
  }, [rawOptions, value])

  function findInTree(
    nodes: ReturnType<typeof buildTypedBindingCascaderOptions>,
    segments: string[],
  ): boolean {
    let list = nodes
    for (const seg of segments) {
      const hit = list.find((n) => n.value === seg)
      if (!hit) return false
      list = hit.children ?? []
    }
    return true
  }

  function normalizePathValue(
    val: (string | number)[] | string | null | undefined,
  ): string[] {
    if (val == null || val === '') return []
    if (Array.isArray(val)) return val.map(String).filter(Boolean)
    if (typeof val === 'string') return splitBindingPath(val)
    return []
  }

  function onPathChange(val: (string | number)[] | undefined) {
    const segments = normalizePathValue(val)
    if (!segments.length) {
      onChange?.('')
      return
    }
    if (!isSelectableBindingPath(rawOptions, segments)) {
      return
    }
    onChange?.(joinBindingPath(segments))
  }

  return (
    <div className="typed-binding-wrap">
      <Cascader
        value={pathValue}
        options={options}
        changeOnSelect
        expandTrigger="hover"
        showSearch
        allowClear
        placeholder={placeholder || '选择类型匹配的变量或字段'}
        className={`typed-binding-cascader${className ? ` ${className}` : ''}`}
        onChange={(val) => onPathChange(val as (string | number)[] | undefined)}
      />
      {!options.length ? (
        <p className="empty-hint">暂无类型匹配的可选变量</p>
      ) : null}
    </div>
  )
}

// frontend/src/components/editor/method-flow/TypedBindingCascader.vue
<script setup lang="ts">
import { computed } from 'vue'
import type { ProcessorTypeExpr } from '../../../types/backend-services'
import type { DataTypeLibrary } from '../../../types/data-types'
import type { MethodParam } from '../../../types/page-method'
import {
  buildTypedBindingCascaderOptions,
  isSelectableBindingPath,
  joinBindingPath,
  splitBindingPath,
  toElCascaderOptions,
} from '../../../utils/typed-binding-paths'

const props = defineProps<{
  modelValue: string
  ambientVars: MethodParam[]
  targetType: ProcessorTypeExpr | null | undefined
  typeLibrary?: DataTypeLibrary | null
  placeholder?: string
  /** 额外根节点（如 $query） */
  extraRoots?: import('../../../utils/typed-binding-paths').TypedBindingCascaderOption[]
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const rawOptions = computed(() =>
  buildTypedBindingCascaderOptions(
    props.ambientVars,
    props.targetType,
    props.typeLibrary,
    props.extraRoots,
  ),
)

const options = computed(() => toElCascaderOptions(rawOptions.value))

const cascaderProps = {
  checkStrictly: true,
  emitPath: true,
  expandTrigger: 'hover' as const,
}

const pathValue = computed((): string[] => {
  const segments = splitBindingPath(props.modelValue || '')
  if (!segments.length) return []
  // 历史自由文本若不在选项树中，仍回显为单段，避免清空
  if (!findInTree(rawOptions.value, segments)) {
    return segments.length === 1 ? segments : [props.modelValue]
  }
  return segments
})

function findInTree(
  nodes: ReturnType<typeof buildTypedBindingCascaderOptions>,
  segments: string[],
): boolean {
  let list = nodes
  for (const seg of segments) {
    const hit = list.find((n) => n.value === seg)
    if (!hit) return false
    list = hit.children ?? []
  }
  return true
}

function normalizePathValue(
  val: string | string[] | null | undefined,
): string[] {
  if (val == null || val === '') return []
  if (Array.isArray(val)) return val.map(String).filter(Boolean)
  if (typeof val === 'string') return splitBindingPath(val)
  return []
}

function onPathChange(val: string | string[] | null | undefined) {
  const segments = normalizePathValue(val)
  if (!segments.length) {
    emit('update:modelValue', '')
    return
  }
  if (!isSelectableBindingPath(rawOptions.value, segments)) {
    // 未类型匹配的中间节点：忽略本次选择
    return
  }
  emit('update:modelValue', joinBindingPath(segments))
}
</script>

<template>
  <div class="typed-binding-wrap">
    <el-cascader
      :model-value="pathValue"
      :options="options"
      :props="cascaderProps"
      filterable
      clearable
      :placeholder="placeholder || '选择类型匹配的变量或字段'"
      class="typed-binding-cascader"
      @update:model-value="onPathChange"
    />
    <p v-if="!options.length" class="empty-hint">暂无类型匹配的可选变量</p>
  </div>
</template>

<style scoped>
.typed-binding-wrap {
  width: 100%;
  display: block;
}

.typed-binding-cascader {
  width: 100%;
  display: inline-flex;
}

.typed-binding-cascader :deep(.el-input),
.typed-binding-cascader :deep(.el-input__wrapper) {
  width: 100%;
}

.empty-hint {
  margin: 4px 0 0;
  font-size: 12px;
  color: #909399;
  line-height: 1.3;
}
</style>
