// frontend/src/components/xml/MultiWindowPort.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  watch,
} from 'vue'
import { Plus } from '@element-plus/icons-vue'
import type { OverflowStrategy } from '../../utils/xml'

const props = withDefaults(
  defineProps<{
    /** 编辑态：横向平铺全部窗口；预览态：仅展示激活项匹配的窗口 */
    editable?: boolean
    /** 是否显示「新建窗口」并允许点选切换焦点（组件实例内为 false） */
    allowManage?: boolean
    /** 预览态溢出策略（默认 visible）；编辑态忽略，始终可溢出 */
    overflow?: OverflowStrategy
    /** 激活项（已解析的数据池值或字面量） */
    activeValue?: string | number | null
    /** 编辑态当前聚焦的窗口下标 */
    focusIndex?: number
    windows: Array<{ key: string; index: number }>
  }>(),
  {
    editable: false,
    allowManage: true,
    overflow: 'visible',
    activeValue: '',
    focusIndex: 0,
  },
)

const emit = defineEmits<{
  'add-window': []
  'select-window': [index: number]
}>()

const viewportRef = ref<HTMLElement | null>(null)
const paneWidthPx = ref(0)
/** 编辑态锁定屏幕宽（每一页内容区宽） */
const lockedEditPaneW = ref(0)
/**
 * 深度优先：本页右侧需让出的宽度（嵌套 Swiper 第 2+ 窗、嵌套多窗体等），
 * 用 margin-right 占位，形成：
 * 【第一页【Swiper1】】【Swiper2】【Swiper3】【第二页】【第三页】
 */
const dfsExtraByIndex = ref<Record<number, number>>({})
const paneElByIndex = new Map<number, HTMLElement>()

let resizeObserver: ResizeObserver | null = null
let measureRaf = 0

const EDIT_GAP_PX = 10

const activeKey = computed(() => {
  const v = props.activeValue
  if (v == null) return ''
  return String(v)
})

const previewIndex = computed(() => {
  const key = activeKey.value
  if (!key) return -1
  return props.windows.findIndex((w) => w.key === key)
})

const editIndex = computed(() => {
  if (!props.windows.length) return -1
  const fi = props.focusIndex ?? 0
  if (fi >= 0 && fi < props.windows.length) return fi
  return 0
})

function isPreviewVisible(index: number, key: string): boolean {
  if (!key) return false
  return index === previewIndex.value
}

function paneStyle(index: number): Record<string, string> | undefined {
  if (!props.editable) return undefined
  const w = paneWidthPx.value
  if (!(w > 0)) return undefined
  const extra = dfsExtraByIndex.value[index] ?? 0
  const style: Record<string, string> = {
    width: `${w}px`,
    flex: `0 0 ${w}px`,
    minWidth: `${w}px`,
    maxWidth: `${w}px`,
  }
  // 让出内层平铺占用的横向空间，后续页不会叠上来
  if (extra > 0) style.marginRight = `${extra}px`
  return style
}

const viewportStyle = computed(() => {
  const style: Record<string, string> = {}
  if (props.editable && paneWidthPx.value) {
    style['--pane-w'] = `${paneWidthPx.value}px`
  }
  if (!props.editable) {
    style.overflow = props.overflow === 'hidden' ? 'hidden' : 'visible'
  }
  return Object.keys(style).length ? style : undefined
})

const trackStyle = computed(() => {
  if (!props.editable) return undefined
  return {
    display: 'flex',
    flexDirection: 'row' as const,
    alignItems: 'stretch' as const,
    height: '100%',
    width: 'max-content',
    maxWidth: 'none',
    gap: `${EDIT_GAP_PX}px`,
    boxSizing: 'border-box' as const,
  }
})

function setPaneRef(index: number, el: Element | null) {
  if (el instanceof HTMLElement) paneElByIndex.set(index, el)
  else paneElByIndex.delete(index)
}

/**
 * 深度优先：量本页内嵌套平铺超出「第一屏」的宽度。
 * - Swiper：track 总宽 − 单窗宽（第 2、3… 窗）
 * - 嵌套 MultiWindow：其子 track 总宽 − 单页宽
 */
function measureDfsExtra(pane: HTMLElement, baseW: number): number {
  if (!(baseW > 0)) return 0
  let extra = 0

  pane.querySelectorAll('.swiper-viewport.editable').forEach((node) => {
    const vp = node as HTMLElement
    const track = vp.querySelector('.swiper-track') as HTMLElement | null
    if (!track) return
    const trackW = track.scrollWidth
    // 窗口宽 = Swiper 宿主布局宽，与 slide 锁定宽一致
    const hostW = Math.round(vp.parentElement?.clientWidth || 0)
    const slide = vp.querySelector('.swiper-slide.editable') as HTMLElement | null
    const winW = hostW || Math.round(slide?.offsetWidth || baseW)
    if (trackW > winW) extra = Math.max(extra, trackW - winW)
  })

  const selfPort = viewportRef.value
  pane.querySelectorAll('.multi-window-port.is-edit').forEach((node) => {
    const port = node as HTMLElement
    if (port === selfPort) return
    if (!pane.contains(port)) return
    const track = port.querySelector(
      ':scope > .multi-window-track',
    ) as HTMLElement | null
    if (!track) return
    const trackW = track.scrollWidth
    if (trackW > baseW) extra = Math.max(extra, trackW - baseW)
  })

  return Math.max(0, Math.ceil(extra))
}

function remeasureDfsExtras() {
  if (!props.editable) return
  const base = lockedEditPaneW.value || paneWidthPx.value
  if (!(base > 0)) return

  const next: Record<number, number> = {}
  let changed = false
  for (const [index, pane] of paneElByIndex) {
    const extra = measureDfsExtra(pane, base)
    next[index] = extra
    if ((dfsExtraByIndex.value[index] ?? 0) !== extra) changed = true
  }
  if (changed) dfsExtraByIndex.value = next
}

function scheduleRemeasure() {
  if (!props.editable) return
  if (measureRaf) cancelAnimationFrame(measureRaf)
  measureRaf = requestAnimationFrame(() => {
    measureRaf = 0
    void nextTick(() => {
      remeasureDfsExtras()
      observeTileSources()
    })
  })
}

function observeTileSources() {
  if (!resizeObserver || !props.editable) return
  const root = viewportRef.value
  if (!root) return
  root
    .querySelectorAll(
      '.swiper-viewport.editable, .swiper-track, .multi-window-port.is-edit > .multi-window-track',
    )
    .forEach((node) => {
      resizeObserver!.observe(node)
    })
  for (const pane of paneElByIndex.values()) {
    resizeObserver!.observe(pane)
  }
}

function syncPaneWidth() {
  const el = viewportRef.value
  if (!el) return
  if (props.editable) {
    if (lockedEditPaneW.value > 0) {
      paneWidthPx.value = lockedEditPaneW.value
      scheduleRemeasure()
      return
    }
    const w = Math.max(0, Math.round(el.clientWidth))
    if (w > 0) {
      lockedEditPaneW.value = w
      paneWidthPx.value = w
      scheduleRemeasure()
    }
    return
  }
  lockedEditPaneW.value = 0
  dfsExtraByIndex.value = {}
  paneWidthPx.value = Math.max(0, Math.round(el.clientWidth))
}

watch(
  () => props.windows.length,
  (n, prev) => {
    if (props.editable && props.allowManage && n > (prev ?? 0)) {
      emit('select-window', n - 1)
    }
    scheduleRemeasure()
  },
)

watch(
  () => props.editable,
  () => {
    lockedEditPaneW.value = 0
    dfsExtraByIndex.value = {}
    void nextTick(() => syncPaneWidth())
  },
)

watch(
  () => props.windows.map((w) => w.key).join('\0'),
  () => scheduleRemeasure(),
)

onMounted(() => {
  syncPaneWidth()
  if (typeof ResizeObserver !== 'undefined') {
    resizeObserver = new ResizeObserver((entries) => {
      const root = viewportRef.value
      for (const entry of entries) {
        if (entry.target === root) syncPaneWidth()
        else scheduleRemeasure()
      }
    })
    if (viewportRef.value) resizeObserver.observe(viewportRef.value)
    observeTileSources()
  }
})

onBeforeUnmount(() => {
  if (measureRaf) cancelAnimationFrame(measureRaf)
  resizeObserver?.disconnect()
  resizeObserver = null
  paneElByIndex.clear()
})
</script>

<template>
  <div
    ref="viewportRef"
    class="multi-window-port"
    :class="{ 'is-edit': editable }"
    :style="viewportStyle"
  >
    <div class="multi-window-track" :style="trackStyle">
      <div
        v-for="win in windows"
        v-show="editable || isPreviewVisible(win.index, win.key)"
        :key="`${win.index}:${win.key}`"
        :ref="(el) => setPaneRef(win.index, el as Element | null)"
        class="multi-window-pane"
        :class="{
          editable,
          active: editable && win.index === editIndex,
          unbound: editable && !win.key,
        }"
        :style="paneStyle(win.index)"
        @click.stop="editable && allowManage && emit('select-window', win.index)"
      >
        <div class="multi-window-pane-screen">
          <slot :index="win.index" />
        </div>
      </div>

      <button
        v-if="editable && allowManage"
        type="button"
        class="multi-window-add"
        @click.stop="emit('add-window')"
      >
        <el-icon :size="22"><Plus /></el-icon>
        <span>新建窗口</span>
      </button>

      <div
        v-if="editable && allowManage && !windows.length"
        class="multi-window-empty multi-window-empty--edit"
      >
        点击右侧新建窗口
      </div>
      <div
        v-else-if="!editable && previewIndex < 0"
        class="multi-window-empty"
      >
        {{ activeKey ? `无匹配窗口「${activeKey}」` : '未绑定激活项' }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.multi-window-port {
  position: relative;
  width: 100%;
  height: 100%;
  min-height: 0;
  min-width: 0;
  box-sizing: border-box;
  overflow: visible;
}

.multi-window-port.is-edit {
  overflow: visible;
}

.multi-window-track {
  position: relative;
  width: 100%;
  height: 100%;
  min-height: 48px;
  box-sizing: border-box;
}

.multi-window-pane {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  min-width: 0;
  min-height: 0;
  box-sizing: border-box;
  overflow: visible;
}

.multi-window-pane.editable {
  position: relative;
  inset: auto;
  height: 100%;
  border: 1px dashed #94a3b8;
  border-radius: 8px;
  background: rgba(148, 163, 184, 0.04);
  overflow: visible;
  box-sizing: border-box;
}

.multi-window-pane-screen {
  /* 透传 pane 的 column flex，避免预览态 match_parent / flex:1 子节点高度塌缩 */
  display: flex;
  flex-direction: column;
  flex: 1 1 auto;
  width: 100%;
  height: 100%;
  min-width: 0;
  min-height: 0;
  box-sizing: border-box;
  overflow: visible;
  position: relative;
}

.multi-window-pane.editable.active {
  border-color: #409eff;
  background: rgba(64, 158, 255, 0.06);
}

.multi-window-pane.editable.unbound {
  border-style: dashed;
  border-color: #f59e0b;
}

.multi-window-empty {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #94a3b8;
  font-size: 12px;
  pointer-events: none;
}

.multi-window-empty--edit {
  position: relative;
  inset: auto;
  flex: 0 0 var(--pane-w, 160px);
  width: var(--pane-w, 160px);
  min-width: 120px;
  height: 100%;
  border: 1px dashed #cbd5e1;
  border-radius: 8px;
}

.multi-window-add {
  flex: 0 0 88px;
  width: 88px;
  align-self: stretch;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 6px;
  border: 1px dashed #94a3b8;
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.92);
  color: #64748b;
  font-size: 12px;
  cursor: pointer;
  padding: 8px;
  box-sizing: border-box;
}

.multi-window-add:hover {
  border-color: #409eff;
  color: #409eff;
  background: #ecf5ff;
}
</style>

// frontend/src/components/xml/MultiWindowPort.tsx
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react'
import { PlusOutlined } from '@ant-design/icons'
import type { OverflowStrategy } from '../../utils/xml'
import './MultiWindowPort.css'

export default function MultiWindowPort({
  editable = false,
  allowManage = true,
  overflow = 'visible',
  activeValue = '',
  focusIndex = 0,
  windows,
  children,
  onAddWindow,
  onSelectWindow,
}: {
  editable?: boolean
  allowManage?: boolean
  overflow?: OverflowStrategy
  activeValue?: string | number | null
  focusIndex?: number
  windows: Array<{ key: string; index: number }>
  children?: (index: number) => ReactNode
  onAddWindow?: () => void
  onSelectWindow?: (index: number) => void
}) {
  const viewportRef = useRef<HTMLDivElement | null>(null)
  const [paneWidthPx, setPaneWidthPx] = useState(0)
  const lockedEditPaneWRef = useRef(0)
  const [dfsExtraByIndex, setDfsExtraByIndex] = useState<Record<number, number>>(
    {},
  )
  const dfsExtraByIndexRef = useRef<Record<number, number>>({})
  dfsExtraByIndexRef.current = dfsExtraByIndex
  const paneElByIndexRef = useRef(new Map<number, HTMLElement>())

  const resizeObserverRef = useRef<ResizeObserver | null>(null)
  const measureRafRef = useRef(0)
  const windowsLengthRef = useRef(windows.length)
  const editableRef = useRef(editable)
  const allowManageRef = useRef(allowManage)
  editableRef.current = editable
  allowManageRef.current = allowManage

  const EDIT_GAP_PX = 10

  const activeKey = useMemo(() => {
    if (activeValue == null) return ''
    return String(activeValue)
  }, [activeValue])

  const previewIndex = useMemo(() => {
    if (!activeKey) return -1
    return windows.findIndex((w) => w.key === activeKey)
  }, [activeKey, windows])

  const editIndex = useMemo(() => {
    if (!windows.length) return -1
    const fi = focusIndex ?? 0
    if (fi >= 0 && fi < windows.length) return fi
    return 0
  }, [focusIndex, windows.length])

  function isPreviewVisible(index: number, key: string): boolean {
    if (!key) return false
    return index === previewIndex
  }

  function paneStyle(index: number): CSSProperties | undefined {
    if (!editable) return undefined
    const w = paneWidthPx
    if (!(w > 0)) return undefined
    const extra = dfsExtraByIndex[index] ?? 0
    const style: CSSProperties = {
      width: `${w}px`,
      flex: `0 0 ${w}px`,
      minWidth: `${w}px`,
      maxWidth: `${w}px`,
    }
    if (extra > 0) style.marginRight = `${extra}px`
    return style
  }

  const viewportStyle = useMemo(() => {
    const style: Record<string, string> = {}
    if (editable && paneWidthPx) {
      style['--pane-w'] = `${paneWidthPx}px`
    }
    if (!editable) {
      style.overflow = overflow === 'hidden' ? 'hidden' : 'visible'
    }
    return Object.keys(style).length ? (style as CSSProperties) : undefined
  }, [editable, overflow, paneWidthPx])

  const trackStyle = useMemo(() => {
    if (!editable) return undefined
    return {
      display: 'flex',
      flexDirection: 'row' as const,
      alignItems: 'stretch' as const,
      height: '100%',
      width: 'max-content',
      maxWidth: 'none',
      gap: `${EDIT_GAP_PX}px`,
      boxSizing: 'border-box' as const,
    } as CSSProperties
  }, [editable])

  function setPaneRef(index: number, el: HTMLDivElement | null) {
    if (el) paneElByIndexRef.current.set(index, el)
    else paneElByIndexRef.current.delete(index)
  }

  function measureDfsExtra(pane: HTMLElement, baseW: number): number {
    if (!(baseW > 0)) return 0
    let extra = 0

    pane.querySelectorAll('.swiper-viewport.editable').forEach((node) => {
      const vp = node as HTMLElement
      const track = vp.querySelector('.swiper-track') as HTMLElement | null
      if (!track) return
      const trackW = track.scrollWidth
      const hostW = Math.round(vp.parentElement?.clientWidth || 0)
      const slide = vp.querySelector('.swiper-slide.editable') as HTMLElement | null
      const winW = hostW || Math.round(slide?.offsetWidth || baseW)
      if (trackW > winW) extra = Math.max(extra, trackW - winW)
    })

    const selfPort = viewportRef.current
    pane.querySelectorAll('.multi-window-port.is-edit').forEach((node) => {
      const port = node as HTMLElement
      if (port === selfPort) return
      if (!pane.contains(port)) return
      const track = port.querySelector(
        ':scope > .multi-window-track',
      ) as HTMLElement | null
      if (!track) return
      const trackW = track.scrollWidth
      if (trackW > baseW) extra = Math.max(extra, trackW - baseW)
    })

    return Math.max(0, Math.ceil(extra))
  }

  function remeasureDfsExtras() {
    if (!editableRef.current) return
    const base = lockedEditPaneWRef.current || paneWidthPx
    if (!(base > 0)) return

    const next: Record<number, number> = {}
    let changed = false
    for (const [index, pane] of paneElByIndexRef.current) {
      const extra = measureDfsExtra(pane, base)
      next[index] = extra
      if ((dfsExtraByIndexRef.current[index] ?? 0) !== extra) changed = true
    }
    if (changed) setDfsExtraByIndex(next)
  }

  function observeTileSources() {
    if (!resizeObserverRef.current || !editableRef.current) return
    const root = viewportRef.current
    if (!root) return
    root
      .querySelectorAll(
        '.swiper-viewport.editable, .swiper-track, .multi-window-port.is-edit > .multi-window-track',
      )
      .forEach((node) => {
        resizeObserverRef.current!.observe(node)
      })
    for (const pane of paneElByIndexRef.current.values()) {
      resizeObserverRef.current.observe(pane)
    }
  }

  function scheduleRemeasure() {
    if (!editableRef.current) return
    if (measureRafRef.current) cancelAnimationFrame(measureRafRef.current)
    measureRafRef.current = requestAnimationFrame(() => {
      measureRafRef.current = 0
      queueMicrotask(() => {
        remeasureDfsExtras()
        observeTileSources()
      })
    })
  }

  function syncPaneWidth() {
    const el = viewportRef.current
    if (!el) return
    if (editableRef.current) {
      if (lockedEditPaneWRef.current > 0) {
        setPaneWidthPx(lockedEditPaneWRef.current)
        scheduleRemeasure()
        return
      }
      const w = Math.max(0, Math.round(el.clientWidth))
      if (w > 0) {
        lockedEditPaneWRef.current = w
        setPaneWidthPx(w)
        scheduleRemeasure()
      }
      return
    }
    lockedEditPaneWRef.current = 0
    setDfsExtraByIndex({})
    setPaneWidthPx(Math.max(0, Math.round(el.clientWidth)))
  }

  useEffect(() => {
    const n = windows.length
    const prev = windowsLengthRef.current
    if (editable && allowManage && n > prev) {
      onSelectWindow?.(n - 1)
    }
    windowsLengthRef.current = n
    scheduleRemeasure()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [windows.length])

  useEffect(() => {
    lockedEditPaneWRef.current = 0
    setDfsExtraByIndex({})
    queueMicrotask(() => syncPaneWidth())
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editable])

  const windowsKey = windows.map((w) => w.key).join('\0')
  useEffect(() => {
    scheduleRemeasure()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [windowsKey])

  useEffect(() => {
    syncPaneWidth()
    if (typeof ResizeObserver !== 'undefined') {
      resizeObserverRef.current = new ResizeObserver((entries) => {
        const root = viewportRef.current
        for (const entry of entries) {
          if (entry.target === root) syncPaneWidth()
          else scheduleRemeasure()
        }
      })
      if (viewportRef.current) {
        resizeObserverRef.current.observe(viewportRef.current)
      }
      observeTileSources()
    }
    return () => {
      if (measureRafRef.current) cancelAnimationFrame(measureRafRef.current)
      resizeObserverRef.current?.disconnect()
      resizeObserverRef.current = null
      paneElByIndexRef.current.clear()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <div
      ref={viewportRef}
      className={`multi-window-port${editable ? ' is-edit' : ''}`}
      style={viewportStyle}
    >
      <div className="multi-window-track" style={trackStyle}>
        {windows.map((win) => {
          const previewHidden =
            !editable && !isPreviewVisible(win.index, win.key)
          return (
            <div
              key={`${win.index}:${win.key}`}
              ref={(el) => setPaneRef(win.index, el)}
              className={[
                'multi-window-pane',
                editable ? 'editable' : '',
                editable && win.index === editIndex ? 'active' : '',
                editable && !win.key ? 'unbound' : '',
                previewHidden ? 'is-preview-hidden' : '',
              ]
                .filter(Boolean)
                .join(' ')}
              style={{
                ...paneStyle(win.index),
                display: editable || isPreviewVisible(win.index, win.key)
                  ? undefined
                  : 'none',
              }}
              onClick={(event) => {
                event.stopPropagation()
                if (editable && allowManage) onSelectWindow?.(win.index)
              }}
            >
              <div className="multi-window-pane-screen">{children?.(win.index)}</div>
            </div>
          )
        })}

        {editable && allowManage ? (
          <button
            type="button"
            className="multi-window-add"
            onClick={(event) => {
              event.stopPropagation()
              onAddWindow?.()
            }}
          >
            <PlusOutlined style={{ fontSize: 22 }} />
            <span>新建窗口</span>
          </button>
        ) : null}

        {editable && allowManage && !windows.length ? (
          <div className="multi-window-empty multi-window-empty--edit">
            点击右侧新建窗口
          </div>
        ) : !editable && previewIndex < 0 ? (
          <div className="multi-window-empty">
            {activeKey ? `无匹配窗口「${activeKey}」` : '未绑定激活项'}
          </div>
        ) : null}
      </div>
    </div>
  )
}
