// frontend/src/components/xml/RepeatBadge.tsx
import './RepeatBadge.css'

export default function RepeatBadge({
  title = '已配置重复',
  size = 15,
  clickable = false,
  onClick,
}: {
  title?: string
  size?: number
  clickable?: boolean
  onClick?: (event: React.MouseEvent<HTMLSpanElement>) => void
}) {
  function handleClick(event: React.MouseEvent<HTMLSpanElement>) {
    event.stopPropagation()
    onClick?.(event)
  }

  return (
    <span
      className={`repeat-badge${clickable ? ' clickable' : ''}`}
      title={title}
      style={{
        width: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
        height: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
        fontSize: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
        borderRadius: `calc(4px / max(var(--canvas-zoom, 1), 1))`,
      }}
      role="button"
      onClick={clickable ? handleClick : undefined}
    >
      <svg className="repeat-badge-icon" viewBox="0 0 24 24" aria-hidden="true">
        <path
          fill="currentColor"
          d="M17.5 3.5c-2.6.2-5 1.6-6.5 3.7C9.2 5 6.5 3.5 3.5 3.5c0 0-.5 5.2 2.2 8.4C4.2 13.2 3 15.4 3 18c2.6 0 5-1.2 6.5-3.2.3 1.7.9 3.3 1.8 4.7.9-1.4 1.5-3 1.8-4.7C14.6 16.8 17 18 19.6 18c0-2.6-1.2-4.8-2.7-6.1 2.7-3.2 2.2-8.4 2.2-8.4z"
        />
      </svg>
    </span>
  )
}

// frontend/src/components/xml/RepeatBadge.vue
<script setup lang="ts">
withDefaults(
  defineProps<{
    title?: string
    size?: number
    clickable?: boolean
  }>(),
  {
    title: '已配置重复',
    size: 15,
    clickable: false,
  },
)

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

function handleClick(event: MouseEvent) {
  event.stopPropagation()
  emit('click', event)
}
</script>

<template>
  <span
    class="repeat-badge"
    :class="{ clickable }"
    :title="title"
    :style="{
      width: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
      height: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
      fontSize: `calc(${size}px / max(var(--canvas-zoom, 1), 1))`,
      borderRadius: `calc(4px / max(var(--canvas-zoom, 1), 1))`,
    }"
    role="button"
    @click="clickable ? handleClick($event) : undefined"
  >
    <svg class="repeat-badge-icon" viewBox="0 0 24 24" aria-hidden="true">
      <path
        fill="currentColor"
        d="M17.5 3.5c-2.6.2-5 1.6-6.5 3.7C9.2 5 6.5 3.5 3.5 3.5c0 0-.5 5.2 2.2 8.4C4.2 13.2 3 15.4 3 18c2.6 0 5-1.2 6.5-3.2.3 1.7.9 3.3 1.8 4.7.9-1.4 1.5-3 1.8-4.7C14.6 16.8 17 18 19.6 18c0-2.6-1.2-4.8-2.7-6.1 2.7-3.2 2.2-8.4 2.2-8.4z"
      />
    </svg>
  </span>
</template>

<style scoped>
.repeat-badge {
  box-sizing: border-box;
  flex-shrink: 0;
  background: #7c3aed;
  color: #fff;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  line-height: 0;
  overflow: hidden;
  pointer-events: none;
  box-shadow: 0 1px 3px rgba(15, 23, 42, 0.2);
}

.repeat-badge.clickable {
  pointer-events: auto;
  cursor: pointer;
}

.repeat-badge.clickable:hover {
  background: #6d28d9;
}

.repeat-badge-icon {
  width: 0.68em;
  height: 0.68em;
  display: block;
  flex-shrink: 0;
}
</style>
