// frontend/src/components/editor/method-flow/dialogs/OutputNodeDialog.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button, Form, Input, Modal, Select } from 'antd'
import type {
  DataMethodOperation,
  ProcessorMethodParam,
  ServiceProcessor,
} from '../../../../types/backend-services'
import type { DataTypeLibrary } from '../../../../types/data-types'
import type { MethodParam } from '../../../../types/page-method'
import { processorTypeExprToTs } from '../../../../types/page-method'
import TypedBindingCascader from '../TypedBindingCascader'
import FlowPrintField from '../FlowPrintField'
import {
  createEmptyOutputNodeForm,
  type OutputNodeForm,
} from './output-node'
import './OutputNodeDialog.css'

export type { OutputNodeForm } from './output-node'

const WRITE_OPERATIONS = new Set<DataMethodOperation>([
  'insert',
  'batchInsert',
  'delete',
  'update',
  'custom',
])

const OPERATION_LABEL: Partial<Record<DataMethodOperation, string>> = {
  insert: '插入',
  batchInsert: '批量插入',
  delete: '删除',
  update: '修改',
  custom: '自定义',
}

export default function OutputNodeDialog({
  open,
  onOpenChange,
  form,
  dataProcessors,
  reservedNames,
  ambientVars,
  typeLibrary,
  onSave,
}: {
  open: boolean
  onOpenChange?: (open: boolean) => void
  form: OutputNodeForm
  dataProcessors: ServiceProcessor[]
  reservedNames: string[]
  ambientVars: MethodParam[]
  typeLibrary?: DataTypeLibrary | null
  onSave?: (form: OutputNodeForm) => void
}) {
  const [draft, setDraft] = useState<OutputNodeForm>(createEmptyOutputNodeForm())

  useEffect(() => {
    if (!open) return
    setDraft(
      createEmptyOutputNodeForm({
        ...form,
        paramBindings: { ...(form.paramBindings ?? {}) },
      }),
    )
  }, [open, form])

  const methodOptions = useMemo(() => {
    const opts: Array<{
      value: string
      label: string
      processorId: string
      methodId: string
    }> = []
    for (const proc of dataProcessors) {
      for (const m of proc.methods) {
        const op = m.dataConfig?.operation
        const isHttp = m.dataConfig?.source === 'http'
        if (!isHttp && (!op || !WRITE_OPERATIONS.has(op))) continue
        const name = m.name.trim() || m.id
        const opLabel = isHttp ? '外部接口' : OPERATION_LABEL[op!] || op
        opts.push({
          value: `${proc.id}::${m.id}`,
          label: `${proc.name || proc.id}.${name}（${opLabel}）`,
          processorId: proc.id,
          methodId: m.id,
        })
      }
    }
    return opts
  }, [dataProcessors])

  const selectedMethod = useMemo(() => {
    for (const proc of dataProcessors) {
      if (proc.id !== draft.dataProcessorId) continue
      return proc.methods.find((m) => m.id === draft.dataMethodId) ?? null
    }
    return null
  }, [dataProcessors, draft.dataProcessorId, draft.dataMethodId])

  const methodParams = useMemo(
    (): ProcessorMethodParam[] =>
      (selectedMethod?.params ?? []).filter((p) => p.name.trim()),
    [selectedMethod],
  )

  function syncParamBindings(
    params: ProcessorMethodParam[],
    current: Record<string, string>,
  ): Record<string, string> {
    const next: Record<string, string> = {}
    for (const p of params) {
      const name = p.name.trim()
      if (!name) continue
      next[name] = current[name] ?? ''
    }
    return next
  }

  const selectedMethodKey =
    draft.dataProcessorId && draft.dataMethodId
      ? `${draft.dataProcessorId}::${draft.dataMethodId}`
      : ''

  function setSelectedMethodKey(key: string | null) {
    const opt = methodOptions.find((o) => o.value === key)
    if (!opt) {
      setDraft((d) => ({
        ...d,
        dataProcessorId: '',
        dataMethodId: '',
        methodLabel: '',
        paramBindings: {},
      }))
      return
    }
    const method = dataProcessors
      .find((p) => p.id === opt.processorId)
      ?.methods.find((m) => m.id === opt.methodId)
    setDraft((d) => ({
      ...d,
      dataProcessorId: opt.processorId,
      dataMethodId: opt.methodId,
      methodLabel: opt.label,
      paramBindings: syncParamBindings(method?.params ?? [], d.paramBindings),
      description: d.description.trim() ? d.description : opt.label,
    }))
  }

  useEffect(() => {
    if (!methodParams.length && !Object.keys(draft.paramBindings).length) return
    const next = syncParamBindings(methodParams, draft.paramBindings)
    const same =
      Object.keys(next).length === Object.keys(draft.paramBindings).length &&
      Object.keys(next).every((k) => next[k] === draft.paramBindings[k])
    if (same) return
    setDraft((d) => ({ ...d, paramBindings: next }))
  }, [methodParams])

  const methodError =
    draft.dataProcessorId && draft.dataMethodId
      ? ''
      : '请选择数据层写入方法（插入 / 删除 / 修改等）或外部接口'

  const bindingError = useMemo(() => {
    for (const p of methodParams) {
      const name = p.name.trim()
      if (!name) continue
      if (!(draft.paramBindings[name] ?? '').trim()) {
        return `请绑定入参「${name}」`
      }
    }
    return ''
  }, [methodParams, draft.paramBindings])

  const resultVarError = useMemo(() => {
    const name = draft.resultVarName.trim()
    if (!name) return ''
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
      return '变量名须为合法标识符'
    }
    if (reservedNames.includes(name)) {
      return '变量名与已有名称冲突'
    }
    return ''
  }, [draft.resultVarName, reservedNames])

  function paramTypeLabel(p: ProcessorMethodParam): string {
    return processorTypeExprToTs(p.typeExpr, typeLibrary)
  }

  const canSave = !methodError && !bindingError && !resultVarError

  function handleSave() {
    if (!canSave) return
    const paramBindings: Record<string, string> = {}
    for (const p of methodParams) {
      const name = p.name.trim()
      if (!name) continue
      paramBindings[name] = (draft.paramBindings[name] ?? '').trim()
    }
    onSave?.({
      ...createEmptyOutputNodeForm(),
      channel: 'local',
      dataProcessorId: draft.dataProcessorId,
      dataMethodId: draft.dataMethodId,
      methodLabel: draft.methodLabel,
      paramBindings,
      resultVarName: draft.resultVarName.trim(),
      description: draft.description.trim(),
      printExpr: draft.printExpr.trim(),
    })
    onOpenChange?.(false)
  }

  return (
    <Modal
      open={open}
      title="编辑输出节点"
      width={560}
      destroyOnHidden
      maskClosable={false}
      keyboard={false}
      onCancel={() => onOpenChange?.(false)}
      footer={
        <Button type="primary" size="small" disabled={!canSave} onClick={handleSave}>
          确定
        </Button>
      }
    >
      <Form
        className="flow-node-form"
        size="small"
        labelAlign="right"
        labelCol={{ flex: '110px' }}
        wrapperCol={{ flex: 1 }}
      >
        <Form.Item
          label="数据层方法"
          required
          validateStatus={methodError ? 'error' : undefined}
          help={methodError || undefined}
        >
          <Select
            value={selectedMethodKey || undefined}
            size="small"
            showSearch
            allowClear
            placeholder="选择插入 / 删除 / 修改等方法或外部接口"
            style={{ width: '100%' }}
            options={methodOptions.map((opt) => ({
              value: opt.value,
              label: opt.label,
            }))}
            onChange={(key) => setSelectedMethodKey(key ?? null)}
          />
          {!methodOptions.length ? (
            <p className="hint">
              暂无写入类数据层方法或外部接口，请先在数据层配置插入、删除、修改或 HTTP 接口方法
            </p>
          ) : null}
        </Form.Item>

        {methodParams.length ? (
          <Form.Item
            label="绑定入参"
            required
            validateStatus={bindingError ? 'error' : undefined}
            help={bindingError || undefined}
          >
            <div className="param-bindings">
              {methodParams.map((p) => (
                <div key={p.id} className="param-row">
                  <span
                    className="param-name"
                    title={`${p.remark || p.name} · ${paramTypeLabel(p)}`}
                  >
                    {p.name}
                    <em className="param-type">{paramTypeLabel(p)}</em>
                  </span>
                  <TypedBindingCascader
                    className="param-bind"
                    value={draft.paramBindings[p.name] ?? ''}
                    onChange={(expr) =>
                      setDraft((d) => ({
                        ...d,
                        paramBindings: { ...d.paramBindings, [p.name]: expr },
                      }))
                    }
                    ambientVars={ambientVars}
                    targetType={p.typeExpr}
                    typeLibrary={typeLibrary}
                  />
                </div>
              ))}
            </div>
          </Form.Item>
        ) : selectedMethodKey ? (
          <Form.Item label="绑定入参">
            <span className="hint-inline">该方法无入参</span>
          </Form.Item>
        ) : null}

        <Form.Item
          label="结果变量"
          validateStatus={resultVarError ? 'error' : undefined}
          help={resultVarError || undefined}
        >
          <Input
            value={draft.resultVarName}
            size="small"
            placeholder="可选，如 affected / insertId"
            maxLength={64}
            allowClear
            onChange={(e) =>
              setDraft((d) => ({ ...d, resultVarName: e.target.value }))
            }
          />
        </Form.Item>

        <Form.Item label="说明">
          <Input
            value={draft.description}
            size="small"
            maxLength={80}
            showCount
            placeholder="显示在流程节点上"
            onChange={(e) =>
              setDraft((d) => ({ ...d, description: e.target.value }))
            }
          />
        </Form.Item>
        <Form.Item label="打印">
          <FlowPrintField
            value={draft.printExpr}
            onChange={(printExpr) => setDraft((d) => ({ ...d, printExpr }))}
            ambientNames={ambientVars.map((v) => v.name).filter(Boolean)}
          />
        </Form.Item>
      </Form>
    </Modal>
  )
}

// frontend/src/components/editor/method-flow/dialogs/OutputNodeDialog.vue
<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import type {
  DataMethodOperation,
  ProcessorMethodParam,
  ServiceProcessor,
} from '../../../../types/backend-services'
import type { DataTypeLibrary } from '../../../../types/data-types'
import type { MethodParam } from '../../../../types/page-method'
import { processorTypeExprToTs } from '../../../../types/page-method'
import TypedBindingCascader from '../TypedBindingCascader.vue'
import FlowPrintField from '../FlowPrintField.vue'

/** 输出节点：绑定数据层写入类方法 */
export type OutputNodeForm = {
  dataProcessorId: string
  dataMethodId: string
  methodLabel: string
  paramBindings: Record<string, string>
  /** 可选：写入结果变量名 */
  resultVarName: string
  description: string
  printExpr: string
}

const WRITE_OPERATIONS = new Set<DataMethodOperation>([
  'insert',
  'batchInsert',
  'delete',
  'update',
  'custom',
])

const OPERATION_LABEL: Partial<Record<DataMethodOperation, string>> = {
  insert: '插入',
  batchInsert: '批量插入',
  delete: '删除',
  update: '修改',
  custom: '自定义',
}

const props = defineProps<{
  modelValue: boolean
  form: OutputNodeForm
  dataProcessors: ServiceProcessor[]
  reservedNames: string[]
  ambientVars: MethodParam[]
  typeLibrary?: DataTypeLibrary | null
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  save: [form: OutputNodeForm]
}>()

const draft = reactive<OutputNodeForm>({
  dataProcessorId: '',
  dataMethodId: '',
  methodLabel: '',
  paramBindings: {},
  resultVarName: '',
  description: '',
  printExpr: '',
})

const visible = computed({
  get: () => props.modelValue,
  set: (v) => emit('update:modelValue', v),
})

watch(
  () => props.modelValue,
  (open) => {
    if (!open) return
    Object.assign(draft, {
      ...props.form,
      paramBindings: { ...(props.form.paramBindings ?? {}) },
    })
  },
)

const methodOptions = computed(() => {
  const opts: Array<{
    value: string
    label: string
    processorId: string
    methodId: string
  }> = []
  for (const proc of props.dataProcessors) {
    for (const m of proc.methods) {
      const op = m.dataConfig?.operation
      if (!op || !WRITE_OPERATIONS.has(op)) continue
      const name = m.name.trim() || m.id
      const opLabel = OPERATION_LABEL[op] || op
      opts.push({
        value: `${proc.id}::${m.id}`,
        label: `${proc.name || proc.id}.${name}（${opLabel}）`,
        processorId: proc.id,
        methodId: m.id,
      })
    }
  }
  return opts
})

const selectedMethod = computed(() => {
  for (const proc of props.dataProcessors) {
    if (proc.id !== draft.dataProcessorId) continue
    return proc.methods.find((m) => m.id === draft.dataMethodId) ?? null
  }
  return null
})

const methodParams = computed((): ProcessorMethodParam[] => {
  return (selectedMethod.value?.params ?? []).filter((p) => p.name.trim())
})

function syncParamBindings(params: ProcessorMethodParam[]) {
  const next: Record<string, string> = {}
  for (const p of params) {
    const name = p.name.trim()
    if (!name) continue
    next[name] = draft.paramBindings[name] ?? ''
  }
  draft.paramBindings = next
}

const selectedMethodKey = computed({
  get() {
    if (!draft.dataProcessorId || !draft.dataMethodId) return ''
    return `${draft.dataProcessorId}::${draft.dataMethodId}`
  },
  set(key: string) {
    const opt = methodOptions.value.find((o) => o.value === key)
    if (!opt) {
      draft.dataProcessorId = ''
      draft.dataMethodId = ''
      draft.methodLabel = ''
      draft.paramBindings = {}
      return
    }
    draft.dataProcessorId = opt.processorId
    draft.dataMethodId = opt.methodId
    draft.methodLabel = opt.label
    const method = props.dataProcessors
      .find((p) => p.id === opt.processorId)
      ?.methods.find((m) => m.id === opt.methodId)
    syncParamBindings(method?.params ?? [])
    if (!draft.description.trim()) {
      draft.description = opt.label
    }
  },
})

watch(
  methodParams,
  (params) => {
    if (!params.length && !Object.keys(draft.paramBindings).length) return
    syncParamBindings(params)
  },
  { deep: true },
)

const methodError = computed(() =>
  draft.dataProcessorId && draft.dataMethodId
    ? ''
    : '请选择数据层写入方法（插入 / 删除 / 修改等）',
)

const bindingError = computed(() => {
  for (const p of methodParams.value) {
    const name = p.name.trim()
    if (!name) continue
    if (!(draft.paramBindings[name] ?? '').trim()) {
      return `请绑定入参「${name}」`
    }
  }
  return ''
})

const resultVarError = computed(() => {
  const name = draft.resultVarName.trim()
  if (!name) return ''
  if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) {
    return '变量名须为合法标识符'
  }
  if (props.reservedNames.includes(name)) {
    return '变量名与已有名称冲突'
  }
  return ''
})

function paramTypeLabel(p: ProcessorMethodParam): string {
  return processorTypeExprToTs(p.typeExpr, props.typeLibrary)
}

function handleSave() {
  if (methodError.value || bindingError.value || resultVarError.value) return
  const paramBindings: Record<string, string> = {}
  for (const p of methodParams.value) {
    const name = p.name.trim()
    if (!name) continue
    paramBindings[name] = (draft.paramBindings[name] ?? '').trim()
  }
  emit('save', {
    dataProcessorId: draft.dataProcessorId,
    dataMethodId: draft.dataMethodId,
    methodLabel: draft.methodLabel,
    paramBindings,
    resultVarName: draft.resultVarName.trim(),
    description: draft.description.trim(),
    printExpr: draft.printExpr.trim(),
  })
  visible.value = false
}
</script>

<template>
  <el-dialog
    v-model="visible"
    title="编辑输出节点"
    width="560px"
    destroy-on-close
    append-to-body
    :close-on-click-modal="false"
    :close-on-press-escape="false"
  >
    <el-form
      class="flow-node-form"
      label-position="right"
      label-width="110px"
    >
      <el-form-item
        label="数据层方法"
        required
        :error="methodError || undefined"
      >
        <el-select
          v-model="selectedMethodKey"
          filterable
          clearable
          placeholder="选择插入 / 删除 / 修改等方法"
          style="width: 100%"
        >
          <el-option
            v-for="opt in methodOptions"
            :key="opt.value"
            :label="opt.label"
            :value="opt.value"
          />
        </el-select>
        <p v-if="!methodOptions.length" class="hint">
          暂无写入类数据层方法，请先在数据层配置插入、删除或修改方法
        </p>
      </el-form-item>

      <el-form-item
        v-if="methodParams.length"
        label="绑定入参"
        required
        :error="bindingError || undefined"
      >
        <div class="param-bindings">
          <div v-for="p in methodParams" :key="p.id" class="param-row">
            <span
              class="param-name"
              :title="`${p.remark || p.name} · ${paramTypeLabel(p)}`"
            >
              {{ p.name }}
              <em class="param-type">{{ paramTypeLabel(p) }}</em>
            </span>
            <TypedBindingCascader
              v-model="draft.paramBindings[p.name]"
              class="param-bind"
              :ambient-vars="ambientVars"
              :target-type="p.typeExpr"
              :type-library="typeLibrary"
            />
          </div>
        </div>
      </el-form-item>
      <el-form-item v-else-if="selectedMethodKey" label="绑定入参">
        <span class="hint-inline">该方法无入参</span>
      </el-form-item>

      <el-form-item
        label="结果变量"
        :error="resultVarError || undefined"
      >
        <el-input
          v-model="draft.resultVarName"
          placeholder="可选，如 affected / insertId"
          maxlength="64"
          clearable
        />
      </el-form-item>

      <el-form-item label="说明">
        <el-input
          v-model="draft.description"
          maxlength="80"
          show-word-limit
          placeholder="显示在流程节点上"
        />
      </el-form-item>
      <el-form-item label="打印">
        <FlowPrintField
          v-model="draft.printExpr"
          :ambient-names="ambientVars.map((v) => v.name).filter(Boolean)"
        />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button
        type="primary"
        :disabled="
          Boolean(methodError) ||
          Boolean(bindingError) ||
          Boolean(resultVarError)
        "
        @click="handleSave"
      >
        确定
      </el-button>
    </template>
  </el-dialog>
</template>

<style scoped>
.hint {
  margin: 6px 0 0;
  font-size: 12px;
  color: #909399;
}

.hint-inline {
  font-size: 12px;
  color: #909399;
}

.param-bindings {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.param-row {
  width: 100%;
  display: flex;
  align-items: center;
  gap: 10px;
}

.param-name {
  flex: 0 0 128px;
  box-sizing: border-box;
  height: 32px;
  padding: 0 8px;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  background: #f5f7fa;
  font-size: 13px;
  color: #606266;
  line-height: 30px;
  display: flex;
  align-items: center;
  gap: 6px;
  overflow: hidden;
  white-space: nowrap;
}

.param-type {
  font-style: normal;
  font-size: 11px;
  color: #909399;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  min-width: 0;
}

.param-bind {
  flex: 1 1 0;
  min-width: 0;
  width: 0;
}

.flow-node-form :deep(.el-form-item__content) {
  flex: 1;
  min-width: 0;
}
</style>
