// frontend/src/components/editor/method-flow/dialogs/StartNodeDialog.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import FlowPrintField from '../FlowPrintField.vue'

const props = defineProps<{
  modelValue: boolean
  printExpr: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  save: [payload: { printExpr: string }]
}>()

const draft = ref('')

const visible = computed({
  get: () => props.modelValue,
  set: (v) => emit('update:modelValue', v),
})

watch(
  () => props.modelValue,
  (open) => {
    if (open) draft.value = props.printExpr ?? ''
  },
)

function handleSave() {
  emit('save', { printExpr: draft.value.trim() })
  visible.value = false
}
</script>

<template>
  <el-dialog
    v-model="visible"
    title="编辑开始节点"
    width="480px"
    destroy-on-close
    append-to-body
    :close-on-click-modal="false"
    :close-on-press-escape="false"
  >
    <el-form
      class="flow-node-form"
      label-position="right"
      label-width="110px"
      @submit.prevent
    >
      <el-form-item label="打印">
        <FlowPrintField v-model="draft" />
      </el-form-item>
    </el-form>
    <template #footer>
      <el-button type="primary" @click="handleSave">确定</el-button>
    </template>
  </el-dialog>
</template>

// frontend/src/components/editor/method-flow/dialogs/StartNodeDialog.tsx
import { useEffect, useState } from 'react'
import { Button, Form, Modal } from 'antd'
import FlowPrintField from '../FlowPrintField'
import './StartNodeDialog.css'

export default function StartNodeDialog({
  open,
  onOpenChange,
  printExpr,
  onSave,
}: {
  open: boolean
  onOpenChange?: (open: boolean) => void
  printExpr: string
  onSave?: (payload: { printExpr: string }) => void
}) {
  const [draft, setDraft] = useState('')

  useEffect(() => {
    if (open) setDraft(printExpr ?? '')
  }, [open, printExpr])

  function handleSave() {
    onSave?.({ printExpr: draft.trim() })
    onOpenChange?.(false)
  }

  return (
    <Modal
      open={open}
      title="编辑开始节点"
      width={480}
      destroyOnHidden
      maskClosable={false}
      keyboard={false}
      onCancel={() => onOpenChange?.(false)}
      footer={
        <Button type="primary" onClick={handleSave}>
          确定
        </Button>
      }
    >
      <Form
        className="flow-node-form"
        labelAlign="right"
        labelCol={{ flex: '110px' }}
        wrapperCol={{ flex: 1 }}
        onFinish={(e) => e.preventDefault?.()}
      >
        <Form.Item label="打印">
          <FlowPrintField value={draft} onChange={setDraft} />
        </Form.Item>
      </Form>
    </Modal>
  )
}
