// frontend/src/components/editor/method-flow/nodes/StartNode.tsx
import { Handle, Position, type NodeProps } from '@xyflow/react'
import { useFlowDebugNode } from '../use-flow-debug-node'
import FlowNodePrintBubble from '../FlowNodePrintBubble'
import './StartNode.css'

export default function StartNode({ id }: NodeProps) {
  const { debugClass } = useFlowDebugNode(id)

  return (
    <div className={`flow-node start-node ${debugClass}`}>
      <div className="flow-node-title">开始</div>
      <Handle id="default" type="source" position={Position.Bottom} />
      <FlowNodePrintBubble nodeId={id} />
    </div>
  )
}

// frontend/src/components/editor/method-flow/nodes/StartNode.vue
<script setup lang="ts">
import { Handle, Position, type NodeProps } from '@vue-flow/core'
import { useFlowDebugNode } from '../use-flow-debug-node'
import FlowNodePrintBubble from '../FlowNodePrintBubble.vue'

const props = defineProps<NodeProps>()
const { debugClass } = useFlowDebugNode(props.id)
</script>

<template>
  <!-- 开始/结束：圆角胶囊 -->
  <div class="flow-node start-node" :class="debugClass">
    <div class="flow-node-title">开始</div>
    <Handle id="default" type="source" :position="Position.Bottom" />
    <FlowNodePrintBubble :node-id="id" />
  </div>
</template>

<style scoped>
.flow-node {
  position: relative;
  overflow: visible;
  min-width: 88px;
  padding: 10px 28px;
  border-radius: 999px;
  border: 1.5px solid #79bbff;
  background: #ecf5ff;
  font-size: 13px;
  color: #303133;
  text-align: center;
  line-height: 1.3;
  box-sizing: border-box;
}

.flow-node-title {
  font-weight: 600;
  color: #337ecc;
  letter-spacing: 0.08em;
}
</style>
