// frontend/src/layouts/MainLayout.tsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { Outlet, useNavigate } from 'react-router-dom'
import { Button, Form, Input, Modal, Tooltip } from 'antd'
import { CommentOutlined, LogoutOutlined } from '@ant-design/icons'
import { useProjectStore } from '../stores/project'
import { useWorkspaceSettingsStore } from '../stores/workspace-settings'
import { useAiAssistantStore } from '../stores/ai-assistant'
import {
  buildProject,
  getBuildSchemes,
  getWechatPublishStatus,
  uploadWechatMp,
  type BuildScheme,
} from '../api/projects'
import WorkspaceSettingsButton, {
  type WorkspaceSettingsButtonHandle,
} from '../components/editor/WorkspaceSettingsButton'
import AiAssistantPanel from '../components/editor/AiAssistantPanel'
import BuildSchemeDialog from '../components/editor/BuildSchemeDialog'
import BuildSchemeIcon from '../components/icons/BuildSchemeIcon'
import HammerIcon from '../components/icons/HammerIcon'
import PublishIcon from '../components/icons/PublishIcon'
import LubanStackLogo from '../components/icons/LubanStackLogo'
import { PRODUCT_NAME } from '../constants/brand'
import { ElMessage } from '../ui/feedback'
import './MainLayout.css'

type BuildTargetKind = 'backend' | 'frontend'

type BuildTarget = {
  key: string
  kind: BuildTargetKind
  name: string
  label: string
  detail: string
}

export default function MainLayout() {
  const navigate = useNavigate()
  const projectPath = useProjectStore((s) => s.path)
  const projectConfig = useProjectStore((s) => s.config)
  const clearProject = useProjectStore((s) => s.clearProject)
  const showAiButton = useWorkspaceSettingsStore((s) => s.aiAssistantEnabled)
  const panelOpen = useAiAssistantStore((s) => s.panelOpen)
  const projectBusyByAi = useAiAssistantStore((s) => s.projectBusyByAi)
  const setPanelOpen = useAiAssistantStore((s) => s.setPanelOpen)
  const togglePanel = useAiAssistantStore((s) => s.togglePanel)
  const [building, setBuilding] = useState(false)
  const settingsBtn = useRef<WorkspaceSettingsButtonHandle>(null)
  const [buildingKey, setBuildingKey] = useState('')
  const [buildingLabel, setBuildingLabel] = useState('')
  const [schemeDialogVisible, setSchemeDialogVisible] = useState(false)
  const [buildSelectVisible, setBuildSelectVisible] = useState(false)
  const [schemes, setSchemes] = useState<BuildScheme[]>([])
  const [publishVisible, setPublishVisible] = useState(false)
  const [publishing, setPublishing] = useState(false)
  const [publishForm, setPublishForm] = useState({ version: '', desc: '' })
  const [publishStatusHint, setPublishStatusHint] = useState('')

  const pageTitle = projectConfig?.name
    ? `${projectConfig.name} · 工作区`
    : '工作区'

  useEffect(() => {
    if (!showAiButton) setPanelOpen(false)
  }, [showAiButton, setPanelOpen])

  function onAiBusyMaskClick() {
    ElMessage.warning({
      message: 'AI助手正在编辑项目，请稍候',
      zIndex: 6000,
    })
  }

  function closeProject() {
    clearProject()
    void navigate('/')
  }

  function openSchemeDialog() {
    if (!projectPath) {
      ElMessage.warning('请先打开项目')
      return
    }
    setSchemeDialogVisible(true)
  }

  function frontendTypeLabel(type: string): string {
    if (type === 'mp-wx') return '微信小程序'
    if (type === 'vue3') return 'Vue3'
    return type || '前端'
  }

  function targetsOf(scheme: BuildScheme): BuildTarget[] {
    const out: BuildTarget[] = []
    const schemeName = scheme.name.trim()
    for (const b of scheme.backends ?? []) {
      const name = b.name.trim()
      if (!name) continue
      out.push({
        key: `${schemeName}::backend::${name}`,
        kind: 'backend',
        name,
        label: name,
        detail: `${b.type === 'nestjs' ? 'Nest.js' : b.type || '后端'} :${b.port}${
          b.includeOss ? ' · OSS' : ''
        }`,
      })
    }
    for (const f of scheme.frontends ?? []) {
      const name = f.name.trim()
      if (!name) continue
      const pageCount = f.pageIds?.length ?? 0
      out.push({
        key: `${schemeName}::frontend::${name}`,
        kind: 'frontend',
        name,
        label: name,
        detail: `${frontendTypeLabel(f.type)}${pageCount ? ` · ${pageCount} 页` : ''}`,
      })
    }
    return out
  }

  const schemeRows = useMemo(
    () => schemes.map((scheme) => ({ scheme, targets: targetsOf(scheme) })),
    [schemes],
  )

  async function handleBuild() {
    if (!projectPath) {
      ElMessage.warning('请先打开项目')
      return
    }
    try {
      const lib = await getBuildSchemes(projectPath)
      if (!lib.schemes.length) {
        ElMessage.warning('请先配置构建方案')
        setSchemeDialogVisible(true)
        return
      }
      setSchemes(lib.schemes)
      setBuildSelectVisible(true)
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '读取构建方案失败')
    }
  }

  async function runBuild(payload: {
    schemeName: string
    backendNames?: string[]
    frontendNames?: string[]
    label: string
    key?: string
  }) {
    if (!projectPath || building) return
    setBuilding(true)
    setBuildingKey(payload.key || '')
    setBuildingLabel(payload.label)
    try {
      const result = await buildProject({
        projectPath,
        schemeName: payload.schemeName,
        ...(payload.backendNames != null ? { backendNames: payload.backendNames } : {}),
        ...(payload.frontendNames != null
          ? { frontendNames: payload.frontendNames }
          : {}),
      })
      ElMessage.success(
        `构建完成：${result.backends.length} 个后端 / ${result.frontends.length} 个前端 → ${result.outputRoot}`,
      )
      setBuildSelectVisible(false)
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '构建失败')
    } finally {
      setBuilding(false)
      setBuildingKey('')
      setBuildingLabel('')
    }
  }

  function onTargetClick(scheme: BuildScheme, item: BuildTarget) {
    void runBuild({
      schemeName: scheme.name,
      backendNames: item.kind === 'backend' ? [item.name] : [],
      frontendNames: item.kind === 'frontend' ? [item.name] : [],
      label: `正在构建 ${item.label}…`,
      key: item.key,
    })
  }

  function onBuildAll(scheme: BuildScheme) {
    void runBuild({
      schemeName: scheme.name,
      label: `正在构建 ${scheme.name}…`,
      key: `${scheme.name}::all`,
    })
  }

  async function handlePublish() {
    if (!projectPath) {
      ElMessage.warning('请先打开项目')
      return
    }
    try {
      const status = await getWechatPublishStatus(projectPath)
      if (!status.wechatAppId || !status.hasPrivateKey) {
        ElMessage.warning('请先在「设置 → 项目」配置微信 AppID 与上传密钥')
        settingsBtn.current?.open('project')
        return
      }
      setPublishForm({
        version: status.projectVersion || '0.1.0',
        desc: '',
      })
      setPublishStatusHint(`AppID：${status.wechatAppId}`)
      setPublishVisible(true)
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '读取发布配置失败')
    }
  }

  function openPublishSettings() {
    setPublishVisible(false)
    settingsBtn.current?.open('project')
  }

  async function confirmPublish() {
    if (!projectPath || publishing) return
    const version = publishForm.version.trim()
    if (!version) {
      ElMessage.warning('请填写版本号')
      return
    }
    setPublishing(true)
    try {
      const result = await uploadWechatMp({
        projectPath,
        version,
        desc: publishForm.desc.trim(),
        rebuild: true,
      })
      ElMessage.success(
        `已上传开发版 ${result.version}（${result.appid}），可在微信公众平台查看`,
      )
      setPublishVisible(false)
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '发布失败')
    } finally {
      setPublishing(false)
    }
  }

  return (
    <div className="layout">
      {projectBusyByAi
        ? createPortal(
            <div
              className="ai-busy-mask"
              aria-hidden="true"
              onClick={onAiBusyMaskClick}
              onContextMenu={(e) => {
                e.preventDefault()
                onAiBusyMaskClick()
              }}
            />,
            document.body,
          )
        : null}
      <header className="header">
        <div className="brand">
          <LubanStackLogo className="brand-mark" size={28} />
          <span className="logo">{PRODUCT_NAME}</span>
          <span className="title">{pageTitle}</span>
        </div>
        <div className="header-actions">
          {showAiButton ? (
            <Tooltip title="AI助手" placement="bottom">
              <Button
                className="header-icon-btn"
                icon={<CommentOutlined />}
                onClick={() => togglePanel()}
              />
            </Tooltip>
          ) : null}
          <WorkspaceSettingsButton ref={settingsBtn} />
          <Tooltip title="配置构建方案" placement="bottom">
            <Button
              className="header-icon-btn"
              disabled={!projectPath}
              onClick={openSchemeDialog}
            >
              <BuildSchemeIcon className="header-action-icon" />
            </Button>
          </Tooltip>
          <Tooltip title="构建" placement="bottom">
            <Button
              className="header-icon-btn"
              loading={building}
              disabled={!projectPath}
              onClick={() => void handleBuild()}
            >
              <HammerIcon className="header-action-icon" />
            </Button>
          </Tooltip>
          <Tooltip title="发布到微信" placement="bottom">
            <Button
              className="header-icon-btn"
              loading={publishing}
              disabled={!projectPath || building}
              onClick={() => void handlePublish()}
            >
              <PublishIcon className="header-action-icon" />
            </Button>
          </Tooltip>
          <Tooltip title="关闭项目" placement="bottom">
            <Button
              className="header-icon-btn"
              icon={<LogoutOutlined />}
              onClick={closeProject}
            />
          </Tooltip>
        </div>
      </header>
      <main className="main">
        <Outlet />
      </main>

      <AiAssistantPanel
        open={panelOpen}
        onOpenChange={setPanelOpen}
      />

      {projectPath ? (
        <BuildSchemeDialog
          open={schemeDialogVisible}
          onOpenChange={setSchemeDialogVisible}
          projectPath={projectPath}
        />
      ) : null}

      <Modal
        title="选择要构建的方案"
        open={buildSelectVisible}
        onCancel={() => {
          if (!building) {
            setBuildSelectVisible(false)
            setSchemes([])
          }
        }}
        width={560}
        centered
        destroyOnHidden
        maskClosable={!building}
        keyboard={!building}
        closable={!building}
        footer={null}
      >
        <div className="build-picker">
          {building ? (
            <div className="build-picker-loading">{buildingLabel || '正在构建…'}</div>
          ) : null}
          {schemeRows.map((row) => (
            <div key={row.scheme.id || row.scheme.name} className="scheme-block">
              <div className="scheme-head">
                <div className="scheme-titles">
                  <div className="scheme-name">{row.scheme.name}</div>
                  <div className="scheme-desc">
                    {row.scheme.description?.trim() || '暂无说明'}
                  </div>
                </div>
                <Button
                  type="primary"
                  size="small"
                  disabled={building || !row.targets.length}
                  loading={building && buildingKey === `${row.scheme.name}::all`}
                  onClick={() => onBuildAll(row.scheme)}
                >
                  构建全部
                </Button>
              </div>
              {row.targets.length ? (
                <div className="target-grid">
                  {row.targets.map((item) => (
                    <button
                      key={item.key}
                      type="button"
                      className={`target-tile${
                        building && buildingKey === item.key ? ' is-building' : ''
                      }`}
                      disabled={building}
                      onClick={() => onTargetClick(row.scheme, item)}
                    >
                      <div className="tile-body">
                        <div className="tile-name">{item.label}</div>
                        <div className="tile-detail">{item.detail}</div>
                      </div>
                      <span className="tile-kind">
                        {item.kind === 'backend' ? '后端' : '前端'}
                      </span>
                    </button>
                  ))}
                </div>
              ) : (
                <div className="targets-empty">没有可构建的后端/前端</div>
              )}
            </div>
          ))}
        </div>
      </Modal>

      <Modal
        title="发布到微信小程序"
        open={publishVisible}
        onCancel={() => {
          if (!publishing) setPublishVisible(false)
        }}
        width={480}
        centered
        destroyOnHidden
        maskClosable={!publishing}
        keyboard={!publishing}
        closable={!publishing}
        footer={
          <>
            <Button disabled={publishing} onClick={openPublishSettings}>
              项目设置
            </Button>
            <Button disabled={publishing} onClick={() => setPublishVisible(false)}>
              取消
            </Button>
            <Button
              type="primary"
              loading={publishing}
              onClick={() => void confirmPublish()}
            >
              发布
            </Button>
          </>
        }
      >
        <p className="publish-hint">
          {publishStatusHint}
          <br />
          将导出小程序并上传为开发版（无需打开微信开发者工具）。请确认本机 IP 已在公众平台白名单中。
        </p>
        <Form labelCol={{ span: 4 }} className="publish-form">
          <Form.Item label="版本号" required>
            <Input
              value={publishForm.version}
              disabled={publishing}
              placeholder="例如 1.0.0"
              onChange={(e) =>
                setPublishForm((prev) => ({ ...prev, version: e.target.value }))
              }
            />
          </Form.Item>
          <Form.Item label="备注">
            <Input.TextArea
              value={publishForm.desc}
              rows={3}
              disabled={publishing}
              placeholder="可选，显示在微信后台的版本描述"
              onChange={(e) =>
                setPublishForm((prev) => ({ ...prev, desc: e.target.value }))
              }
            />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  )
}

// frontend/src/layouts/MainLayout.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ChatDotRound, SwitchButton } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useProjectStore } from '../stores/project'
import { useWorkspaceSettingsStore } from '../stores/workspace-settings'
import { useAiAssistantStore } from '../stores/ai-assistant'
import {
  buildProject,
  getBuildSchemes,
  type BuildScheme,
} from '../api/projects'
import WorkspaceSettingsButton from '../components/editor/WorkspaceSettingsButton.vue'
import AiAssistantPanel from '../components/editor/AiAssistantPanel.vue'
import BuildSchemeDialog from '../components/editor/BuildSchemeDialog.vue'
import BuildSchemeIcon from '../components/icons/BuildSchemeIcon.vue'
import HammerIcon from '../components/icons/HammerIcon.vue'
import LubanStackLogo from '../components/icons/LubanStackLogo.vue'
import { PRODUCT_NAME } from '../constants/brand'

type BuildTargetKind = 'backend' | 'frontend'

type BuildTarget = {
  key: string
  kind: BuildTargetKind
  name: string
  label: string
  detail: string
}

const router = useRouter()
const projectStore = useProjectStore()
const workspaceSettings = useWorkspaceSettingsStore()
const aiAssistant = useAiAssistantStore()
const showAiButton = computed(() => workspaceSettings.aiAssistantEnabled)
const aiPanelVisible = computed({
  get: () => aiAssistant.panelOpen,
  set: (open: boolean) => aiAssistant.setPanelOpen(open),
})
const building = ref(false)

watch(showAiButton, (enabled) => {
  if (!enabled) aiAssistant.setPanelOpen(false)
})
const buildingKey = ref('')
const buildingLabel = ref('')
const schemeDialogVisible = ref(false)
const buildSelectVisible = ref(false)
const schemes = ref<BuildScheme[]>([])

const pageTitle = computed(() => {
  const name = projectStore.config?.name
  return name ? `${name} · 工作区` : '工作区'
})

function closeProject() {
  projectStore.clearProject()
  void router.push('/')
}

function openSchemeDialog() {
  if (!projectStore.path) {
    ElMessage.warning('请先打开项目')
    return
  }
  schemeDialogVisible.value = true
}

function frontendTypeLabel(type: string): string {
  if (type === 'mp-wx') return '微信小程序'
  if (type === 'vue3') return 'Vue3'
  return type || '前端'
}

function targetsOf(scheme: BuildScheme): BuildTarget[] {
  const out: BuildTarget[] = []
  const schemeName = scheme.name.trim()
  for (const b of scheme.backends ?? []) {
    const name = b.name.trim()
    if (!name) continue
    out.push({
      key: `${schemeName}::backend::${name}`,
      kind: 'backend',
      name,
      label: name,
      detail: `${b.type === 'nestjs' ? 'Nest.js' : b.type || '后端'} :${b.port}${
        b.includeOss ? ' · OSS' : ''
      }`,
    })
  }
  for (const f of scheme.frontends ?? []) {
    const name = f.name.trim()
    if (!name) continue
    const pageCount = f.pageIds?.length ?? 0
    out.push({
      key: `${schemeName}::frontend::${name}`,
      kind: 'frontend',
      name,
      label: name,
      detail: `${frontendTypeLabel(f.type)}${
        pageCount ? ` · ${pageCount} 页` : ''
      }`,
    })
  }
  return out
}

const schemeRows = computed(() =>
  schemes.value.map((scheme) => ({
    scheme,
    targets: targetsOf(scheme),
  })),
)

async function handleBuild() {
  if (!projectStore.path) {
    ElMessage.warning('请先打开项目')
    return
  }
  try {
    const lib = await getBuildSchemes(projectStore.path)
    if (!lib.schemes.length) {
      ElMessage.warning('请先配置构建方案')
      schemeDialogVisible.value = true
      return
    }
    schemes.value = lib.schemes
    buildSelectVisible.value = true
  } catch (err) {
    ElMessage.error(err instanceof Error ? err.message : '读取构建方案失败')
  }
}

async function runBuild(payload: {
  schemeName: string
  backendNames?: string[]
  frontendNames?: string[]
  label: string
  key?: string
}) {
  if (!projectStore.path || building.value) return
  building.value = true
  buildingKey.value = payload.key || ''
  buildingLabel.value = payload.label
  try {
    const result = await buildProject({
      projectPath: projectStore.path,
      schemeName: payload.schemeName,
      ...(payload.backendNames != null
        ? { backendNames: payload.backendNames }
        : {}),
      ...(payload.frontendNames != null
        ? { frontendNames: payload.frontendNames }
        : {}),
    })
    ElMessage.success(
      `构建完成：${result.backends.length} 个后端 / ${result.frontends.length} 个前端 → ${result.outputRoot}`,
    )
    buildSelectVisible.value = false
  } catch (err) {
    ElMessage.error(err instanceof Error ? err.message : '构建失败')
  } finally {
    building.value = false
    buildingKey.value = ''
    buildingLabel.value = ''
  }
}

function onTargetClick(scheme: BuildScheme, item: BuildTarget) {
  void runBuild({
    schemeName: scheme.name,
    backendNames: item.kind === 'backend' ? [item.name] : [],
    frontendNames: item.kind === 'frontend' ? [item.name] : [],
    label: `正在构建 ${item.label}…`,
    key: item.key,
  })
}

function onBuildAll(scheme: BuildScheme) {
  void runBuild({
    schemeName: scheme.name,
    label: `正在构建 ${scheme.name}…`,
    key: `${scheme.name}::all`,
  })
}

function onBuildSelectClose(done: () => void) {
  if (building.value) return
  done()
}

function onDialogClosed() {
  schemes.value = []
}
</script>

<template>
  <div class="layout">
    <header class="header">
      <div class="brand">
        <LubanStackLogo class="brand-mark" :size="28" />
        <span class="logo">{{ PRODUCT_NAME }}</span>
        <span class="title">{{ pageTitle }}</span>
      </div>
      <div class="header-actions">
        <el-tooltip
          v-if="showAiButton"
          content="AI助手"
          placement="bottom"
          :enterable="false"
        >
          <el-button
            class="header-icon-btn"
            :icon="ChatDotRound"
            @click="aiAssistant.togglePanel()"
          />
        </el-tooltip>
        <WorkspaceSettingsButton />
        <el-tooltip content="配置构建方案" placement="bottom" :enterable="false">
          <el-button
            class="header-icon-btn"
            :disabled="!projectStore.path"
            @click="openSchemeDialog"
          >
            <BuildSchemeIcon class="header-action-icon" />
          </el-button>
        </el-tooltip>
        <el-tooltip content="构建" placement="bottom" :enterable="false">
          <el-button
            class="header-icon-btn"
            :loading="building"
            :disabled="!projectStore.path"
            @click="handleBuild"
          >
            <HammerIcon class="header-action-icon" />
          </el-button>
        </el-tooltip>
        <el-tooltip content="关闭项目" placement="bottom" :enterable="false">
          <el-button
            class="header-icon-btn"
            :icon="SwitchButton"
            @click="closeProject"
          />
        </el-tooltip>
      </div>
    </header>
    <main class="main">
      <router-view />
    </main>

    <AiAssistantPanel v-model="aiPanelVisible" />

    <BuildSchemeDialog
      v-if="projectStore.path"
      v-model="schemeDialogVisible"
      :project-path="projectStore.path"
    />

    <el-dialog
      v-model="buildSelectVisible"
      title="选择要构建的方案"
      width="560px"
      align-center
      destroy-on-close
      append-to-body
      :close-on-click-modal="!building"
      :close-on-press-escape="!building"
      :show-close="!building"
      :before-close="onBuildSelectClose"
      @closed="onDialogClosed"
    >
      <div
        v-loading="building"
        class="build-picker"
        :element-loading-text="buildingLabel || '正在构建…'"
      >
        <div
          v-for="row in schemeRows"
          :key="row.scheme.id || row.scheme.name"
          class="scheme-block"
        >
          <div class="scheme-head">
            <div class="scheme-titles">
              <div class="scheme-name">{{ row.scheme.name }}</div>
              <div class="scheme-desc">
                {{ row.scheme.description?.trim() || '暂无说明' }}
              </div>
            </div>
            <el-button
              type="primary"
              size="small"
              :disabled="building || !row.targets.length"
              :loading="
                building && buildingKey === `${row.scheme.name}::all`
              "
              @click="onBuildAll(row.scheme)"
            >
              构建全部
            </el-button>
          </div>

          <div v-if="row.targets.length" class="target-grid">
            <button
              v-for="item in row.targets"
              :key="item.key"
              type="button"
              class="target-tile"
              :class="{ 'is-building': building && buildingKey === item.key }"
              :disabled="building"
              @click="onTargetClick(row.scheme, item)"
            >
              <div class="tile-body">
                <div class="tile-name">{{ item.label }}</div>
                <div class="tile-detail">{{ item.detail }}</div>
              </div>
              <span class="tile-kind">
                {{ item.kind === 'backend' ? '后端' : '前端' }}
              </span>
            </button>
          </div>
          <div v-else class="targets-empty">没有可构建的后端/前端</div>
        </div>
      </div>
    </el-dialog>
  </div>
</template>

<style scoped>
.layout {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  background: #f5f7fa;
}

.header {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 56px;
  padding: 0 16px;
  background: #fff;
  border-bottom: 1px solid #ebeef5;
}

.brand {
  display: flex;
  align-items: center;
  gap: 10px;
  min-width: 0;
}

.brand-mark {
  flex-shrink: 0;
}

.logo {
  font-weight: 700;
  font-size: 17px;
  letter-spacing: 0.01em;
  color: #303133;
  flex-shrink: 0;
}

.title {
  font-size: 14px;
  color: #606266;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  border-left: 1px solid #e4e7ed;
  padding-left: 10px;
  margin-left: 2px;
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.header-actions :deep(.header-icon-btn) {
  width: 32px;
  height: 32px;
  padding: 0;
  border-radius: 8px;
  border: 1px solid #dcdfe6;
  background: #fff;
  color: #606266;
}

.header-actions :deep(.header-icon-btn:hover) {
  color: #409eff;
  border-color: #c6e2ff;
  background: #ecf5ff;
}

.header-action-icon {
  width: 18px;
  height: 18px;
  display: block;
}

.build-picker {
  position: relative;
  min-height: 80px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.scheme-block {
  padding: 14px;
  border: 1px solid #ebeef5;
  border-radius: 12px;
  background: #fff;
}

.scheme-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  margin-bottom: 12px;
}

.scheme-titles {
  min-width: 0;
}

.scheme-name {
  font-size: 14px;
  font-weight: 600;
  color: #303133;
  line-height: 1.4;
}

.scheme-desc {
  margin-top: 4px;
  font-size: 12px;
  color: #909399;
  line-height: 1.5;
}

.targets-empty {
  padding: 8px 0 2px;
  font-size: 12px;
  color: #c0c4cc;
}

.target-grid {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
}

.target-tile {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  margin: 0;
  padding: 12px;
  text-align: left;
  border: 1px solid #ebeef5;
  border-radius: 10px;
  background: #fafafa;
  cursor: pointer;
  transition:
    border-color 0.15s ease,
    background 0.15s ease,
    box-shadow 0.15s ease;
}

.target-tile:hover:not(:disabled) {
  border-color: #409eff;
  background: #f5faff;
  box-shadow: 0 2px 8px rgba(64, 158, 255, 0.12);
}

.target-tile.is-building {
  border-color: #409eff;
  background: #ecf5ff;
}

.target-tile:disabled {
  cursor: not-allowed;
}

.tile-body {
  flex: 1;
  min-width: 0;
}

.tile-name {
  font-size: 13px;
  font-weight: 600;
  color: #303133;
  line-height: 1.4;
  word-break: break-all;
}

.tile-detail {
  margin-top: 4px;
  font-size: 12px;
  color: #909399;
  line-height: 1.4;
}

.tile-kind {
  flex-shrink: 0;
  font-size: 11px;
  color: #909399;
  line-height: 22px;
}

.main {
  flex: 1;
  min-height: 0;
  overflow: hidden;
}

@media (max-width: 560px) {
  .target-grid {
    grid-template-columns: 1fr;
  }
}
</style>
