// frontend/src/components/editor/BackendServiceWorkspace.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'
import {
  Delete,
  EditPen,
} from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  getServiceControllers,
  getServiceProcessors,
  saveServiceControllers as saveServiceControllersApi,
} from '../../api/projects'
import {
  createDefaultMethodFlow,
  createEmptyDataMethodConfig,
  createEmptyProcessorTypeExpr,
  createEmptyServiceApi,
  createEmptyServiceController,
  type ProcessorMethod,
  type ProcessorMethodParam,
  type ProcessorTypeExpr,
  type ServiceApi,
  type ServiceApiParamLocation,
  type ServiceController,
  type ServiceProcessor,
} from '../../types/backend-services'
import type { DataTypeLibrary } from '../../types/data-types'
import EditServiceApiDialog, {
  type ServiceApiEditPayload,
} from './EditServiceApiDialog.vue'
import ServiceProcessorPanel, {
  type ProcessorDebugTarget,
  type ProcessorSelectionState,
} from './ServiceProcessorPanel.vue'

type ServiceLayer = 'controller' | 'service' | 'data' | 'schedule'

const props = defineProps<{
  projectPath: string
  serviceId: string
  serviceName: string
  typeLibrary: DataTypeLibrary | null
  /** 全部模块选项（输入节点选模块） */
  moduleOptions?: Array<{ id: string; name: string }>
  /** 受控：当前层（由工作区持久化） */
  layer?: ServiceLayer
  /** 恢复：控制器选中 */
  restoredControllerId?: string
  /** 恢复：业务层选中 */
  restoredBusiness?: {
    processorId: string
    methodId: string
    flowEditing: { processorId: string; methodId: string } | null
  } | null
  /** 恢复：数据层选中 */
  restoredData?: {
    processorId: string
    methodId: string
  } | null
}>()

const emit = defineEmits<{
  'update:layer': [layer: ServiceLayer]
  'update:debug-target': [target: ProcessorDebugTarget | null]
  'update:controller-id': [id: string]
  'update:business-selection': [state: ProcessorSelectionState]
  'update:data-selection': [state: ProcessorSelectionState]
}>()

const dataProcessorPanelRef = ref<InstanceType<typeof ServiceProcessorPanel> | null>(
  null,
)
const businessProcessorPanelRef = ref<InstanceType<
  typeof ServiceProcessorPanel
> | null>(null)

const activeLayer = computed(() => props.layer ?? 'controller')
const controllers = ref<ServiceController[]>([])
const activeControllerId = ref('')
const loading = ref(false)
const dialogVisible = ref(false)
const dialogName = ref('')
const dialogPath = ref('')
const dialogRemark = ref('')
const editingControllerId = ref<string | null>(null)

function onDebugTarget(target: ProcessorDebugTarget | null) {
  if (activeLayer.value === 'controller') return
  emit('update:debug-target', target)
}

function applyDebugParams(params: Record<string, unknown>) {
  if (activeLayer.value === 'controller') {
    updateApiDebugParams(params)
    return
  }
  if (activeLayer.value === 'service') {
    businessProcessorPanelRef.value?.updateDebugParams(params)
    return
  }
  dataProcessorPanelRef.value?.updateDebugParams(params)
}

function applyFlowDebugCursor(state: {
  cursorNodeId: string | null
  visitedNodeIds: string[]
  printByNode?: Record<string, string>
}) {
  if (activeLayer.value === 'controller') {
    onApiFlowDebugCursor(state)
    return
  }
  businessProcessorPanelRef.value?.applyFlowDebugCursor(state)
}

defineExpose({
  applyDebugParams,
  applyFlowDebugCursor,
  openCreateController: openCreateDialog,
  addApi,
  openCreateProcessor() {
    if (activeLayer.value === 'service') {
      businessProcessorPanelRef.value?.openCreateDialog()
    } else if (activeLayer.value === 'data') {
      dataProcessorPanelRef.value?.openCreateDialog()
    }
  },
  addProcessorMethod() {
    if (activeLayer.value === 'service') {
      businessProcessorPanelRef.value?.addMethod()
    } else if (activeLayer.value === 'data') {
      dataProcessorPanelRef.value?.addMethod()
    }
  },
})

let saveTimer: ReturnType<typeof setTimeout> | null = null

const activeController = computed(
  () => controllers.value.find((c) => c.id === activeControllerId.value) ?? null,
)

const apis = computed(() => activeController.value?.apis ?? [])

const dtoOptions = computed(() => {
  const opts: Array<{ id: string; label: string }> = []
  for (const group of props.typeLibrary?.groups ?? []) {
    for (const t of group.types) {
      if (t.category === 'dto' || (!t.category && t.kind === 'interface')) {
        opts.push({
          id: t.id,
          label: t.name ? `${t.name}${t.remark ? ` · ${t.remark}` : ''}` : t.id,
        })
      }
    }
  }
  return opts
})

watch(
  () => [props.projectPath, props.serviceId] as const,
  ([path, id]) => {
    // 切服务时不再强制回控制器；层由父级持久化状态决定
    if (path && id) void loadControllers()
    else {
      controllers.value = []
      activeControllerId.value = ''
    }
  },
  { immediate: true },
)

watch(
  controllers,
  (list) => {
    if (!list.length) {
      activeControllerId.value = ''
      return
    }
    const prefer = props.restoredControllerId
    if (prefer && list.some((c) => c.id === prefer)) {
      activeControllerId.value = prefer
      return
    }
    if (!list.some((c) => c.id === activeControllerId.value)) {
      activeControllerId.value = list[0]!.id
    }
  },
  { deep: true },
)

watch(activeControllerId, (id) => {
  emit('update:controller-id', id)
})

watch(
  () => props.layer,
  (layer) => {
    if (layer === 'schedule') {
      emit('update:debug-target', null)
    }
  },
)

async function loadControllers() {
  if (!props.projectPath || !props.serviceId) return
  loading.value = true
  try {
    const res = await getServiceControllers(props.projectPath, props.serviceId)
    controllers.value = res.controllers
  } catch (err) {
    ElMessage.error(err instanceof Error ? err.message : '加载控制器失败')
    controllers.value = []
  } finally {
    loading.value = false
  }
}

function persistControllers() {
  if (!props.projectPath || !props.serviceId) return
  if (saveTimer) clearTimeout(saveTimer)
  saveTimer = setTimeout(async () => {
    try {
      const res = await saveServiceControllersApi({
        projectPath: props.projectPath,
        serviceId: props.serviceId,
        controllers: controllers.value,
      })
      controllers.value = res.controllers
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '保存控制器失败')
    }
  }, 400)
}

function openCreateDialog() {
  editingControllerId.value = null
  dialogName.value = ''
  dialogPath.value = ''
  dialogRemark.value = ''
  dialogVisible.value = true
}

function openEditDialog(ctrl: ServiceController) {
  editingControllerId.value = ctrl.id
  dialogName.value = ctrl.name
  dialogPath.value = ctrl.path
  dialogRemark.value = ctrl.remark
  dialogVisible.value = true
}

function submitDialog() {
  const name = dialogName.value.trim()
  if (!name) {
    ElMessage.warning('请输入控制器名称')
    return
  }
  const path = dialogPath.value.trim()
  const remark = dialogRemark.value.trim()
  const nameTaken = controllers.value.some(
    (c) =>
      c.name.trim().toLowerCase() === name.toLowerCase() &&
      c.id !== editingControllerId.value,
  )
  if (nameTaken) {
    ElMessage.warning(`控制器名称「${name}」已存在`)
    return
  }

  if (editingControllerId.value) {
    controllers.value = controllers.value.map((c) =>
      c.id === editingControllerId.value ? { ...c, name, path, remark } : c,
    )
  } else {
    const next = {
      ...createEmptyServiceController(name),
      path,
      remark,
    }
    controllers.value = [...controllers.value, next]
    activeControllerId.value = next.id
  }
  dialogVisible.value = false
  persistControllers()
}

async function removeController(ctrl: ServiceController) {
  try {
    await ElMessageBox.confirm(
      `确定删除控制器「${ctrl.name}」？其下 API 将一并删除。`,
      '删除控制器',
      { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' },
    )
  } catch {
    return
  }
  controllers.value = controllers.value.filter((c) => c.id !== ctrl.id)
  persistControllers()
}

function patchActiveApis(nextApis: ServiceApi[]) {
  const id = activeControllerId.value
  if (!id) return
  controllers.value = controllers.value.map((c) =>
    c.id === id ? { ...c, apis: nextApis } : c,
  )
  persistControllers()
}

const apiDialogVisible = ref(false)
const apiEditIndex = ref(-1)
const apiDraft = ref<ServiceApi | null>(null)
const selectedApiId = ref('')

const editingApi = computed(() => apiDraft.value)

const apiReservedNames = computed(() =>
  apis.value
    .filter((_, i) => i !== apiEditIndex.value)
    .map((a) => a.name.trim())
    .filter(Boolean),
)

function apiInputLocationClass(location: ServiceApiParamLocation): string {
  switch (location) {
    case 'query':
      return 'api-in-query'
    case 'param':
      return 'api-in-param'
    case 'body':
      return 'api-in-body'
    case 'httpHeader':
      return 'api-in-header'
    default:
      return ''
  }
}

function apiInputItems(api: ServiceApi): Array<{
  name: string
  location: ServiceApiParamLocation
  className: string
}> {
  return (api.inputs ?? [])
    .map((p) => {
      const name = p.varName.trim()
      if (!name) return null
      return {
        name,
        location: p.location,
        className: apiInputLocationClass(p.location),
      }
    })
    .filter((x): x is NonNullable<typeof x> => Boolean(x))
}

function apiInputsTitle(api: ServiceApi): string {
  const list = apiInputItems(api)
  if (!list.length) return '无'
  return list.map((p) => `${p.location}:${p.name}`).join('、')
}

function addApi() {
  if (!activeController.value) {
    ElMessage.warning('请先选择或创建控制器')
    return
  }
  openApiEdit(-1)
}

/** 编辑 / 创建：弹窗绑定业务方法（不再打开流程图） */
function openApiEdit(index: number) {
  if (!activeController.value) return
  apiEditIndex.value = index
  if (index < 0) {
    apiDraft.value = createEmptyServiceApi(`api${apis.value.length + 1}`)
  } else {
    const api = apis.value[index]
    if (!api) return
    apiDraft.value = {
      ...api,
      inputs: (api.inputs ?? []).map((p) => ({ ...p })),
      output: api.output
        ? { ...api.output, genericArgs: { ...(api.output.genericArgs ?? {}) } }
        : createEmptyProcessorTypeExpr('any'),
      scope: api.scope === 'private' ? 'private' : 'public',
      flow: api.flow ?? createDefaultMethodFlow(),
    }
    selectedApiId.value = api.id
  }
  apiDialogVisible.value = true
}

function saveApiEdit(payload: ServiceApiEditPayload) {
  if (apiEditIndex.value < 0) {
    const base = apiDraft.value ?? createEmptyServiceApi(payload.name)
    patchActiveApis([
      ...apis.value,
      {
        ...base,
        name: payload.name,
        path: payload.path,
        remark: payload.remark,
        method: payload.method,
        inputs: payload.inputs,
        output: payload.output,
        requireAuth: payload.requireAuth,
        scope: payload.scope,
        flow: payload.flow ?? createDefaultMethodFlow(),
      },
    ])
    selectedApiId.value = base.id
  } else {
    const next = apis.value.map((api, i) =>
      i === apiEditIndex.value
        ? {
            ...api,
            name: payload.name,
            path: payload.path,
            remark: payload.remark,
            method: payload.method,
            inputs: payload.inputs,
            output: payload.output,
            requireAuth: payload.requireAuth,
            scope: payload.scope,
            flow: payload.flow ?? api.flow ?? createDefaultMethodFlow(),
          }
        : api,
    )
    patchActiveApis(next)
  }
  apiEditIndex.value = -1
  apiDraft.value = null
}

/** API 流程图编辑中 */
const apiFlowEditing = ref<{ controllerId: string; apiId: string } | null>(
  null,
)
const businessProcessors = ref<ServiceProcessor[]>([])
const dataLayerProcessors = ref<ServiceProcessor[]>([])
const flowProcessorsLoading = ref(false)
const apiFlowSelectedNodeId = ref<string | null>(null)
const apiFlowDebugCursorId = ref<string | null>(null)
const apiFlowDebugVisitedIds = ref<string[]>([])
const apiFlowDebugPrintByNode = ref<Record<string, string>>({})

const apiFlowEditingApi = computed(() => {
  const ctx = apiFlowEditing.value
  if (!ctx) return null
  const ctrl = controllers.value.find((c) => c.id === ctx.controllerId)
  return ctrl?.apis.find((a) => a.id === ctx.apiId) ?? null
})

const apiFlowEditingFlow = computed(
  () => apiFlowEditingApi.value?.flow ?? createDefaultMethodFlow(),
)

const selectedApi = computed(
  () => apis.value.find((a) => a.id === selectedApiId.value) ?? null,
)

function findTypeDef(id: string) {
  if (!id) return null
  for (const group of props.typeLibrary?.groups ?? []) {
    const hit = group.types.find((t) => t.id === id)
    if (hit) return hit
  }
  return null
}

function buildApiMethodParams(api: ServiceApi): ProcessorMethodParam[] {
  if (!api.inputs?.length) return []
  return api.inputs.map((p) => {
    const varName =
      p.varName.trim().replace(/[^A-Za-z0-9_]/g, '_') || 'input'
    const def = p.typeRef ? findTypeDef(p.typeRef) : null
    const type = p.typeRef ? 'json' : p.type || 'string'
    return {
      id: p.id || `api_input_${varName}`,
      name: varName,
      remark: p.remark || def?.remark || `${p.location} · ${varName}`,
      typeExpr: {
        ...createEmptyProcessorTypeExpr(type),
        typeRef: p.typeRef || '',
      },
      required: Boolean(p.required),
    }
  })
}

/** API 入参：供流程图环境变量使用（非 body 对象已平铺） */
const apiFlowMethodParams = computed((): ProcessorMethodParam[] => {
  const api = apiFlowEditingApi.value
  if (!api) return []
  return buildApiMethodParams(api)
})

const apiFlowMethodOutput = computed(
  (): ProcessorTypeExpr => createEmptyProcessorTypeExpr(),
)

function apiAsProcessorMethod(api: ServiceApi): ProcessorMethod {
  return {
    id: api.id,
    name: api.name,
    remark: api.remark,
    scope: api.scope === 'private' ? 'private' : 'public',
    params: buildApiMethodParams(api),
    output: api.output ?? createEmptyProcessorTypeExpr(),
    dataConfig: createEmptyDataMethodConfig(),
    debugParams: api.debugParams ?? {},
    flow: api.flow ?? createDefaultMethodFlow(),
  }
}

const apiFlowDebugTarget = computed<ProcessorDebugTarget | null>(() => {
  if (activeLayer.value !== 'controller') return null
  if (!props.projectPath || !props.serviceId) return null

  if (apiFlowEditing.value && apiFlowEditingApi.value) {
    const api = apiFlowEditingApi.value
    const ctrl = activeController.value
    return {
      kind: 'flow',
      projectPath: props.projectPath,
      serviceId: props.serviceId,
      processorId: ctrl?.id || 'controller',
      processorName: ctrl?.name || '控制器',
      method: apiAsProcessorMethod(api),
      flow: api.flow ?? createDefaultMethodFlow(),
      selectedNodeId: apiFlowSelectedNodeId.value,
      dataProcessors: dataLayerProcessors.value,
      businessProcessors: businessProcessors.value,
      mode: 'canvas',
    }
  }

  if (!selectedApi.value) return null
  return {
    kind: 'flow',
    projectPath: props.projectPath,
    serviceId: props.serviceId,
    processorId: activeController.value?.id || 'controller',
    processorName: activeController.value?.name || '控制器',
    method: apiAsProcessorMethod(selectedApi.value),
    flow: selectedApi.value.flow ?? createDefaultMethodFlow(),
    selectedNodeId: apiFlowSelectedNodeId.value || 'start',
    dataProcessors: dataLayerProcessors.value,
    businessProcessors: businessProcessors.value,
    mode: 'list',
  }
})

watch(
  apiFlowDebugTarget,
  (target) => {
    if (activeLayer.value !== 'controller') return
    emit('update:debug-target', target)
  },
  { immediate: true },
)

async function loadFlowProcessors() {
  if (!props.projectPath || !props.serviceId) {
    businessProcessors.value = []
    dataLayerProcessors.value = []
    return
  }
  flowProcessorsLoading.value = true
  try {
    const [biz, data] = await Promise.all([
      getServiceProcessors(props.projectPath, props.serviceId, 'business'),
      getServiceProcessors(props.projectPath, props.serviceId, 'data'),
    ])
    businessProcessors.value = biz.processors
    dataLayerProcessors.value = data.processors
  } catch (err) {
    businessProcessors.value = []
    dataLayerProcessors.value = []
    console.error(err)
  } finally {
    flowProcessorsLoading.value = false
  }
}

watch(
  () =>
    [
      activeLayer.value,
      props.projectPath,
      props.serviceId,
    ] as const,
  ([layer, path, id]) => {
    if (layer === 'controller' && path && id) void loadFlowProcessors()
  },
  { immediate: true },
)

function clearApiFlowDebug() {
  apiFlowSelectedNodeId.value = null
  apiFlowDebugCursorId.value = null
  apiFlowDebugVisitedIds.value = []
  apiFlowDebugPrintByNode.value = {}
}

function onApiFlowSelectedNode(nodeId: string | null) {
  apiFlowSelectedNodeId.value = nodeId
}

function onApiFlowDebugCursor(state: {
  cursorNodeId: string | null
  visitedNodeIds: string[]
  printByNode?: Record<string, string>
}) {
  apiFlowDebugCursorId.value = state.cursorNodeId
  apiFlowDebugVisitedIds.value = state.visitedNodeIds
  apiFlowDebugPrintByNode.value = state.printByNode ?? {}
}

function updateApiDebugParams(params: Record<string, unknown>) {
  const apiId = apiFlowEditing.value?.apiId ?? selectedApiId.value
  const ctrlId = apiFlowEditing.value?.controllerId ?? activeControllerId.value
  if (!apiId || !ctrlId) return
  controllers.value = controllers.value.map((c) => {
    if (c.id !== ctrlId) return c
    return {
      ...c,
      apis: c.apis.map((a) =>
        a.id === apiId ? { ...a, debugParams: { ...params } } : a,
      ),
    }
  })
  persistControllers()
}

/** 编辑：打开弹窗（流程图已移除） */
async function openApiFlow(index: number) {
  openApiEdit(index)
}

function closeApiFlow() {
  apiFlowEditing.value = null
  clearApiFlowDebug()
}

function updateApiFlow(apiId: string, flow: import('../../types/backend-services').MethodFlow) {
  const ctrlId = activeControllerId.value
  if (!ctrlId) return
  controllers.value = controllers.value.map((c) => {
    if (c.id !== ctrlId) return c
    return {
      ...c,
      apis: c.apis.map((a) => (a.id === apiId ? { ...a, flow } : a)),
    }
  })
  persistControllers()
}

function onApiFlowUpdate(flow: import('../../types/backend-services').MethodFlow) {
  const ctx = apiFlowEditing.value
  if (!ctx) return
  updateApiFlow(ctx.apiId, flow)
}

watch(
  () => [props.projectPath, props.serviceId] as const,
  () => {
    apiFlowEditing.value = null
    clearApiFlowDebug()
  },
)

watch(activeControllerId, () => {
  apiFlowEditing.value = null
  clearApiFlowDebug()
})

watch(selectedApiId, () => {
  if (!apiFlowEditing.value) clearApiFlowDebug()
})

async function removeApi(index: number) {
  const target = apis.value[index]
  if (!target) return
  try {
    await ElMessageBox.confirm(
      `确定删除 API「${target.name || target.path || target.id}」？`,
      '删除 API',
      { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' },
    )
  } catch {
    return
  }
  if (selectedApiId.value === target.id) selectedApiId.value = ''
  if (apiFlowEditing.value?.apiId === target.id) apiFlowEditing.value = null
  patchActiveApis(apis.value.filter((_, i) => i !== index))
}

watch(
  apis,
  (list) => {
    if (!list.length) {
      selectedApiId.value = ''
      return
    }
    if (!list.some((a) => a.id === selectedApiId.value)) {
      selectedApiId.value = list[0]!.id
    }
  },
  { deep: true },
)

onBeforeUnmount(() => {
  apiFlowEditing.value = null
  emit('update:debug-target', null)
})
</script>

<template>
  <div class="svc-workspace">
    <div
      v-if="activeLayer === 'controller'"
      class="svc-workspace-body"
    >
      <aside class="ctrl-pane">
        <el-skeleton v-if="loading" :rows="4" animated style="padding: 12px" />
        <el-empty
          v-else-if="!controllers.length"
          description="暂无控制器，点击顶部创建"
          :image-size="56"
        />
        <ul v-else class="ctrl-list">
          <el-dropdown
            v-for="ctrl in controllers"
            :key="ctrl.id"
            trigger="contextmenu"
            class="ctrl-dropdown"
            @command="
              (cmd: string) =>
                cmd === 'edit'
                  ? openEditDialog(ctrl)
                  : void removeController(ctrl)
            "
          >
            <li
              class="ctrl-item"
              :class="{ active: ctrl.id === activeControllerId }"
              @click="activeControllerId = ctrl.id"
              @dblclick="openEditDialog(ctrl)"
              @contextmenu.prevent
            >
              <span
                class="ctrl-name"
                :title="ctrl.remark || ctrl.path || ctrl.name"
              >
                {{ ctrl.name }}
              </span>
              <span v-if="ctrl.path" class="ctrl-path">({{ ctrl.path }})</span>
            </li>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item command="edit">编辑</el-dropdown-item>
                <el-dropdown-item command="delete" divided>
                  删除
                </el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </ul>
      </aside>

      <section class="api-pane">
        <el-empty
          v-if="!activeController"
          description="请选择或创建左侧控制器"
          :image-size="64"
        />
        <div v-else class="api-table">
          <el-table
            :data="apis"
            border
            stripe
            empty-text="暂无 API，点击顶部创建"
            highlight-current-row
            :row-class-name="
              ({ row }: { row: ServiceApi }) =>
                row.id === selectedApiId ? 'is-selected-row' : ''
            "
            @row-click="(row: ServiceApi) => (selectedApiId = row.id)"
          >
            <el-table-column label="名称" min-width="100">
              <template #default="{ row }">
                <span class="cell-text">{{ row.name || '—' }}</span>
              </template>
            </el-table-column>
            <el-table-column label="路径" min-width="110">
              <template #default="{ row }">
                <span class="cell-text muted">{{ row.path || '/' }}</span>
              </template>
            </el-table-column>
            <el-table-column label="说明" min-width="100">
              <template #default="{ row }">
                <span class="cell-text muted">{{ row.remark || '—' }}</span>
              </template>
            </el-table-column>
            <el-table-column label="请求方法" width="88" align="center">
              <template #default="{ row }">
                <span class="cell-text">{{ row.method }}</span>
              </template>
            </el-table-column>
            <el-table-column label="入参" min-width="180">
              <template #default="{ row }">
                <span
                  v-if="!apiInputItems(row).length"
                  class="cell-text muted"
                >无</span>
                <span
                  v-else
                  class="api-inputs"
                  :title="apiInputsTitle(row)"
                >
                  <template
                    v-for="(item, i) in apiInputItems(row)"
                    :key="`${item.location}-${item.name}-${i}`"
                  >
                    <span
                      v-if="i > 0"
                      class="api-inputs-sep"
                    >、</span>
                    <span
                      class="api-input-name"
                      :class="item.className"
                    >{{ item.name }}</span>
                  </template>
                </span>
              </template>
            </el-table-column>
            <el-table-column label="鉴权" width="64" align="center">
              <template #default="{ row }">
                <span class="cell-text">{{ row.requireAuth ? '是' : '否' }}</span>
              </template>
            </el-table-column>
            <el-table-column label="操作" width="140" align="center" fixed="right">
              <template #default="{ $index }">
                <el-button
                  type="primary"
                  link
                  :icon="EditPen"
                  @click.stop="openApiEdit($index)"
                >
                  编辑
                </el-button>
                <el-button
                  type="danger"
                  link
                  :icon="Delete"
                  @click.stop="removeApi($index)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </section>
    </div>
    <ServiceProcessorPanel
      v-else-if="activeLayer === 'service'"
      ref="businessProcessorPanelRef"
      :project-path="projectPath"
      :service-id="serviceId"
      layer="business"
      :type-library="typeLibrary"
      :module-options="moduleOptions ?? []"
      :restored="restoredBusiness"
      @update:debug-target="onDebugTarget"
      @update:selection="emit('update:business-selection', $event)"
    />
    <ServiceProcessorPanel
      v-else-if="activeLayer === 'data'"
      ref="dataProcessorPanelRef"
      :project-path="projectPath"
      :service-id="serviceId"
      layer="data"
      :type-library="typeLibrary"
      :module-options="moduleOptions ?? []"
      :restored="
        restoredData
          ? {
              processorId: restoredData.processorId,
              methodId: restoredData.methodId,
              flowEditing: null,
            }
          : null
      "
      @update:debug-target="onDebugTarget"
      @update:selection="emit('update:data-selection', $event)"
    />
    <div v-else class="layer-placeholder">
      <el-empty description="定时任务稍后实现" :image-size="80" />
    </div>

    <el-dialog
      v-model="dialogVisible"
      title="控制器"
      width="420px"
      destroy-on-close
      append-to-body
    :close-on-click-modal="false"
    :close-on-press-escape="false"
  >
      <el-form label-width="64px" @submit.prevent="submitDialog">
        <el-form-item label="名称">
          <el-input
            v-model="dialogName"
            placeholder="如 goods"
            maxlength="64"
            autofocus
          />
        </el-form-item>
        <el-form-item label="路径">
          <el-input
            v-model="dialogPath"
            placeholder="如 /goods"
            maxlength="128"
          />
        </el-form-item>
        <el-form-item label="说明">
          <el-input
            v-model="dialogRemark"
            type="textarea"
            :rows="2"
            placeholder="可选说明"
            maxlength="256"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button type="primary" @click="submitDialog">确定</el-button>
      </template>
    </el-dialog>

    <EditServiceApiDialog
      v-model="apiDialogVisible"
      :api="editingApi"
      :dto-options="dtoOptions"
      :type-library="typeLibrary"
      :reserved-names="apiReservedNames"
      :project-path="projectPath"
      :service-id="serviceId"
      @save="saveApiEdit"
    />
  </div>
</template>

<style scoped>
.svc-workspace {
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  background: #fff;
}

.svc-workspace-body {
  flex: 1;
  min-height: 0;
  display: grid;
  grid-template-columns: 220px 1fr;
  overflow: hidden;
}

.ctrl-pane,
.api-pane {
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.ctrl-pane {
  border-right: 1px solid #ebeef5;
  background: #fafafa;
}

.ctrl-list {
  margin: 0;
  padding: 8px;
  list-style: none;
  overflow: auto;
  flex: 1;
  min-height: 0;
}

.ctrl-dropdown {
  display: block;
  width: 100%;
  margin-bottom: 4px;
}

.ctrl-dropdown :deep(.el-tooltip__trigger) {
  display: block;
  width: 100%;
}

.ctrl-item {
  display: flex;
  align-items: center;
  gap: 2px;
  padding: 8px 10px;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.15s;
  list-style: none;
}

.ctrl-item:hover {
  background: #f0f2f5;
}

.ctrl-item.active {
  background: #ecf5ff;
}

.ctrl-name {
  flex: 1;
  min-width: 0;
  font-size: 13px;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ctrl-path {
  flex-shrink: 0;
  max-width: 72px;
  margin-right: 2px;
  font-size: 11px;
  color: #94a3b8;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.api-table {
  flex: 1;
  min-height: 0;
  overflow: auto;
  padding: 12px;
}

.api-inputs {
  display: inline;
  font-size: 13px;
  line-height: 1.4;
  word-break: break-all;
}

.api-inputs-sep {
  color: #c0c4cc;
}

.api-input-name.api-in-query {
  color: #67c23a;
}

.api-input-name.api-in-param {
  color: #e6a23c;
}

.api-input-name.api-in-body {
  color: #9b59b6;
}

.api-input-name.api-in-header {
  color: #409eff;
}

.layer-placeholder {
  flex: 1;
  min-height: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

.cell-text {
  font-size: 13px;
  color: #303133;
  word-break: break-all;
}

.cell-text.muted {
  color: #909399;
}

.api-table :deep(.is-selected-row > td.el-table__cell) {
  background: #ecf5ff !important;
}
</style>

// frontend/src/components/editor/BackendServiceWorkspace.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
  useState,
} from 'react'
import {
  Button,
  Dropdown,
  Empty,
  Form,
  Input,
  Modal,
  Skeleton,
  Table,
} from 'antd'
import { DeleteOutlined, EditOutlined } from '@ant-design/icons'
import { ElMessage, ElMessageBox } from '../../ui/feedback'
import {
  getServiceControllers,
  getServiceProcessors,
  saveServiceControllers as saveServiceControllersApi,
} from '../../api/projects'
import {
  createDefaultMethodFlow,
  createEmptyDataMethodConfig,
  createEmptyProcessorTypeExpr,
  createEmptyServiceApi,
  createEmptyServiceController,
  isValidControllerName,
  type ProcessorMethod,
  type ProcessorMethodParam,
  type ServiceApi,
  type ServiceApiParamLocation,
  type ServiceController,
  type ServiceProcessor,
} from '../../types/backend-services'
import type { DataTypeLibrary } from '../../types/data-types'
import EditServiceApiDialog, {
  type ServiceApiEditPayload,
} from './EditServiceApiDialog'
import ServiceProcessorPanel, {
  isSameProcessorDebugTarget,
  type ProcessorDebugTarget,
  type ProcessorSelectionState,
  type ServiceProcessorPanelHandle,
} from './ServiceProcessorPanel'
import type { DataMethodUsageRef } from '../../utils/data-method-usage'
import './BackendServiceWorkspace.css'

type ServiceLayer = 'controller' | 'service' | 'data' | 'schedule'

export type BackendServiceWorkspaceHandle = {
  applyDebugParams: (params: Record<string, unknown>) => void
  applyFlowDebugCursor: (state: {
    cursorNodeId: string | null
    visitedNodeIds: string[]
    printByNode?: Record<string, string>
  }) => void
  openBusinessFlowAt: (options: {
    processorId: string
    methodId: string
    focusNodeId?: string
  }) => boolean
  openCreateController: () => void
  addApi: () => void
  openCreateProcessor: () => void
  addProcessorMethod: () => void
}

export default forwardRef<
  BackendServiceWorkspaceHandle,
  {
    projectPath: string
    serviceId: string
    serviceName: string
    typeLibrary: DataTypeLibrary | null
    moduleOptions?: Array<{ id: string; name: string }>
    layer?: ServiceLayer
    restoredControllerId?: string
    restoredBusiness?: {
      processorId: string
      methodId: string
      flowEditing: {
        processorId: string
        methodId: string
        focusNodeId?: string
      } | null
    } | null
    restoredData?: {
      processorId: string
      methodId: string
    } | null
    onLayerChange?: (layer: ServiceLayer) => void
    onDebugTargetChange?: (target: ProcessorDebugTarget | null) => void
    onControllerIdChange?: (id: string) => void
    onBusinessSelectionChange?: (state: ProcessorSelectionState) => void
    onDataSelectionChange?: (state: ProcessorSelectionState) => void
    onNavigateUsage?: (ref: DataMethodUsageRef) => void
  }
>(function BackendServiceWorkspace(
  {
    projectPath,
    serviceId,
    typeLibrary,
    moduleOptions,
    layer,
    restoredControllerId,
    restoredBusiness,
    restoredData,
    onDebugTargetChange,
    onControllerIdChange,
    onBusinessSelectionChange,
    onDataSelectionChange,
    onNavigateUsage,
  },
  ref,
) {
  const dataProcessorPanelRef = useRef<ServiceProcessorPanelHandle | null>(null)
  const businessProcessorPanelRef = useRef<ServiceProcessorPanelHandle | null>(
    null,
  )

  const activeLayer = layer ?? 'controller'
  const [controllers, setControllers] = useState<ServiceController[]>([])
  const [activeControllerId, setActiveControllerId] = useState('')
  const [loading, setLoading] = useState(false)
  const [dialogVisible, setDialogVisible] = useState(false)
  const [dialogName, setDialogName] = useState('')
  const [dialogPath, setDialogPath] = useState('')
  const [dialogRemark, setDialogRemark] = useState('')
  const [editingControllerId, setEditingControllerId] = useState<string | null>(
    null,
  )

  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null)

  const [apiDialogVisible, setApiDialogVisible] = useState(false)
  const [apiEditIndex, setApiEditIndex] = useState(-1)
  const [apiDraft, setApiDraft] = useState<ServiceApi | null>(null)
  const [selectedApiId, setSelectedApiId] = useState('')

  const [apiFlowEditing, setApiFlowEditing] = useState<{
    controllerId: string
    apiId: string
  } | null>(null)
  const [businessProcessors, setBusinessProcessors] = useState<
    ServiceProcessor[]
  >([])
  const [dataLayerProcessors, setDataLayerProcessors] = useState<
    ServiceProcessor[]
  >([])
  const [apiFlowSelectedNodeId, setApiFlowSelectedNodeId] = useState<
    string | null
  >(null)
  const [, setApiFlowDebugCursorId] = useState<string | null>(null)
  const [, setApiFlowDebugVisitedIds] = useState<string[]>([])
  const [, setApiFlowDebugPrintByNode] = useState<Record<string, string>>(
    {},
  )

  const activeController =
    controllers.find((c) => c.id === activeControllerId) ?? null
  const apis = activeController?.apis ?? []

  const dtoOptions = useMemo(() => {
    const opts: Array<{ id: string; label: string }> = []
    for (const group of typeLibrary?.groups ?? []) {
      for (const t of group.types) {
        if (t.category === 'dto' || (!t.category && t.kind === 'interface')) {
          opts.push({
            id: t.id,
            label: t.name ? `${t.name}${t.remark ? ` · ${t.remark}` : ''}` : t.id,
          })
        }
      }
    }
    return opts
  }, [typeLibrary])

  function persistControllers(next = controllers) {
    if (!projectPath || !serviceId) return
    if (saveTimer.current) clearTimeout(saveTimer.current)
    saveTimer.current = setTimeout(async () => {
      try {
        const res = await saveServiceControllersApi({
          projectPath,
          serviceId,
          controllers: next,
        })
        setControllers(res.controllers)
      } catch (err) {
        ElMessage.error(err instanceof Error ? err.message : '保存控制器失败')
      }
    }, 400)
  }

  async function loadControllers() {
    if (!projectPath || !serviceId) return
    setLoading(true)
    try {
      const res = await getServiceControllers(projectPath, serviceId)
      setControllers(res.controllers)
    } catch (err) {
      ElMessage.error(err instanceof Error ? err.message : '加载控制器失败')
      setControllers([])
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    if (projectPath && serviceId) void loadControllers()
    else {
      setControllers([])
      setActiveControllerId('')
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectPath, serviceId])

  useEffect(() => {
    if (!controllers.length) {
      setActiveControllerId('')
      return
    }
    const prefer = restoredControllerId
    if (prefer && controllers.some((c) => c.id === prefer)) {
      setActiveControllerId(prefer)
      return
    }
    if (!controllers.some((c) => c.id === activeControllerId)) {
      setActiveControllerId(controllers[0]!.id)
    }
  }, [controllers, restoredControllerId, activeControllerId])

  useEffect(() => {
    onControllerIdChange?.(activeControllerId)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeControllerId])

  const lastEmittedDebugRef = useRef<ProcessorDebugTarget | null>(null)

  useEffect(() => {
    if (layer !== 'schedule') return
    if (lastEmittedDebugRef.current == null) return
    lastEmittedDebugRef.current = null
    onDebugTargetChange?.(null)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layer])

  function onDebugTarget(target: ProcessorDebugTarget | null) {
    if (activeLayer === 'controller') return
    if (isSameProcessorDebugTarget(lastEmittedDebugRef.current, target)) return
    lastEmittedDebugRef.current = target
    onDebugTargetChange?.(target)
  }

  function openCreateDialog() {
    setEditingControllerId(null)
    setDialogName('')
    setDialogPath('')
    setDialogRemark('')
    setDialogVisible(true)
  }

  function openEditDialog(ctrl: ServiceController) {
    setEditingControllerId(ctrl.id)
    setDialogName(ctrl.name)
    setDialogPath(ctrl.path)
    setDialogRemark(ctrl.remark)
    setDialogVisible(true)
  }

  function submitDialog() {
    const name = dialogName.trim()
    if (!name) {
      ElMessage.warning('请输入控制器名称')
      return
    }
    if (!isValidControllerName(name)) {
      ElMessage.warning('名称须为英文大驼峰，如 Goods')
      return
    }
    const path = dialogPath.trim()
    const remark = dialogRemark.trim()
    const nameTaken = controllers.some(
      (c) =>
        c.name.trim().toLowerCase() === name.toLowerCase() &&
        c.id !== editingControllerId,
    )
    if (nameTaken) {
      ElMessage.warning(`控制器名称「${name}」已存在`)
      return
    }

    let next = controllers
    if (editingControllerId) {
      next = controllers.map((c) =>
        c.id === editingControllerId ? { ...c, name, path, remark } : c,
      )
    } else {
      const created = {
        ...createEmptyServiceController(name),
        path,
        remark,
      }
      next = [...controllers, created]
      setActiveControllerId(created.id)
    }
    setControllers(next)
    setDialogVisible(false)
    persistControllers(next)
  }

  async function removeController(ctrl: ServiceController) {
    try {
      await ElMessageBox.confirm(
        `确定删除控制器「${ctrl.name}」？其下 API 将一并删除。`,
        '删除控制器',
        { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' },
      )
    } catch {
      return
    }
    const next = controllers.filter((c) => c.id !== ctrl.id)
    setControllers(next)
    persistControllers(next)
  }

  function patchActiveApis(nextApis: ServiceApi[]) {
    const id = activeControllerId
    if (!id) return
    const next = controllers.map((c) =>
      c.id === id ? { ...c, apis: nextApis } : c,
    )
    setControllers(next)
    persistControllers(next)
  }

  const apiReservedNames = apis
    .filter((_, i) => i !== apiEditIndex)
    .map((a) => a.name.trim())
    .filter(Boolean)

  function apiInputLocationClass(location: ServiceApiParamLocation): string {
    switch (location) {
      case 'query':
        return 'api-in-query'
      case 'param':
        return 'api-in-param'
      case 'body':
        return 'api-in-body'
      case 'httpHeader':
        return 'api-in-header'
      default:
        return ''
    }
  }

  function apiInputItems(api: ServiceApi): Array<{
    name: string
    location: ServiceApiParamLocation
    className: string
  }> {
    return (api.inputs ?? [])
      .map((p) => {
        const name = p.varName.trim()
        if (!name) return null
        return {
          name,
          location: p.location,
          className: apiInputLocationClass(p.location),
        }
      })
      .filter((x): x is NonNullable<typeof x> => Boolean(x))
  }

  function apiInputsTitle(api: ServiceApi): string {
    const list = apiInputItems(api)
    if (!list.length) return '无'
    return list.map((p) => `${p.location}:${p.name}`).join('、')
  }

  function openApiEdit(index: number) {
    if (!activeController) return
    setApiEditIndex(index)
    if (index < 0) {
      setApiDraft(createEmptyServiceApi(`api${apis.length + 1}`))
    } else {
      const api = apis[index]
      if (!api) return
      setApiDraft({
        ...api,
        inputs: (api.inputs ?? []).map((p) => ({ ...p })),
        output: api.output
          ? { ...api.output, genericArgs: { ...(api.output.genericArgs ?? {}) } }
          : createEmptyProcessorTypeExpr('any'),
        scope: api.scope === 'private' ? 'private' : 'public',
        flow: api.flow ?? createDefaultMethodFlow(),
      })
      setSelectedApiId(api.id)
    }
    setApiDialogVisible(true)
  }

  function addApi() {
    if (!activeController) {
      ElMessage.warning('请先选择或创建控制器')
      return
    }
    openApiEdit(-1)
  }

  function saveApiEdit(payload: ServiceApiEditPayload) {
    if (apiEditIndex < 0) {
      const base = apiDraft ?? createEmptyServiceApi(payload.name)
      patchActiveApis([
        ...apis,
        {
          ...base,
          name: payload.name,
          path: payload.path,
          remark: payload.remark,
          method: payload.method,
          inputs: payload.inputs,
          output: payload.output,
          requireAuth: payload.requireAuth,
          scope: payload.scope,
          flow: payload.flow ?? createDefaultMethodFlow(),
        },
      ])
      setSelectedApiId(base.id)
    } else {
      patchActiveApis(
        apis.map((api, i) =>
          i === apiEditIndex
            ? {
                ...api,
                name: payload.name,
                path: payload.path,
                remark: payload.remark,
                method: payload.method,
                inputs: payload.inputs,
                output: payload.output,
                requireAuth: payload.requireAuth,
                scope: payload.scope,
                flow: payload.flow ?? api.flow ?? createDefaultMethodFlow(),
              }
            : api,
        ),
      )
    }
    setApiEditIndex(-1)
    setApiDraft(null)
  }

  function findTypeDef(id: string) {
    if (!id) return null
    for (const group of typeLibrary?.groups ?? []) {
      const hit = group.types.find((t) => t.id === id)
      if (hit) return hit
    }
    return null
  }

  function buildApiMethodParams(api: ServiceApi): ProcessorMethodParam[] {
    if (!api.inputs?.length) return []
    return api.inputs.map((p) => {
      const varName = p.varName.trim().replace(/[^A-Za-z0-9_]/g, '_') || 'input'
      const def = p.typeRef ? findTypeDef(p.typeRef) : null
      const type = p.typeRef ? 'json' : p.type || 'string'
      return {
        id: p.id || `api_input_${varName}`,
        name: varName,
        remark: p.remark || def?.remark || `${p.location} · ${varName}`,
        typeExpr: {
          ...createEmptyProcessorTypeExpr(type),
          typeRef: p.typeRef || '',
        },
        required: Boolean(p.required),
      }
    })
  }

  function apiAsProcessorMethod(api: ServiceApi): ProcessorMethod {
    return {
      id: api.id,
      name: api.name,
      remark: api.remark,
      scope: api.scope === 'private' ? 'private' : 'public',
      params: buildApiMethodParams(api),
      output: api.output ?? createEmptyProcessorTypeExpr(),
      dataConfig: createEmptyDataMethodConfig(),
      debugParams: api.debugParams ?? {},
      flow: api.flow ?? createDefaultMethodFlow(),
    }
  }

  const selectedApi = apis.find((a) => a.id === selectedApiId) ?? null
  const apiFlowEditingApi = (() => {
    if (!apiFlowEditing) return null
    const ctrl = controllers.find((c) => c.id === apiFlowEditing.controllerId)
    return ctrl?.apis.find((a) => a.id === apiFlowEditing.apiId) ?? null
  })()

  const apiFlowDebugTarget: ProcessorDebugTarget | null = (() => {
    if (activeLayer !== 'controller') return null
    if (!projectPath || !serviceId) return null
    if (apiFlowEditing && apiFlowEditingApi) {
      const api = apiFlowEditingApi
      const ctrl = activeController
      return {
        kind: 'flow',
        projectPath,
        serviceId,
        processorId: ctrl?.id || 'controller',
        processorName: ctrl?.name || '控制器',
        method: apiAsProcessorMethod(api),
        flow: api.flow ?? createDefaultMethodFlow(),
        selectedNodeId: apiFlowSelectedNodeId,
        dataProcessors: dataLayerProcessors,
        businessProcessors,
        mode: 'canvas',
      }
    }
    if (!selectedApi) return null
    return {
      kind: 'flow',
      projectPath,
      serviceId,
      processorId: activeController?.id || 'controller',
      processorName: activeController?.name || '控制器',
      method: apiAsProcessorMethod(selectedApi),
      flow: selectedApi.flow ?? createDefaultMethodFlow(),
      selectedNodeId: apiFlowSelectedNodeId || 'start',
      dataProcessors: dataLayerProcessors,
      businessProcessors,
      mode: 'list',
    }
  })()

  useEffect(() => {
    if (activeLayer !== 'controller') return
    if (isSameProcessorDebugTarget(lastEmittedDebugRef.current, apiFlowDebugTarget)) {
      return
    }
    lastEmittedDebugRef.current = apiFlowDebugTarget
    onDebugTargetChange?.(apiFlowDebugTarget)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeLayer, apiFlowDebugTarget])

  async function loadFlowProcessors() {
    if (!projectPath || !serviceId) {
      setBusinessProcessors([])
      setDataLayerProcessors([])
      return
    }
    try {
      const [biz, data] = await Promise.all([
        getServiceProcessors(projectPath, serviceId, 'business'),
        getServiceProcessors(projectPath, serviceId, 'data'),
      ])
      setBusinessProcessors(biz.processors)
      setDataLayerProcessors(data.processors)
    } catch (err) {
      setBusinessProcessors([])
      setDataLayerProcessors([])
      console.error(err)
    }
  }

  useEffect(() => {
    if (activeLayer === 'controller' && projectPath && serviceId) {
      void loadFlowProcessors()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeLayer, projectPath, serviceId])

  function clearApiFlowDebug() {
    setApiFlowSelectedNodeId(null)
    setApiFlowDebugCursorId(null)
    setApiFlowDebugVisitedIds([])
    setApiFlowDebugPrintByNode({})
  }

  function onApiFlowDebugCursor(state: {
    cursorNodeId: string | null
    visitedNodeIds: string[]
    printByNode?: Record<string, string>
  }) {
    setApiFlowDebugCursorId(state.cursorNodeId)
    setApiFlowDebugVisitedIds(state.visitedNodeIds)
    setApiFlowDebugPrintByNode(state.printByNode ?? {})
  }

  function updateApiDebugParams(params: Record<string, unknown>) {
    const apiId = apiFlowEditing?.apiId ?? selectedApiId
    const ctrlId = apiFlowEditing?.controllerId ?? activeControllerId
    if (!apiId || !ctrlId) return
    const next = controllers.map((c) => {
      if (c.id !== ctrlId) return c
      return {
        ...c,
        apis: c.apis.map((a) =>
          a.id === apiId ? { ...a, debugParams: { ...params } } : a,
        ),
      }
    })
    setControllers(next)
    persistControllers(next)
  }

  useEffect(() => {
    setApiFlowEditing(null)
    clearApiFlowDebug()
  }, [projectPath, serviceId])

  useEffect(() => {
    setApiFlowEditing(null)
    clearApiFlowDebug()
  }, [activeControllerId])

  useEffect(() => {
    if (!apiFlowEditing) clearApiFlowDebug()
  }, [selectedApiId])

  useEffect(() => {
    if (!apis.length) {
      setSelectedApiId('')
      return
    }
    if (!apis.some((a) => a.id === selectedApiId)) {
      setSelectedApiId(apis[0]!.id)
    }
  }, [apis, selectedApiId])

  useEffect(() => {
    return () => {
      setApiFlowEditing(null)
      onDebugTargetChange?.(null)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function removeApi(index: number) {
    const target = apis[index]
    if (!target) return
    try {
      await ElMessageBox.confirm(
        `确定删除 API「${target.name || target.path || target.id}」？`,
        '删除 API',
        { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' },
      )
    } catch {
      return
    }
    if (selectedApiId === target.id) setSelectedApiId('')
    if (apiFlowEditing?.apiId === target.id) setApiFlowEditing(null)
    patchActiveApis(apis.filter((_, i) => i !== index))
  }

  useImperativeHandle(ref, () => ({
    applyDebugParams(params) {
      if (activeLayer === 'controller') {
        updateApiDebugParams(params)
        return
      }
      if (activeLayer === 'service') {
        businessProcessorPanelRef.current?.updateDebugParams(params)
        return
      }
      dataProcessorPanelRef.current?.updateDebugParams(params)
    },
    applyFlowDebugCursor(state) {
      if (activeLayer === 'controller') {
        onApiFlowDebugCursor(state)
        return
      }
      businessProcessorPanelRef.current?.applyFlowDebugCursor(state)
    },
    openBusinessFlowAt: (options) =>
      businessProcessorPanelRef.current?.openFlowAt(options) ?? false,
    openCreateController: openCreateDialog,
    addApi,
    openCreateProcessor() {
      if (activeLayer === 'service') {
        businessProcessorPanelRef.current?.openCreateDialog()
      } else if (activeLayer === 'data') {
        dataProcessorPanelRef.current?.openCreateDialog()
      }
    },
    addProcessorMethod() {
      if (activeLayer === 'service') {
        businessProcessorPanelRef.current?.addMethod()
      } else if (activeLayer === 'data') {
        dataProcessorPanelRef.current?.addMethod()
      }
    },
  }))

  const apiColumns = [
    {
      title: '名称',
      key: 'name',
      minWidth: 100,
      render: (_: unknown, row: ServiceApi) => (
        <span className="cell-text">{row.name || '—'}</span>
      ),
    },
    {
      title: '路径',
      key: 'path',
      minWidth: 110,
      render: (_: unknown, row: ServiceApi) => (
        <span className="cell-text muted">{row.path || '/'}</span>
      ),
    },
    {
      title: '说明',
      key: 'remark',
      minWidth: 100,
      render: (_: unknown, row: ServiceApi) => (
        <span className="cell-text muted">{row.remark || '—'}</span>
      ),
    },
    {
      title: '请求方法',
      key: 'method',
      width: 88,
      align: 'center' as const,
      render: (_: unknown, row: ServiceApi) => (
        <span className="cell-text">{row.method}</span>
      ),
    },
    {
      title: '入参',
      key: 'inputs',
      minWidth: 180,
      render: (_: unknown, row: ServiceApi) =>
        !apiInputItems(row).length ? (
          <span className="cell-text muted">无</span>
        ) : (
          <span className="api-inputs" title={apiInputsTitle(row)}>
            {apiInputItems(row).map((item, i) => (
              <span key={`${item.location}-${item.name}-${i}`}>
                {i > 0 ? <span className="api-inputs-sep">、</span> : null}
                <span className={`api-input-name ${item.className}`}>
                  {item.name}
                </span>
              </span>
            ))}
          </span>
        ),
    },
    {
      title: '鉴权',
      key: 'requireAuth',
      width: 64,
      align: 'center' as const,
      render: (_: unknown, row: ServiceApi) => (
        <span className="cell-text">{row.requireAuth ? '是' : '否'}</span>
      ),
    },
    {
      title: '操作',
      key: 'actions',
      width: 140,
      align: 'center' as const,
      fixed: 'right' as const,
      render: (_: unknown, _row: ServiceApi, index: number) => (
        <>
          <Button
            type="link"
            icon={<EditOutlined />}
            onClick={(e) => {
              e.stopPropagation()
              openApiEdit(index)
            }}
          >
            编辑
          </Button>
          <Button
            type="link"
            danger
            icon={<DeleteOutlined />}
            onClick={(e) => {
              e.stopPropagation()
              void removeApi(index)
            }}
          >
            删除
          </Button>
        </>
      ),
    },
  ]

  return (
    <div className="svc-workspace">
      {activeLayer === 'controller' ? (
        <div className="svc-workspace-body">
          <aside className="ctrl-pane">
            {loading ? (
              <div style={{ padding: 12 }}>
                <Skeleton active paragraph={{ rows: 4 }} />
              </div>
            ) : !controllers.length ? (
              <Empty
                description="暂无控制器，点击顶部创建"
                styles={{ image: { height: 56 } }}
              />
            ) : (
              <ul className="ctrl-list">
                {controllers.map((ctrl) => (
                  <Dropdown
                    key={ctrl.id}
                    trigger={['contextMenu']}
                    menu={{
                      items: [
                        { key: 'edit', label: '编辑' },
                        { type: 'divider' },
                        { key: 'delete', label: '删除', danger: true },
                      ],
                      onClick: ({ key }) =>
                        key === 'edit'
                          ? openEditDialog(ctrl)
                          : void removeController(ctrl),
                    }}
                  >
                    <li
                      className={`ctrl-item${ctrl.id === activeControllerId ? ' active' : ''}`}
                      onClick={() => setActiveControllerId(ctrl.id)}
                      onDoubleClick={() => openEditDialog(ctrl)}
                      onContextMenu={(e) => e.preventDefault()}
                    >
                      <div className="ctrl-name" title={ctrl.name}>
                        {ctrl.name}
                      </div>
                      <div className="ctrl-meta">
                        <span
                          className={`ctrl-bind${!ctrl.path ? ' ctrl-bind--empty' : ''}`}
                          title={ctrl.path || undefined}
                        >
                          {ctrl.path || '—'}
                        </span>
                        <span className="ctrl-count">{ctrl.apis.length}个方法</span>
                      </div>
                      <div className="ctrl-desc" title={ctrl.remark || undefined}>
                        {ctrl.remark || '—'}
                      </div>
                    </li>
                  </Dropdown>
                ))}
              </ul>
            )}
          </aside>

          <section className="api-pane">
            {!activeController ? (
              <Empty
                description="请选择或创建左侧控制器"
                styles={{ image: { height: 64 } }}
              />
            ) : (
              <div className="api-table">
                <Table
                  dataSource={apis}
                  columns={apiColumns}
                  bordered
                  size="small"
                  pagination={false}
                  rowKey="id"
                  locale={{ emptyText: '暂无 API，点击顶部创建' }}
                  rowClassName={(row) =>
                    row.id === selectedApiId ? 'is-selected-row' : ''
                  }
                  onRow={(row) => ({
                    onClick: () => setSelectedApiId(row.id),
                  })}
                />
              </div>
            )}
          </section>
        </div>
      ) : activeLayer === 'service' ? (
        <ServiceProcessorPanel
          ref={businessProcessorPanelRef}
          projectPath={projectPath}
          serviceId={serviceId}
          layer="business"
          typeLibrary={typeLibrary}
          moduleOptions={moduleOptions ?? []}
          restored={restoredBusiness}
          onDebugTargetChange={onDebugTarget}
          onSelectionChange={onBusinessSelectionChange}
        />
      ) : activeLayer === 'data' ? (
        <ServiceProcessorPanel
          ref={dataProcessorPanelRef}
          projectPath={projectPath}
          serviceId={serviceId}
          layer="data"
          typeLibrary={typeLibrary}
          moduleOptions={moduleOptions ?? []}
          restored={
            restoredData
              ? {
                  processorId: restoredData.processorId,
                  methodId: restoredData.methodId,
                  flowEditing: null,
                }
              : null
          }
          onDebugTargetChange={onDebugTarget}
          onSelectionChange={onDataSelectionChange}
          onNavigateUsage={onNavigateUsage}
        />
      ) : (
        <div className="layer-placeholder">
          <Empty description="定时任务稍后实现" styles={{ image: { height: 80 } }} />
        </div>
      )}

      <Modal
        open={dialogVisible}
        title="控制器"
        width={420}
        destroyOnHidden
        maskClosable={false}
        keyboard={false}
        onCancel={() => setDialogVisible(false)}
        footer={
          <Button type="primary" onClick={submitDialog}>
            确定
          </Button>
        }
      >
        <Form
          labelCol={{ style: { width: 64 } }}
          onSubmitCapture={(e) => {
            e.preventDefault()
            submitDialog()
          }}
        >
          <Form.Item label="名称">
            <Input
              value={dialogName}
              placeholder="英文大驼峰，如 Goods"
              maxLength={64}
              autoFocus
              onChange={(e) => setDialogName(e.target.value)}
            />
            <p className="field-hint">仅英文，须大驼峰（PascalCase）</p>
          </Form.Item>
          <Form.Item label="路径">
            <Input
              value={dialogPath}
              placeholder="如 /goods"
              maxLength={128}
              onChange={(e) => setDialogPath(e.target.value)}
            />
          </Form.Item>
          <Form.Item label="说明">
            <Input.TextArea
              value={dialogRemark}
              rows={2}
              placeholder="可选说明"
              maxLength={256}
              onChange={(e) => setDialogRemark(e.target.value)}
            />
          </Form.Item>
        </Form>
      </Modal>

      <EditServiceApiDialog
        open={apiDialogVisible}
        onOpenChange={setApiDialogVisible}
        api={apiDraft}
        dtoOptions={dtoOptions}
        typeLibrary={typeLibrary}
        reservedNames={apiReservedNames}
        projectPath={projectPath}
        serviceId={serviceId}
        onSave={saveApiEdit}
      />
    </div>
  )
})
