// frontend/src/components/editor/ColorPicker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { Aim } from '@element-plus/icons-vue'
import { colorPickState } from '../../composables/useColorPick'
import { colorPaletteState } from '../../composables/useColorPalette'
import {
  findPaletteColor,
  type PaletteColor,
} from '../../types/color-palette'

const props = withDefaults(
  defineProps<{
    modelValue: string
    placeholder?: string
    /** 为 true 时隐藏调色板选择（如调色板编辑对话框内） */
    hidePalette?: boolean
    /**
     * 紧凑模式：只显示色块 + 值，点击弹出完整选择器
     *（属性面板常量行用）
     */
    compact?: boolean
  }>(),
  {
    hidePalette: false,
    compact: false,
  },
)

const popoverVisible = ref(false)

const emit = defineEmits<{
  'update:modelValue': [value: string]
  change: [value: string]
}>()

/** 快捷参考色 */
const PRESET_COLORS = [
  { label: '透明', value: 'transparent' },
  { label: '白', value: '#ffffff' },
  { label: '黑', value: '#000000' },
] as const

/** el-color-picker 预置（含透明） */
const PREDEFINE = ['transparent', '#ffffff', '#000000', '#409eff', '#67c23a', '#e6a23c', '#f56c6c']

const paletteColors = computed<PaletteColor[]>(() => {
  if (props.hidePalette) return []
  return colorPaletteState.value.colors
})

const localValue = ref(normalizeColor(props.modelValue))

watch(
  () => props.modelValue,
  (value) => {
    localValue.value = normalizeColor(value)
  },
)

const isBinding = computed(() => /\{[^{}]+\}/.test(localValue.value.trim()))

const activePaletteColor = computed(() =>
  findPaletteColor(
    { colors: paletteColors.value },
    localValue.value.trim(),
  ),
)

const isPaletteKey = computed(() => Boolean(activePaletteColor.value))

/** 供 el-color-picker 使用的可解析色值 */
const pickerModel = computed({
  get() {
    if (activePaletteColor.value) {
      return toPickerColor(activePaletteColor.value.value)
    }
    return toPickerColor(localValue.value)
  },
  set(value: string | null) {
    if (value == null || value === '') {
      commit('transparent')
      return
    }
    commit(formatOutgoingColor(value))
  },
})

function normalizeColor(value: unknown): string {
  return String(value ?? '').trim()
}

function toPickerColor(value: string): string {
  const trimmed = value.trim()
  if (!trimmed || trimmed === 'transparent' || /\{[^{}]+\}/.test(trimmed)) {
    return 'rgba(255, 255, 255, 0)'
  }
  if (/^rgba?\(/i.test(trimmed) || /^hsla?\(/i.test(trimmed)) return trimmed
  if (/^#[0-9a-f]{8}$/i.test(trimmed)) return hex8ToRgba(trimmed)
  if (/^#[0-9a-f]{6}$/i.test(trimmed)) return trimmed
  if (/^#[0-9a-f]{3}$/i.test(trimmed)) {
    const [, r, g, b] = trimmed
    return `#${r}${r}${g}${g}${b}${b}`
  }
  return '#ffffff'
}

function hex8ToRgba(hex: string): string {
  const h = hex.slice(1)
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  const a = parseInt(h.slice(6, 8), 16) / 255
  const alpha = Math.round(a * 1000) / 1000
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

/** 写出：全透明 → transparent；不透明 hex → #rrggbb；半透明 → rgba */
function formatOutgoingColor(value: string): string {
  const trimmed = value.trim()
  if (!trimmed) return 'transparent'

  const rgba = parseRgba(trimmed)
  if (rgba) {
    if (rgba.a <= 0.005) return 'transparent'
    if (rgba.a >= 0.995) {
      return `#${toHex(rgba.r)}${toHex(rgba.g)}${toHex(rgba.b)}`
    }
    const a = Math.round(rgba.a * 1000) / 1000
    return `rgba(${rgba.r}, ${rgba.g}, ${rgba.b}, ${a})`
  }

  if (/^#[0-9a-f]{8}$/i.test(trimmed)) {
    return formatOutgoingColor(hex8ToRgba(trimmed))
  }
  if (/^#[0-9a-f]{3,6}$/i.test(trimmed)) return trimmed.toLowerCase()
  return trimmed
}

function parseRgba(
  value: string,
): { r: number; g: number; b: number; a: number } | null {
  const m = value
    .trim()
    .match(
      /^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})(?:\s*,\s*([0-9.]+))?\s*\)$/i,
    )
  if (!m) return null
  return {
    r: clampByte(Number(m[1])),
    g: clampByte(Number(m[2])),
    b: clampByte(Number(m[3])),
    a: m[4] == null ? 1 : Math.min(1, Math.max(0, Number(m[4]))),
  }
}

function clampByte(n: number): number {
  if (!Number.isFinite(n)) return 0
  return Math.min(255, Math.max(0, Math.round(n)))
}

function toHex(n: number): string {
  return n.toString(16).padStart(2, '0')
}

function commit(value: string) {
  const next = normalizeColor(value)
  localValue.value = next
  emit('update:modelValue', next)
  emit('change', next)
}

function handleTextChange() {
  commit(localValue.value)
}

function applyPreset(value: string) {
  commit(value)
}

function applyPalette(color: PaletteColor) {
  commit(color.name)
}

function handleEyedropper() {
  void colorPickState.startPick((color) => {
    commit(color)
  })
}

function isPresetActive(value: string): boolean {
  const cur = localValue.value.trim().toLowerCase()
  if (value === 'transparent') return !cur || cur === 'transparent'
  return cur === value.toLowerCase()
}

function isPaletteActive(name: string): boolean {
  return localValue.value.trim() === name
}

function paletteTitle(color: PaletteColor): string {
  const desc = color.description?.trim()
  return desc ? `${color.name} · ${desc}` : color.name
}

/** 预览方块背景：调色板 key 用实际色值 */
const swatchCss = computed(() => {
  if (activePaletteColor.value) {
    const v = activePaletteColor.value.value.trim()
    if (!v || v === 'transparent') return undefined
    return v
  }
  const cur = localValue.value.trim()
  if (!cur || cur === 'transparent' || isBinding.value) return undefined
  return toPickerColor(cur)
})

const isTransparentSwatch = computed(() => {
  if (activePaletteColor.value) {
    const v = activePaletteColor.value.value.trim()
    return !v || v === 'transparent'
  }
  const cur = localValue.value.trim()
  return !cur || cur === 'transparent'
})

const displayLabel = computed(() => {
  const cur = localValue.value.trim()
  if (!cur) return props.placeholder || '选择颜色'
  return cur
})
</script>

<template>
  <el-popover
    v-if="compact"
    v-model:visible="popoverVisible"
    placement="bottom-start"
    :width="320"
    trigger="click"
    :disabled="isBinding"
    popper-class="color-picker-compact-popper"
  >
    <template #reference>
      <button
        type="button"
        class="color-compact-trigger"
        :title="displayLabel"
      >
        <span
          class="compact-swatch"
          :class="{ checker: isTransparentSwatch }"
          :style="swatchCss ? { background: swatchCss } : undefined"
        />
        <span class="compact-label">{{ displayLabel }}</span>
      </button>
    </template>
    <div class="color-picker">
      <div class="color-picker-row">
        <el-color-picker
          v-model="pickerModel"
          class="ep-picker"
          size="small"
          show-alpha
          :predefine="PREDEFINE"
          :disabled="isBinding || isPaletteKey"
        />
        <el-input
          v-model="localValue"
          class="hex-input"
          size="small"
          :placeholder="placeholder || '#ffffff / transparent / rgba() / key'"
          clearable
          @change="handleTextChange"
        />
        <el-tooltip content="吸管取色" placement="top">
          <el-button
            class="eyedropper-btn"
            size="small"
            :icon="Aim"
            :disabled="isBinding"
            @click="handleEyedropper"
          />
        </el-tooltip>
      </div>
      <div
        v-if="paletteColors.length"
        class="preset-row"
        role="list"
        aria-label="调色板"
      >
        <button
          v-for="item in paletteColors"
          :key="item.name"
          type="button"
          class="preset-chip palette-chip"
          :class="{ active: isPaletteActive(item.name) }"
          :title="paletteTitle(item)"
          role="listitem"
          @click="applyPalette(item)"
        >
          <span
            class="preset-swatch"
            :class="{ checker: item.value === 'transparent' }"
            :style="
              item.value === 'transparent'
                ? undefined
                : { background: item.value }
            "
          />
          <span class="preset-label">{{ item.name }}</span>
        </button>
      </div>
      <div class="preset-row" role="list" aria-label="参考颜色">
        <button
          v-for="item in PRESET_COLORS"
          :key="item.value"
          type="button"
          class="preset-chip"
          :class="{ active: isPresetActive(item.value) }"
          :title="item.label"
          role="listitem"
          @click="applyPreset(item.value)"
        >
          <span
            class="preset-swatch"
            :class="{ checker: item.value === 'transparent' }"
            :style="
              item.value === 'transparent'
                ? undefined
                : { background: item.value }
            "
          />
          <span class="preset-label">{{ item.label }}</span>
        </button>
      </div>
    </div>
  </el-popover>

  <div v-else class="color-picker">
    <div class="color-picker-row">
      <el-color-picker
        v-model="pickerModel"
        class="ep-picker"
        size="small"
        show-alpha
        :predefine="PREDEFINE"
        :disabled="isBinding || isPaletteKey"
      />

      <el-input
        v-model="localValue"
        class="hex-input"
        size="small"
        :placeholder="placeholder || '#ffffff / transparent / rgba() / key'"
        clearable
        @change="handleTextChange"
      />

      <el-tooltip content="吸管取色" placement="top">
        <el-button
          class="eyedropper-btn"
          size="small"
          :icon="Aim"
          :disabled="isBinding"
          @click="handleEyedropper"
        />
      </el-tooltip>
    </div>

    <div
      v-if="paletteColors.length"
      class="preset-row"
      role="list"
      aria-label="调色板"
    >
      <button
        v-for="item in paletteColors"
        :key="item.name"
        type="button"
        class="preset-chip palette-chip"
        :class="{ active: isPaletteActive(item.name) }"
        :title="paletteTitle(item)"
        role="listitem"
        @click="applyPalette(item)"
      >
        <span
          class="preset-swatch"
          :class="{ checker: item.value === 'transparent' }"
          :style="
            item.value === 'transparent' ? undefined : { background: item.value }
          "
        />
        <span class="preset-label">{{ item.name }}</span>
      </button>
    </div>

    <div class="preset-row" role="list" aria-label="参考颜色">
      <button
        v-for="item in PRESET_COLORS"
        :key="item.value"
        type="button"
        class="preset-chip"
        :class="{ active: isPresetActive(item.value) }"
        :title="item.label"
        role="listitem"
        @click="applyPreset(item.value)"
      >
        <span
          class="preset-swatch"
          :class="{ checker: item.value === 'transparent' }"
          :style="
            item.value === 'transparent' ? undefined : { background: item.value }
          "
        />
        <span class="preset-label">{{ item.label }}</span>
      </button>
    </div>
  </div>
</template>

<style scoped>
.color-compact-trigger {
  display: flex;
  align-items: center;
  gap: 6px;
  width: 100%;
  min-width: 0;
  height: 24px;
  min-height: 24px;
  padding: 0 8px;
  margin: 0;
  border: 1px solid var(--el-border-color);
  border-radius: var(--el-border-radius-base);
  background: var(--el-fill-color-blank);
  color: var(--el-text-color-primary);
  font-size: 12px;
  line-height: 1;
  text-align: left;
  cursor: pointer;
  box-sizing: border-box;
}

.color-compact-trigger:hover {
  border-color: var(--el-border-color-hover);
}

.compact-swatch {
  flex-shrink: 0;
  width: 14px;
  height: 14px;
  border-radius: 3px;
  border: 1px solid rgba(0, 0, 0, 0.12);
  box-sizing: border-box;
}

.compact-swatch.checker {
  background-color: #fff;
  background-image:
    linear-gradient(45deg, #ccc 25%, transparent 25%),
    linear-gradient(-45deg, #ccc 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, #ccc 75%),
    linear-gradient(-45deg, transparent 75%, #ccc 75%);
  background-size: 8px 8px;
  background-position:
    0 0,
    0 4px,
    4px -4px,
    -4px 0;
}

.compact-label {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.color-picker {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}

.color-picker-row {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  min-height: 24px;
}

.ep-picker {
  flex-shrink: 0;
  height: 24px;
}

.ep-picker :deep(.el-color-picker__trigger) {
  width: 24px;
  height: 24px;
  padding: 2px;
  border-radius: 4px;
}

.hex-input {
  flex: 1;
  min-width: 0;
}

.hex-input :deep(.el-input__wrapper) {
  min-height: 24px;
}

.eyedropper-btn {
  flex-shrink: 0;
  width: 24px;
  height: 24px;
  padding: 0;
}

.preset-row {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.preset-chip {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  height: 24px;
  padding: 0 8px 0 4px;
  border: 1px solid #dcdfe6;
  border-radius: 4px;
  background: #fff;
  color: #606266;
  font-size: 12px;
  line-height: 1;
  cursor: pointer;
  user-select: none;
  max-width: 100%;
}

.preset-chip:hover {
  border-color: #c0c4cc;
  color: #303133;
}

.preset-chip.active {
  border-color: #409eff;
  color: #409eff;
  background: #ecf5ff;
}

.preset-swatch {
  width: 14px;
  height: 14px;
  border-radius: 3px;
  border: 1px solid rgba(0, 0, 0, 0.12);
  box-sizing: border-box;
  flex-shrink: 0;
}

.preset-swatch.checker {
  background-color: #fff;
  background-image:
    linear-gradient(45deg, #ccc 25%, transparent 25%),
    linear-gradient(-45deg, #ccc 25%, transparent 25%),
    linear-gradient(45deg, transparent 75%, #ccc 75%),
    linear-gradient(-45deg, transparent 75%, #ccc 75%);
  background-size: 6px 6px;
  background-position:
    0 0,
    0 3px,
    3px -3px,
    -3px 0;
}

.preset-label {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
</style>

// frontend/src/components/editor/ColorPicker.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button, ColorPicker as AntColorPicker, Input, Popover, Tooltip } from 'antd'
import { AimOutlined } from '@ant-design/icons'
import { colorPickState } from '../../composables/useColorPick'
import { useColorPaletteState } from '../../composables/useColorPalette'
import {
  findPaletteColor,
  type PaletteColor,
} from '../../types/color-palette'
import './ColorPicker.css'

const PRESET_COLORS = [
  { label: '透明', value: 'transparent' },
  { label: '白', value: '#ffffff' },
  { label: '黑', value: '#000000' },
] as const

const PREDEFINE = [
  'transparent',
  '#ffffff',
  '#000000',
  '#409eff',
  '#67c23a',
  '#e6a23c',
  '#f56c6c',
]

function normalizeColor(value: unknown): string {
  return String(value ?? '').trim()
}

function toPickerColor(value: string): string {
  const trimmed = value.trim()
  if (!trimmed || trimmed === 'transparent' || /\{[^{}]+\}/.test(trimmed)) {
    return 'rgba(255, 255, 255, 0)'
  }
  if (/^rgba?\(/i.test(trimmed) || /^hsla?\(/i.test(trimmed)) return trimmed
  if (/^#[0-9a-f]{8}$/i.test(trimmed)) return hex8ToRgba(trimmed)
  if (/^#[0-9a-f]{6}$/i.test(trimmed)) return trimmed
  if (/^#[0-9a-f]{3}$/i.test(trimmed)) {
    const [, r, g, b] = trimmed
    return `#${r}${r}${g}${g}${b}${b}`
  }
  return '#ffffff'
}

function hex8ToRgba(hex: string): string {
  const h = hex.slice(1)
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  const a = parseInt(h.slice(6, 8), 16) / 255
  const alpha = Math.round(a * 1000) / 1000
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

function formatOutgoingColor(value: string): string {
  const trimmed = value.trim()
  if (!trimmed) return 'transparent'

  const rgba = parseRgba(trimmed)
  if (rgba) {
    if (rgba.a <= 0.005) return 'transparent'
    if (rgba.a >= 0.995) {
      return `#${toHex(rgba.r)}${toHex(rgba.g)}${toHex(rgba.b)}`
    }
    const a = Math.round(rgba.a * 1000) / 1000
    return `rgba(${rgba.r}, ${rgba.g}, ${rgba.b}, ${a})`
  }

  if (/^#[0-9a-f]{8}$/i.test(trimmed)) {
    return formatOutgoingColor(hex8ToRgba(trimmed))
  }
  if (/^#[0-9a-f]{3,6}$/i.test(trimmed)) return trimmed.toLowerCase()
  return trimmed
}

function parseRgba(
  value: string,
): { r: number; g: number; b: number; a: number } | null {
  const m = value
    .trim()
    .match(
      /^rgba?\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})(?:\s*,\s*([0-9.]+))?\s*\)$/i,
    )
  if (!m) return null
  return {
    r: clampByte(Number(m[1])),
    g: clampByte(Number(m[2])),
    b: clampByte(Number(m[3])),
    a: m[4] == null ? 1 : Math.min(1, Math.max(0, Number(m[4]))),
  }
}

function clampByte(n: number): number {
  if (!Number.isFinite(n)) return 0
  return Math.min(255, Math.max(0, Math.round(n)))
}

function toHex(n: number): string {
  return n.toString(16).padStart(2, '0')
}

export default function ColorPicker({
  value,
  onChange,
  placeholder,
  hidePalette = false,
  compact = false,
}: {
  value: string
  onChange?: (value: string) => void
  placeholder?: string
  hidePalette?: boolean
  compact?: boolean
}) {
  const colorPalette = useColorPaletteState()
  const [popoverVisible, setPopoverVisible] = useState(false)
  const [localValue, setLocalValue] = useState(() => normalizeColor(value))

  useEffect(() => {
    setLocalValue(normalizeColor(value))
  }, [value])

  const paletteColors = hidePalette ? [] : colorPalette.colors

  const isBinding = /\{[^{}]+\}/.test(localValue.trim())

  const activePaletteColor = findPaletteColor(
    { colors: paletteColors },
    localValue.trim(),
  )

  const isPaletteKey = Boolean(activePaletteColor)

  const pickerModel = useMemo(() => {
    if (activePaletteColor) {
      return toPickerColor(activePaletteColor.value)
    }
    return toPickerColor(localValue)
  }, [activePaletteColor, localValue])

  function commit(nextValue: string) {
    const next = normalizeColor(nextValue)
    setLocalValue(next)
    onChange?.(next)
  }

  function handleTextChange() {
    commit(localValue)
  }

  function applyPreset(presetValue: string) {
    commit(presetValue)
  }

  function applyPalette(color: PaletteColor) {
    commit(color.name)
  }

  function handleEyedropper() {
    void colorPickState.startPick((color) => {
      commit(color)
    })
  }

  function isPresetActive(presetValue: string): boolean {
    const cur = localValue.trim().toLowerCase()
    if (presetValue === 'transparent') return !cur || cur === 'transparent'
    return cur === presetValue.toLowerCase()
  }

  function isPaletteActive(name: string): boolean {
    return localValue.trim() === name
  }

  function paletteTitle(color: PaletteColor): string {
    const desc = color.description?.trim()
    return desc ? `${color.name} · ${desc}` : color.name
  }

  const swatchCss = (() => {
    if (activePaletteColor) {
      const v = activePaletteColor.value.trim()
      if (!v || v === 'transparent') return undefined
      return v
    }
    const cur = localValue.trim()
    if (!cur || cur === 'transparent' || isBinding) return undefined
    return toPickerColor(cur)
  })()

  const isTransparentSwatch = (() => {
    if (activePaletteColor) {
      const v = activePaletteColor.value.trim()
      return !v || v === 'transparent'
    }
    const cur = localValue.trim()
    return !cur || cur === 'transparent'
  })()

  const displayLabel = (() => {
    const cur = localValue.trim()
    if (!cur) return placeholder || '选择颜色'
    return cur
  })()

  const pickerBody = (
    <div className="color-picker">
      <div className="color-picker-row">
        <AntColorPicker
          className="ep-picker"
          size="small"
          disabled={isBinding || isPaletteKey}
          value={pickerModel}
          presets={[{ label: '预置', colors: [...PREDEFINE] }]}
          onChange={(color) => {
            const next = color.toRgbString()
            if (!next) {
              commit('transparent')
              return
            }
            commit(formatOutgoingColor(next))
          }}
        />
        <Input
          className="hex-input"
          size="small"
          value={localValue}
          allowClear
          placeholder={placeholder || '#ffffff / transparent / rgba() / key'}
          onChange={(e) => setLocalValue(e.target.value)}
          onBlur={handleTextChange}
          onPressEnter={handleTextChange}
        />
        <Tooltip title="吸管取色" placement="top">
          <Button
            className="eyedropper-btn"
            size="small"
            icon={<AimOutlined />}
            disabled={isBinding}
            onClick={handleEyedropper}
          />
        </Tooltip>
      </div>
      {paletteColors.length > 0 && (
        <div className="preset-row" role="list" aria-label="调色板">
          {paletteColors.map((item) => (
            <button
              key={item.name}
              type="button"
              className={`preset-chip palette-chip${isPaletteActive(item.name) ? ' active' : ''}`}
              title={paletteTitle(item)}
              role="listitem"
              onClick={() => applyPalette(item)}
            >
              <span
                className={`preset-swatch${item.value === 'transparent' ? ' checker' : ''}`}
                style={
                  item.value === 'transparent'
                    ? undefined
                    : { background: item.value }
                }
              />
              <span className="preset-label">{item.name}</span>
            </button>
          ))}
        </div>
      )}
      <div className="preset-row" role="list" aria-label="参考颜色">
        {PRESET_COLORS.map((item) => (
          <button
            key={item.value}
            type="button"
            className={`preset-chip${isPresetActive(item.value) ? ' active' : ''}`}
            title={item.label}
            role="listitem"
            onClick={() => applyPreset(item.value)}
          >
            <span
              className={`preset-swatch${item.value === 'transparent' ? ' checker' : ''}`}
              style={
                item.value === 'transparent'
                  ? undefined
                  : { background: item.value }
              }
            />
            <span className="preset-label">{item.label}</span>
          </button>
        ))}
      </div>
    </div>
  )

  if (compact) {
    return (
      <Popover
        open={isBinding ? false : popoverVisible}
        onOpenChange={(next) => {
          if (isBinding) return
          setPopoverVisible(next)
        }}
        placement="bottomLeft"
        trigger="click"
        overlayClassName="color-picker-compact-popper"
        overlayInnerStyle={{ width: 320 }}
        content={pickerBody}
      >
        <button type="button" className="color-compact-trigger" title={displayLabel}>
          <span
            className={`compact-swatch${isTransparentSwatch ? ' checker' : ''}`}
            style={swatchCss ? { background: swatchCss } : undefined}
          />
          <span className="compact-label">{displayLabel}</span>
        </button>
      </Popover>
    )
  }

  return pickerBody
}
