// frontend/src/components/editor/ComponentMetaPanel.vue
<script setup lang="ts">
import { reactive, ref, watch } from 'vue'
import { Delete, Plus } from '@element-plus/icons-vue'
import {
  dataFieldToMethodParamType,
  methodParamToDataFieldType,
  type MethodParam,
  type PageMethod,
} from '../../types/page-method'
import {
  createEmptyComponentEvent,
  createEmptyComponentProp,
  type ComponentConfig,
  type ComponentEventDef,
  type ComponentPropDef,
} from '../../types/component'
import { SIZE_OPTIONS } from '../../utils/xml-node'
import NumericInput from './NumericInput.vue'
import ComponentPropDialog from './ComponentPropDialog.vue'
import DataFieldTypeTreeSelect, { type TypeSelectPayload } from './DataFieldTypeTreeSelect.vue'
import type { DataTypeLibrary } from '../../types/data-types'
import { DATA_FIELD_TYPE_OPTIONS } from '../../types/page-data'

const props = defineProps<{
  config: ComponentConfig
  methods: PageMethod[]
  iconOptions?: Array<{ id: string; label: string }>
  typeLibrary?: DataTypeLibrary | null
}>()

const emit = defineEmits<{
  'update:config': [config: ComponentConfig]
}>()

const draft = reactive<ComponentConfig>({
  name: '',
  title: '',
  width: 'match_parent',
  height: 'wrap_content',
  props: [],
  events: [],
  exposedMethods: [],
  debugProps: {},
})

const widthMode = reactive({ mode: 'match_parent', value: 200 })
const heightMode = reactive({ mode: 'wrap_content', value: 80 })

const propDialogVisible = ref(false)
const editingPropIndex = ref(-1)
const editingProp = ref<ComponentPropDef | null>(null)

watch(
  () => props.config,
  (config) => {
    draft.name = config.name
    draft.title = config.title || config.name
    draft.width = config.width
    draft.height = config.height
    draft.props = config.props.map((item) => ({
      ...item,
      required: Boolean(item.required),
    }))
    draft.events = config.events.map((item) => ({
      ...item,
      params: item.params.map((p) => ({ ...p })),
    }))
    draft.exposedMethods = [...config.exposedMethods]
    draft.debugProps = { ...(config.debugProps ?? {}) }
    Object.assign(widthMode, parseSize(config.width, 200))
    Object.assign(heightMode, parseSize(config.height, 80))
  },
  { immediate: true, deep: true },
)

function parseSize(value: string | undefined, fallback: number) {
  if (!value || value === 'wrap_content') return { mode: 'wrap_content', value: fallback }
  if (value === 'match_parent') return { mode: 'match_parent', value: fallback }
  const n = Number(value)
  if (Number.isFinite(n) && n > 0) return { mode: 'fixed', value: n }
  if (Number.isFinite(n)) return { mode: 'fixed', value: fallback }
  return { mode: 'wrap_content', value: fallback }
}

function sizeToAttr(mode: string, value: number | string, fallback = 0) {
  if (mode === 'wrap_content' || mode === 'match_parent') return mode
  const num = Number(value)
  if (!Number.isFinite(num) || num < 0) return String(fallback)
  return String(num)
}

function onWidthModeChange() {
  if (widthMode.mode === 'fixed') {
    const n = Number(widthMode.value)
    if (!Number.isFinite(n) || n <= 0) widthMode.value = 200
  }
  commit()
}

function onHeightModeChange() {
  if (heightMode.mode === 'fixed') {
    const n = Number(heightMode.value)
    if (!Number.isFinite(n) || n <= 0) heightMode.value = 80
  }
  commit()
}

function commit() {
  draft.width = sizeToAttr(widthMode.mode, widthMode.value, 200)
  draft.height = sizeToAttr(heightMode.mode, heightMode.value, 80)
  emit('update:config', {
    name: draft.name.trim(),
    title: (draft.title || draft.name).trim(),
    width: draft.width,
    height: draft.height,
    props: draft.props.map((item) => ({
      ...item,
      name: item.name.trim(),
      required: Boolean(item.required),
    })),
    events: draft.events.map((item) => ({
      name: item.name.trim(),
      params: item.params.map((p) => ({
        ...p,
        name: p.name.trim(),
      })),
    })),
    exposedMethods: [...draft.exposedMethods],
    debugProps: { ...(draft.debugProps ?? props.config.debugProps ?? {}) },
  })
}

function openAddProp() {
  editingPropIndex.value = -1
  editingProp.value = createEmptyComponentProp()
  propDialogVisible.value = true
}

function openEditProp(index: number) {
  editingPropIndex.value = index
  editingProp.value = { ...draft.props[index] }
  propDialogVisible.value = true
}

function removeProp(index: number) {
  draft.props.splice(index, 1)
  commit()
}

function saveProp(prop: ComponentPropDef) {
  if (editingPropIndex.value >= 0) {
    draft.props[editingPropIndex.value] = { ...prop }
  } else {
    draft.props.push({ ...prop })
  }
  commit()
}

function propExistingNames(): string[] {
  return draft.props
    .map((item, index) => (index === editingPropIndex.value ? '' : item.name))
    .filter(Boolean)
}

function propTypeLabel(type: string): string {
  return DATA_FIELD_TYPE_OPTIONS.find((item) => item.value === type)?.label ?? type
}

function propSummary(row: ComponentPropDef): string {
  const parts = [propTypeLabel(row.type)]
  if (row.required) parts.push('必填')
  if (row.type === 'api') {
    const n = row.apiParams?.length ?? 0
    parts.push(n ? `${n} 个形参` : '无形参')
    if (row.apiReturnType?.typeRef || (row.apiReturnType?.type && row.apiReturnType.type !== 'any')) {
      parts.push('有出参')
    }
    parts.push('props')
  } else if (row.twoWay) {
    parts.push('可更新')
  } else {
    parts.push('props')
  }
  return parts.join(' · ')
}

function addEvent() {
  draft.events.push(createEmptyComponentEvent())
  commit()
}

function removeEvent(index: number) {
  draft.events.splice(index, 1)
  commit()
}

function addEventParam(event: ComponentEventDef) {
  event.params.push({ name: '', type: 'any' })
  commit()
}

function removeEventParam(event: ComponentEventDef, index: number) {
  event.params.splice(index, 1)
  commit()
}

function onEventParamTypeChange(param: MethodParam, payload: TypeSelectPayload) {
  const fieldType =
    payload.type === 'void' || payload.type === 'generic' ? 'any' : payload.type
  param.type = dataFieldToMethodParamType(fieldType)
  param.typeRef = payload.typeRef
  param.itemType =
    fieldType === 'array'
      ? payload.itemType === 'generic'
        ? 'any'
        : payload.itemType || 'string'
      : undefined
  param.itemTypeRef = fieldType === 'array' ? payload.itemTypeRef : undefined
  param.itemItemType =
    fieldType === 'array' && payload.itemType === 'array'
      ? payload.itemItemType === 'generic'
        ? 'any'
        : payload.itemItemType || 'string'
      : undefined
  param.itemItemTypeRef =
    fieldType === 'array' && payload.itemType === 'array'
      ? payload.itemItemTypeRef
      : undefined
  commit()
}

const customMethodOptions = () =>
  props.methods.filter((item) => !item.builtin).map((item) => item.name)
</script>

<template>
  <div class="component-meta">
    <div class="panel-header">组件设置</div>
    <div class="panel-body">
      <div class="section-title">基本</div>
      <el-form label-position="top" size="small">
        <el-form-item label="名称">
          <el-input v-model="draft.name" @change="commit" />
        </el-form-item>
        <el-form-item label="标题">
          <el-input v-model="draft.title" @change="commit" />
        </el-form-item>
      </el-form>

      <div class="section-title">默认尺寸</div>
      <el-form label-position="top" size="small">
        <el-form-item label="宽度 width">
          <div class="size-row">
            <el-select v-model="widthMode.mode" @change="onWidthModeChange">
              <el-option
                v-for="opt in SIZE_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
            <NumericInput
              v-if="widthMode.mode === 'fixed'"
              v-model="widthMode.value"
              @change="commit"
            />
          </div>
        </el-form-item>
        <el-form-item label="高度 height">
          <div class="size-row">
            <el-select v-model="heightMode.mode" @change="onHeightModeChange">
              <el-option
                v-for="opt in SIZE_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
            <NumericInput
              v-if="heightMode.mode === 'fixed'"
              v-model="heightMode.value"
              @change="commit"
            />
          </div>
        </el-form-item>
      </el-form>

      <div class="section-title">
        <span>参数（Props / Model）</span>
        <el-button type="primary" link :icon="Plus" @click="openAddProp">添加</el-button>
      </div>
      <p class="hint">点击条目编辑。模板中用 <code>{$props.字段名}</code> 读取。</p>
      <div v-if="!draft.props.length" class="empty">暂无参数</div>
      <div
        v-for="(row, index) in draft.props"
        :key="`${row.name}-${index}`"
        class="prop-item"
      >
        <button type="button" class="prop-main" @click="openEditProp(index)">
          <span class="prop-name">{{ row.name || '未命名' }}</span>
          <span class="prop-meta">{{ propSummary(row) }}</span>
        </button>
        <el-button type="danger" link :icon="Delete" @click="removeProp(index)" />
      </div>

      <div class="section-title">
        <span>事件方法</span>
        <el-button type="primary" link :icon="Plus" @click="addEvent">添加</el-button>
      </div>
      <p class="hint">组件对外抛出的事件，父页面可绑定。</p>
      <div v-if="!draft.events.length" class="empty">暂无事件</div>
      <div v-for="(event, eIndex) in draft.events" :key="eIndex" class="card">
        <div class="card-row">
          <el-input
            v-model="event.name"
            placeholder="事件名，如 onChange"
            @change="commit"
          />
          <el-button type="danger" link :icon="Delete" @click="removeEvent(eIndex)" />
        </div>
        <div class="params">
          <div
            v-for="(param, pIndex) in event.params"
            :key="pIndex"
            class="param-row"
          >
            <el-input
              v-model="param.name"
              placeholder="参数名"
              @change="commit"
            />
            <DataFieldTypeTreeSelect
              :type="methodParamToDataFieldType(param.type)"
              :type-ref="param.typeRef"
              :item-type="param.itemType"
              :item-type-ref="param.itemTypeRef"
              :item-item-type="param.itemItemType"
              :item-item-type-ref="param.itemItemTypeRef"
              :library="typeLibrary"
              composable
              size="small"
              @change="onEventParamTypeChange(param, $event)"
            />
            <el-button
              type="danger"
              link
              :icon="Delete"
              @click="removeEventParam(event, pIndex)"
            />
          </div>
          <el-button type="primary" link :icon="Plus" @click="addEventParam(event)">
            添加参数
          </el-button>
        </div>
      </div>

      <div class="section-title">暴露方法</div>
      <p class="hint">从组件方法中多选，供父页面调用。</p>
      <el-select
        v-model="draft.exposedMethods"
        multiple
        filterable
        clearable
        placeholder="选择要暴露的方法"
        style="width: 100%"
        @change="commit"
      >
        <el-option
          v-for="name in customMethodOptions()"
          :key="name"
          :label="name"
          :value="name"
        />
      </el-select>
      <p v-if="!customMethodOptions().length" class="hint">
        请先在「方法」模式中添加自定义方法。
      </p>
    </div>

    <ComponentPropDialog
      v-model="propDialogVisible"
      :prop="editingProp"
      :existing-names="propExistingNames()"
      :icon-options="iconOptions"
      :type-library="typeLibrary"
      @save="saveProp"
    />
  </div>
</template>

<style scoped>
.component-meta {
  width: var(--workspace-right-width, 300px);
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  background: #fff;
  border-left: 1px solid #ebeef5;
}

.panel-header {
  flex-shrink: 0;
  height: 48px;
  padding: 0 14px;
  display: flex;
  align-items: center;
  font-weight: 600;
  color: #303133;
  border-bottom: 1px solid #ebeef5;
}

.panel-body {
  flex: 1;
  min-height: 0;
  overflow: auto;
  padding: 12px;
}

.section-title {
  margin: 12px 0 8px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 13px;
  font-weight: 600;
  color: #606266;
}

.hint {
  margin: 0 0 8px;
  font-size: 12px;
  color: #94a3b8;
}

.hint code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 11px;
}

.empty {
  font-size: 12px;
  color: #c0c4cc;
  margin-bottom: 8px;
}

.prop-item {
  display: flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 6px;
  padding: 8px 10px;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background: #fafbfc;
}

.prop-main {
  flex: 1;
  min-width: 0;
  border: none;
  background: transparent;
  text-align: left;
  cursor: pointer;
  padding: 0;
}

.prop-name {
  display: block;
  font-size: 13px;
  font-weight: 600;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.prop-meta {
  display: block;
  margin-top: 2px;
  font-size: 12px;
  color: #94a3b8;
}

.card {
  padding: 10px;
  margin-bottom: 8px;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background: #fafbfc;
}

.card-row {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
}

.card-row:last-child {
  margin-bottom: 0;
}

.params {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.param-row {
  display: grid;
  grid-template-columns: minmax(72px, 1fr) minmax(140px, 1.4fr) 28px;
  gap: 6px;
  align-items: center;
}

.size-row {
  display: flex;
  flex-direction: column;
  gap: 8px;
  width: 100%;
}

:deep(.el-select) {
  width: 100%;
}
</style>

// frontend/src/components/editor/ComponentMetaPanel.tsx
import { useEffect, useState } from 'react'
import { Button, Form, Input, Select } from 'antd'
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import {
  dataFieldToMethodParamType,
  methodParamToDataFieldType,
  type MethodParam,
  type PageMethod,
} from '../../types/page-method'
import {
  createEmptyComponentEvent,
  createEmptyComponentProp,
  type ComponentConfig,
  type ComponentPropDef,
} from '../../types/component'
import { SIZE_OPTIONS } from '../../utils/xml-node'
import NumericInput from './NumericInput'
import ComponentPropDialog from './ComponentPropDialog'
import DataFieldTypeTreeSelect, {
  type TypeSelectPayload,
} from './DataFieldTypeTreeSelect'
import type { DataTypeLibrary } from '../../types/data-types'
import { DATA_FIELD_TYPE_OPTIONS } from '../../types/page-data'
import './ComponentMetaPanel.css'

function parseSize(value: string | undefined, fallback: number) {
  if (!value || value === 'wrap_content') return { mode: 'wrap_content', value: fallback }
  if (value === 'match_parent') return { mode: 'match_parent', value: fallback }
  const n = Number(value)
  if (Number.isFinite(n) && n > 0) return { mode: 'fixed', value: n }
  if (Number.isFinite(n)) return { mode: 'fixed', value: fallback }
  return { mode: 'wrap_content', value: fallback }
}

function sizeToAttr(mode: string, value: number | string, fallback = 0) {
  if (mode === 'wrap_content' || mode === 'match_parent') return mode
  const num = Number(value)
  if (!Number.isFinite(num) || num < 0) return String(fallback)
  return String(num)
}

function cloneConfig(config: ComponentConfig): ComponentConfig {
  return {
    name: config.name,
    title: config.title || config.name,
    width: config.width,
    height: config.height,
    props: config.props.map((item) => ({
      ...item,
      required: Boolean(item.required),
    })),
    events: config.events.map((item) => ({
      ...item,
      params: item.params.map((p) => ({ ...p })),
    })),
    exposedMethods: [...config.exposedMethods],
    debugProps: { ...(config.debugProps ?? {}) },
  }
}

export default function ComponentMetaPanel({
  config,
  methods,
  iconOptions,
  typeLibrary,
  onConfigChange,
}: {
  config: ComponentConfig
  methods: PageMethod[]
  iconOptions?: Array<{ id: string; label: string }>
  typeLibrary?: DataTypeLibrary | null
  onConfigChange?: (config: ComponentConfig) => void
}) {
  const [draft, setDraft] = useState<ComponentConfig>(() => cloneConfig(config))
  const [widthMode, setWidthMode] = useState(() => parseSize(config.width, 200))
  const [heightMode, setHeightMode] = useState(() => parseSize(config.height, 80))
  const [propDialogVisible, setPropDialogVisible] = useState(false)
  const [editingPropIndex, setEditingPropIndex] = useState(-1)
  const [editingProp, setEditingProp] = useState<ComponentPropDef | null>(null)

  useEffect(() => {
    setDraft(cloneConfig(config))
    setWidthMode(parseSize(config.width, 200))
    setHeightMode(parseSize(config.height, 80))
  }, [config])

  function commit(
    nextDraft = draft,
    nextWidth = widthMode,
    nextHeight = heightMode,
  ) {
    const width = sizeToAttr(nextWidth.mode, nextWidth.value, 200)
    const height = sizeToAttr(nextHeight.mode, nextHeight.value, 80)
    onConfigChange?.({
      name: nextDraft.name.trim(),
      title: (nextDraft.title || nextDraft.name).trim(),
      width,
      height,
      props: nextDraft.props.map((item) => ({
        ...item,
        name: item.name.trim(),
        required: Boolean(item.required),
      })),
      events: nextDraft.events.map((item) => ({
        name: item.name.trim(),
        params: item.params.map((p) => ({
          ...p,
          name: p.name.trim(),
        })),
      })),
      exposedMethods: [...nextDraft.exposedMethods],
      debugProps: { ...(nextDraft.debugProps ?? config.debugProps ?? {}) },
    })
  }

  function onWidthModeChange(mode: string) {
    let next = { ...widthMode, mode }
    if (mode === 'fixed') {
      const n = Number(next.value)
      if (!Number.isFinite(n) || n <= 0) next = { ...next, value: 200 }
    }
    setWidthMode(next)
    commit(draft, next, heightMode)
  }

  function onHeightModeChange(mode: string) {
    let next = { ...heightMode, mode }
    if (mode === 'fixed') {
      const n = Number(next.value)
      if (!Number.isFinite(n) || n <= 0) next = { ...next, value: 80 }
    }
    setHeightMode(next)
    commit(draft, widthMode, next)
  }

  function openAddProp() {
    setEditingPropIndex(-1)
    setEditingProp(createEmptyComponentProp())
    setPropDialogVisible(true)
  }

  function openEditProp(index: number) {
    setEditingPropIndex(index)
    setEditingProp({ ...draft.props[index] })
    setPropDialogVisible(true)
  }

  function removeProp(index: number) {
    const next = {
      ...draft,
      props: draft.props.filter((_, i) => i !== index),
    }
    setDraft(next)
    commit(next)
  }

  function saveProp(prop: ComponentPropDef) {
    const nextProps = [...draft.props]
    if (editingPropIndex >= 0) {
      nextProps[editingPropIndex] = { ...prop }
    } else {
      nextProps.push({ ...prop })
    }
    const next = { ...draft, props: nextProps }
    setDraft(next)
    commit(next)
  }

  function propExistingNames(): string[] {
    return draft.props
      .map((item, index) => (index === editingPropIndex ? '' : item.name))
      .filter(Boolean)
  }

  function propTypeLabel(type: string): string {
    return DATA_FIELD_TYPE_OPTIONS.find((item) => item.value === type)?.label ?? type
  }

  function propSummary(row: ComponentPropDef): string {
    const parts = [propTypeLabel(row.type)]
    if (row.required) parts.push('必填')
    if (row.type === 'api') {
      const n = row.apiParams?.length ?? 0
      parts.push(n ? `${n} 个形参` : '无形参')
      if (
        row.apiReturnType?.typeRef ||
        (row.apiReturnType?.type && row.apiReturnType.type !== 'any')
      ) {
        parts.push('有出参')
      }
      parts.push('props')
    } else if (row.twoWay) {
      parts.push('可更新')
    } else {
      parts.push('props')
    }
    return parts.join(' · ')
  }

  function addEvent() {
    const next = {
      ...draft,
      events: [...draft.events, createEmptyComponentEvent()],
    }
    setDraft(next)
    commit(next)
  }

  function removeEvent(index: number) {
    const next = {
      ...draft,
      events: draft.events.filter((_, i) => i !== index),
    }
    setDraft(next)
    commit(next)
  }

  function addEventParam(eIndex: number) {
    const next = {
      ...draft,
      events: draft.events.map((event, i) =>
        i === eIndex
          ? { ...event, params: [...event.params, { name: '', type: 'any' as const }] }
          : event,
      ),
    }
    setDraft(next)
    commit(next)
  }

  function removeEventParam(eIndex: number, pIndex: number) {
    const next = {
      ...draft,
      events: draft.events.map((event, i) =>
        i === eIndex
          ? { ...event, params: event.params.filter((_, j) => j !== pIndex) }
          : event,
      ),
    }
    setDraft(next)
    commit(next)
  }

  function onEventParamTypeChange(
    eIndex: number,
    pIndex: number,
    payload: TypeSelectPayload,
  ) {
    const fieldType =
      payload.type === 'void' || payload.type === 'generic' ? 'any' : payload.type
    const next = {
      ...draft,
      events: draft.events.map((event, i) => {
        if (i !== eIndex) return event
        return {
          ...event,
          params: event.params.map((param, j) => {
            if (j !== pIndex) return param
            const nextParam: MethodParam = {
              ...param,
              type: dataFieldToMethodParamType(fieldType),
              typeRef: payload.typeRef,
              itemType:
                fieldType === 'array'
                  ? payload.itemType === 'generic'
                    ? 'any'
                    : payload.itemType || 'string'
                  : undefined,
              itemTypeRef: fieldType === 'array' ? payload.itemTypeRef : undefined,
              itemItemType:
                fieldType === 'array' && payload.itemType === 'array'
                  ? payload.itemItemType === 'generic'
                    ? 'any'
                    : payload.itemItemType || 'string'
                  : undefined,
              itemItemTypeRef:
                fieldType === 'array' && payload.itemType === 'array'
                  ? payload.itemItemTypeRef
                  : undefined,
            }
            return nextParam
          }),
        }
      }),
    }
    setDraft(next)
    commit(next)
  }

  const customMethodOptions = methods
    .filter((item) => !item.builtin)
    .map((item) => item.name)

  return (
    <div className="component-meta">
      <div className="panel-header">组件设置</div>
      <div className="panel-body">
        <div className="section-title">基本</div>
        <Form layout="vertical" size="small">
          <Form.Item label="名称">
            <Input
              value={draft.name}
              onChange={(e) => setDraft((prev) => ({ ...prev, name: e.target.value }))}
              onBlur={() => commit()}
            />
          </Form.Item>
          <Form.Item label="标题">
            <Input
              value={draft.title}
              onChange={(e) => setDraft((prev) => ({ ...prev, title: e.target.value }))}
              onBlur={() => commit()}
            />
          </Form.Item>
        </Form>

        <div className="section-title">默认尺寸</div>
        <Form layout="vertical" size="small">
          <Form.Item label="宽度 width">
            <div className="size-row">
              <Select
                value={widthMode.mode}
                options={[...SIZE_OPTIONS]}
                onChange={onWidthModeChange}
              />
              {widthMode.mode === 'fixed' ? (
                <NumericInput
                  value={widthMode.value}
                  onChange={(v) => {
                    const next = { ...widthMode, value: Number(v) || 0 }
                    setWidthMode(next)
                    commit(draft, next, heightMode)
                  }}
                />
              ) : null}
            </div>
          </Form.Item>
          <Form.Item label="高度 height">
            <div className="size-row">
              <Select
                value={heightMode.mode}
                options={[...SIZE_OPTIONS]}
                onChange={onHeightModeChange}
              />
              {heightMode.mode === 'fixed' ? (
                <NumericInput
                  value={heightMode.value}
                  onChange={(v) => {
                    const next = { ...heightMode, value: Number(v) || 0 }
                    setHeightMode(next)
                    commit(draft, widthMode, next)
                  }}
                />
              ) : null}
            </div>
          </Form.Item>
        </Form>

        <div className="section-title">
          <span>参数（Props / Model）</span>
          <Button type="link" icon={<PlusOutlined />} onClick={openAddProp}>
            添加
          </Button>
        </div>
        <p className="hint">
          点击条目编辑。模板中用 <code>{'{$props.字段名}'}</code> 读取。
        </p>
        {!draft.props.length ? <div className="empty">暂无参数</div> : null}
        {draft.props.map((row, index) => (
          <div key={`${row.name}-${index}`} className="prop-item">
            <button type="button" className="prop-main" onClick={() => openEditProp(index)}>
              <span className="prop-name">{row.name || '未命名'}</span>
              <span className="prop-meta">{propSummary(row)}</span>
            </button>
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
              onClick={() => removeProp(index)}
            />
          </div>
        ))}

        <div className="section-title">
          <span>事件方法</span>
          <Button type="link" icon={<PlusOutlined />} onClick={addEvent}>
            添加
          </Button>
        </div>
        <p className="hint">组件对外抛出的事件，父页面可绑定。</p>
        {!draft.events.length ? <div className="empty">暂无事件</div> : null}
        {draft.events.map((event, eIndex) => (
          <div key={eIndex} className="card">
            <div className="card-row">
              <Input
                value={event.name}
                placeholder="事件名，如 onChange"
                onChange={(e) => {
                  const next = {
                    ...draft,
                    events: draft.events.map((item, i) =>
                      i === eIndex ? { ...item, name: e.target.value } : item,
                    ),
                  }
                  setDraft(next)
                }}
                onBlur={() => commit()}
              />
              <Button
                type="link"
                danger
                icon={<DeleteOutlined />}
                onClick={() => removeEvent(eIndex)}
              />
            </div>
            <div className="params">
              {event.params.map((param, pIndex) => (
                <div key={pIndex} className="param-row">
                  <Input
                    value={param.name}
                    placeholder="参数名"
                    onChange={(e) => {
                      const next = {
                        ...draft,
                        events: draft.events.map((item, i) =>
                          i === eIndex
                            ? {
                                ...item,
                                params: item.params.map((p, j) =>
                                  j === pIndex ? { ...p, name: e.target.value } : p,
                                ),
                              }
                            : item,
                        ),
                      }
                      setDraft(next)
                    }}
                    onBlur={() => commit()}
                  />
                  <DataFieldTypeTreeSelect
                    type={methodParamToDataFieldType(param.type)}
                    typeRef={param.typeRef}
                    itemType={param.itemType}
                    itemTypeRef={param.itemTypeRef}
                    itemItemType={param.itemItemType}
                    itemItemTypeRef={param.itemItemTypeRef}
                    library={typeLibrary}
                    composable
                    size="small"
                    onChange={(payload) =>
                      onEventParamTypeChange(eIndex, pIndex, payload)
                    }
                  />
                  <Button
                    type="link"
                    danger
                    icon={<DeleteOutlined />}
                    onClick={() => removeEventParam(eIndex, pIndex)}
                  />
                </div>
              ))}
              <Button type="link" icon={<PlusOutlined />} onClick={() => addEventParam(eIndex)}>
                添加参数
              </Button>
            </div>
          </div>
        ))}

        <div className="section-title">暴露方法</div>
        <p className="hint">从组件方法中多选，供父页面调用。</p>
        <Select
          mode="multiple"
          showSearch
          allowClear
          placeholder="选择要暴露的方法"
          style={{ width: '100%' }}
          value={draft.exposedMethods}
          options={customMethodOptions.map((name) => ({ label: name, value: name }))}
          onChange={(exposedMethods) => {
            const next = { ...draft, exposedMethods }
            setDraft(next)
            commit(next)
          }}
        />
        {!customMethodOptions.length ? (
          <p className="hint">请先在「方法」模式中添加自定义方法。</p>
        ) : null}
      </div>

      <ComponentPropDialog
        open={propDialogVisible}
        onOpenChange={setPropDialogVisible}
        prop={editingProp}
        existingNames={propExistingNames()}
        iconOptions={iconOptions}
        typeLibrary={typeLibrary}
        onSave={saveProp}
      />
    </div>
  )
}
