// frontend/src/components/editor/StyleEditor.tsx
import { useEffect, useMemo, useState } from 'react'
import { Form, Select } from 'antd'
import AttrBindField from './AttrBindField'
import { GRAVITY_OPTIONS, SIZE_OPTIONS } from '../../utils/xml-node'
import { OVERFLOW_OPTIONS } from '../../utils/xml'
import type { StyleOverrides } from '../../types/dynamic-styles'
import type { DataField } from '../../types/page-data'
import type { ComponentPropDef } from '../../types/component'
import type { PageQueryParamDef } from '../../types/page-query'
import './StyleEditor.css'

type FormState = {
  widthMode: string
  widthValue: string
  heightMode: string
  heightValue: string
  margin: string
  marginLeft: string
  marginRight: string
  marginTop: string
  marginBottom: string
  padding: string
  paddingLeft: string
  paddingRight: string
  paddingTop: string
  paddingBottom: string
  background: string
  gravity: string
  borderRadius: string
  borderTopLeftRadius: string
  borderTopRightRadius: string
  borderBottomRightRadius: string
  borderBottomLeftRadius: string
  borderWidth: string
  borderColor: string
  overflow: string
  zIndex: string
  text: string
  textSize: string
  textColor: string
  value: string
  placeholder: string
  color: string
  rotateX: string
  rotateY: string
  rotateZ: string
}

function parseSizeMode(value: string | undefined, fallbackValue: number) {
  if (!value || value === 'wrap_content') {
    return { mode: 'wrap_content', value: String(fallbackValue) }
  }
  if (value === 'match_parent') {
    return { mode: 'match_parent', value: String(fallbackValue) }
  }
  return {
    mode: 'fixed',
    value: String(value).replace(/px$/i, ''),
  }
}

function sizeToAttr(mode: string, value: number | string): string {
  if (mode === 'match_parent' || mode === 'wrap_content') return mode
  const raw = String(value ?? '').trim()
  if (!raw) return '0'
  if (/\{[^{}]+\}/.test(raw)) return raw
  const num = Number(raw.replace(/px$/i, ''))
  return Number.isFinite(num) ? String(num) : raw
}

function syncFromModel(styles: StyleOverrides): FormState {
  const width = parseSizeMode(styles.width, 100)
  const height = parseSizeMode(styles.height, 40)
  return {
    widthMode: width.mode,
    widthValue: width.value,
    heightMode: height.mode,
    heightValue: height.value,
    margin: styles.margin ?? '',
    marginLeft: styles.marginLeft ?? '',
    marginRight: styles.marginRight ?? '',
    marginTop: styles.marginTop ?? '',
    marginBottom: styles.marginBottom ?? '',
    padding: styles.padding ?? '',
    paddingLeft: styles.paddingLeft ?? '',
    paddingRight: styles.paddingRight ?? '',
    paddingTop: styles.paddingTop ?? '',
    paddingBottom: styles.paddingBottom ?? '',
    background: styles.background ?? '',
    gravity: styles.gravity ?? '',
    borderRadius: styles.borderRadius ?? '',
    borderTopLeftRadius: styles.borderTopLeftRadius ?? '',
    borderTopRightRadius: styles.borderTopRightRadius ?? '',
    borderBottomRightRadius: styles.borderBottomRightRadius ?? '',
    borderBottomLeftRadius: styles.borderBottomLeftRadius ?? '',
    borderWidth: styles.borderWidth ?? '',
    borderColor: styles.borderColor ?? '',
    overflow: styles.overflow ?? '',
    zIndex: styles.zIndex ?? '',
    text: styles.text ?? '',
    textSize: styles.textSize ?? '',
    textColor: styles.textColor ?? '',
    value: styles.value ?? '',
    placeholder: styles.placeholder ?? '',
    color: styles.color ?? '',
    rotateX: styles.rotateX ?? '',
    rotateY: styles.rotateY ?? '',
    rotateZ: styles.rotateZ ?? '',
  }
}

export default function StyleEditor({
  value,
  onChange,
  tag,
  showBorder: showBorderProp,
  dataFields,
  componentProps,
  routeParams,
  pageQueryParams,
  repeatListName,
}: {
  value: StyleOverrides
  onChange?: (value: StyleOverrides) => void
  tag?: string
  showBorder?: boolean
  dataFields?: DataField[]
  componentProps?: ComponentPropDef[] | null
  routeParams?: Record<string, unknown> | null
  pageQueryParams?: PageQueryParamDef[] | null
  repeatListName?: string | null
}) {
  const [form, setForm] = useState<FormState>(() => syncFromModel(value ?? {}))

  useEffect(() => {
    setForm(syncFromModel(value ?? {}))
  }, [value])

  const attrBindShared = {
    dataFields: dataFields ?? [],
    componentProps,
    routeParams,
    pageQueryParams,
    repeatListName,
  }

  const showTextProps = tag === 'Text' || tag === 'Button'
  const showInputProps = tag === 'Input'
  const showIconColor = tag === 'Icon'
  const showRotateProps = tag === 'Text' || tag === 'Image' || tag === 'Icon'
  const showSizeProps = tag !== 'Modal'
  const showMarginProps = tag !== 'Modal'
  const showBorder =
    showBorderProp ??
    (tag === 'LinearLayout' ||
      tag === 'RelativeLayout' ||
      tag === 'Swiper' ||
      tag === 'MultiWindow' ||
      tag === 'Modal' ||
      tag === 'Image' ||
      tag === 'Input')
  const showOverflow =
    tag === 'LinearLayout' ||
    tag === 'RelativeLayout' ||
    tag === 'Swiper' ||
    tag === 'MultiWindow'

  const overflowOptionsForTag = useMemo(() => {
    if (tag === 'Swiper' || tag === 'MultiWindow') {
      return OVERFLOW_OPTIONS.filter((item) => item.value !== 'scroll')
    }
    return OVERFLOW_OPTIONS
  }, [tag])

  function emitStyles(nextForm: FormState) {
    const next: StyleOverrides = {}
    const set = (key: string, raw: string) => {
      const trimmed = raw.trim()
      if (trimmed) next[key] = trimmed
    }

    if (showSizeProps) {
      if (nextForm.widthMode === 'match_parent' || nextForm.widthMode === 'fixed') {
        set('width', sizeToAttr(nextForm.widthMode, nextForm.widthValue))
      }
      if (nextForm.heightMode === 'match_parent' || nextForm.heightMode === 'fixed') {
        set('height', sizeToAttr(nextForm.heightMode, nextForm.heightValue))
      }
    }
    if (showMarginProps) {
      set('margin', nextForm.margin)
      set('marginLeft', nextForm.marginLeft)
      set('marginRight', nextForm.marginRight)
      set('marginTop', nextForm.marginTop)
      set('marginBottom', nextForm.marginBottom)
    }
    set('padding', nextForm.padding)
    set('paddingLeft', nextForm.paddingLeft)
    set('paddingRight', nextForm.paddingRight)
    set('paddingTop', nextForm.paddingTop)
    set('paddingBottom', nextForm.paddingBottom)
    set('background', nextForm.background)
    if (tag !== 'Modal') set('gravity', nextForm.gravity)
    set('borderRadius', nextForm.borderRadius)
    set('borderTopLeftRadius', nextForm.borderTopLeftRadius)
    set('borderTopRightRadius', nextForm.borderTopRightRadius)
    set('borderBottomRightRadius', nextForm.borderBottomRightRadius)
    set('borderBottomLeftRadius', nextForm.borderBottomLeftRadius)
    set('borderWidth', nextForm.borderWidth)
    set('borderColor', nextForm.borderColor)
    set('overflow', nextForm.overflow)
    set('zIndex', nextForm.zIndex)
    set('text', nextForm.text)
    set('textSize', nextForm.textSize)
    set('textColor', nextForm.textColor)
    set('value', nextForm.value)
    set('placeholder', nextForm.placeholder)
    set('color', nextForm.color)
    if (showRotateProps) {
      set('rotateX', nextForm.rotateX)
      set('rotateY', nextForm.rotateY)
      set('rotateZ', nextForm.rotateZ)
    }

    onChange?.(next)
  }

  function patch(partial: Partial<FormState>) {
    const next = { ...form, ...partial }
    setForm(next)
    emitStyles(next)
  }

  function bindField(key: keyof FormState) {
    return {
      value: form[key],
      onChange: (next: string) => patch({ [key]: next }),
      ...attrBindShared,
    }
  }

  return (
    <div className="style-editor">
      {showSizeProps ? (
        <>
          <div className="section-title">尺寸</div>
          <Form layout="vertical" size="small">
            <Form.Item label="宽度 width">
              <div className="size-row">
                <Select
                  value={form.widthMode}
                  options={[...SIZE_OPTIONS]}
                  onChange={(widthMode) => patch({ widthMode })}
                />
                {form.widthMode === 'fixed' ? (
                  <AttrBindField
                    {...bindField('widthValue')}
                    placeholder="数字 / 绑定"
                    valueType="number"
                  />
                ) : null}
              </div>
            </Form.Item>
            <Form.Item label="高度 height">
              <div className="size-row">
                <Select
                  value={form.heightMode}
                  options={[...SIZE_OPTIONS]}
                  onChange={(heightMode) => patch({ heightMode })}
                />
                {form.heightMode === 'fixed' ? (
                  <AttrBindField
                    {...bindField('heightValue')}
                    placeholder="数字 / 绑定"
                    valueType="number"
                  />
                ) : null}
              </div>
            </Form.Item>
          </Form>
        </>
      ) : null}

      <div className="section-title">间距</div>
      <Form layout="vertical" size="small">
        <Form.Item label="padding">
          <AttrBindField {...bindField('padding')} valueType="number" />
        </Form.Item>
        <div className="quad-grid">
          <Form.Item label="上">
            <AttrBindField {...bindField('paddingTop')} valueType="number" />
          </Form.Item>
          <Form.Item label="右">
            <AttrBindField {...bindField('paddingRight')} valueType="number" />
          </Form.Item>
          <Form.Item label="下">
            <AttrBindField {...bindField('paddingBottom')} valueType="number" />
          </Form.Item>
          <Form.Item label="左">
            <AttrBindField {...bindField('paddingLeft')} valueType="number" />
          </Form.Item>
        </div>
        {showMarginProps ? (
          <>
            <Form.Item label="margin">
              <AttrBindField {...bindField('margin')} valueType="number" />
            </Form.Item>
            <div className="quad-grid">
              <Form.Item label="上">
                <AttrBindField {...bindField('marginTop')} valueType="number" />
              </Form.Item>
              <Form.Item label="右">
                <AttrBindField {...bindField('marginRight')} valueType="number" />
              </Form.Item>
              <Form.Item label="下">
                <AttrBindField {...bindField('marginBottom')} valueType="number" />
              </Form.Item>
              <Form.Item label="左">
                <AttrBindField {...bindField('marginLeft')} valueType="number" />
              </Form.Item>
            </div>
          </>
        ) : null}
      </Form>

      <div className="section-title">外观</div>
      <Form layout="vertical" size="small">
        <Form.Item label="background">
          <AttrBindField
            {...bindField('background')}
            placeholder="色值 / 绑定"
            valueType="color"
          />
        </Form.Item>
        <Form.Item label="层级 zIndex">
          <AttrBindField
            {...bindField('zIndex')}
            placeholder="如 10"
            valueType="number"
          />
        </Form.Item>
        {tag !== 'Modal' ? (
          <Form.Item label="gravity">
            <Select
              allowClear
              placeholder="默认"
              value={form.gravity || undefined}
              options={GRAVITY_OPTIONS.map((opt) => ({
                label: opt.label,
                value: opt.value || undefined,
              }))}
              onChange={(gravity) => patch({ gravity: gravity ?? '' })}
            />
          </Form.Item>
        ) : null}
        {showBorder ? (
          <>
            <Form.Item label="borderRadius 统一圆角">
              <AttrBindField {...bindField('borderRadius')} valueType="number" />
            </Form.Item>
            <div className="quad-grid">
              <Form.Item label="上左">
                <AttrBindField {...bindField('borderTopLeftRadius')} valueType="number" />
              </Form.Item>
              <Form.Item label="上右">
                <AttrBindField {...bindField('borderTopRightRadius')} valueType="number" />
              </Form.Item>
              <Form.Item label="下右">
                <AttrBindField
                  {...bindField('borderBottomRightRadius')}
                  valueType="number"
                />
              </Form.Item>
              <Form.Item label="下左">
                <AttrBindField
                  {...bindField('borderBottomLeftRadius')}
                  valueType="number"
                />
              </Form.Item>
            </div>
            <Form.Item label="borderWidth">
              <AttrBindField {...bindField('borderWidth')} valueType="number" />
            </Form.Item>
            <Form.Item label="borderColor">
              <AttrBindField
                {...bindField('borderColor')}
                placeholder="色值 / 绑定"
                valueType="color"
              />
            </Form.Item>
          </>
        ) : null}
        {showOverflow ? (
          <Form.Item label="overflow 溢出">
            <Select
              allowClear
              placeholder="默认显示"
              value={form.overflow || undefined}
              options={overflowOptionsForTag}
              onChange={(overflow) => patch({ overflow: overflow ?? '' })}
            />
          </Form.Item>
        ) : null}
      </Form>

      {showTextProps ? (
        <>
          <div className="section-title">内容</div>
          <Form layout="vertical" size="small">
            <Form.Item label="text">
              <AttrBindField {...bindField('text')} />
            </Form.Item>
            <Form.Item label="textSize">
              <AttrBindField {...bindField('textSize')} valueType="number" />
            </Form.Item>
            <Form.Item label="textColor">
              <AttrBindField
                {...bindField('textColor')}
                placeholder="色值 / 绑定"
                valueType="color"
              />
            </Form.Item>
          </Form>
        </>
      ) : null}

      {showInputProps ? (
        <>
          <div className="section-title">输入</div>
          <Form layout="vertical" size="small">
            <Form.Item label="value">
              <AttrBindField {...bindField('value')} />
            </Form.Item>
            <Form.Item label="placeholder">
              <AttrBindField {...bindField('placeholder')} />
            </Form.Item>
            <Form.Item label="textSize">
              <AttrBindField {...bindField('textSize')} valueType="number" />
            </Form.Item>
            <Form.Item label="textColor">
              <AttrBindField
                {...bindField('textColor')}
                placeholder="色值 / 绑定"
                valueType="color"
              />
            </Form.Item>
          </Form>
        </>
      ) : null}

      {showIconColor ? (
        <>
          <div className="section-title">图标</div>
          <Form layout="vertical" size="small">
            <Form.Item label="color">
              <AttrBindField
                {...bindField('color')}
                placeholder="色值 / 绑定"
                valueType="color"
              />
            </Form.Item>
          </Form>
        </>
      ) : null}

      {showRotateProps ? (
        <>
          <div className="section-title">旋转</div>
          <Form layout="vertical" size="small">
            <Form.Item label="rotateX（度）">
              <AttrBindField
                {...bindField('rotateX')}
                placeholder="0"
                valueType="number"
              />
            </Form.Item>
            <Form.Item label="rotateY（度）">
              <AttrBindField
                {...bindField('rotateY')}
                placeholder="0"
                valueType="number"
              />
            </Form.Item>
            <Form.Item label="rotateZ（度）">
              <AttrBindField
                {...bindField('rotateZ')}
                placeholder="0"
                valueType="number"
              />
            </Form.Item>
          </Form>
        </>
      ) : null}
    </div>
  )
}

// frontend/src/components/editor/StyleEditor.vue
<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import ColorPicker from './ColorPicker.vue'
import NumericInput from './NumericInput.vue'
import {
  GRAVITY_OPTIONS,
  SIZE_OPTIONS,
} from '../../utils/xml-node'
import { OVERFLOW_OPTIONS } from '../../utils/xml'
import type { StyleOverrides } from '../../types/dynamic-styles'

const props = defineProps<{
  modelValue: StyleOverrides
  /** 控件 tag，用于显示内容/图标等专属项 */
  tag?: string
  showBorder?: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: StyleOverrides]
}>()

const form = reactive({
  widthMode: 'wrap_content' as string,
  widthValue: '100' as string,
  heightMode: 'wrap_content' as string,
  heightValue: '40' as string,
  margin: '',
  marginLeft: '',
  marginRight: '',
  marginTop: '',
  marginBottom: '',
  padding: '',
  paddingLeft: '',
  paddingRight: '',
  paddingTop: '',
  paddingBottom: '',
  background: '',
  gravity: '',
  borderRadius: '',
  borderTopLeftRadius: '',
  borderTopRightRadius: '',
  borderBottomRightRadius: '',
  borderBottomLeftRadius: '',
  borderWidth: '',
  borderColor: '',
  overflow: '',
  zIndex: '',
  text: '',
  textSize: '',
  textColor: '',
  value: '',
  placeholder: '',
  color: '',
})

const showTextProps = computed(
  () => props.tag === 'Text' || props.tag === 'Button',
)
const showInputProps = computed(() => props.tag === 'Input')
const showIconColor = computed(() => props.tag === 'Icon')
/** Modal 始终全屏，无宽高 / margin */
const showSizeProps = computed(() => props.tag !== 'Modal')
const showMarginProps = computed(() => props.tag !== 'Modal')
const showBorder = computed(
  () =>
    props.showBorder ??
    (props.tag === 'LinearLayout' ||
      props.tag === 'RelativeLayout' ||
      props.tag === 'Swiper' ||
      props.tag === 'MultiWindow' ||
      props.tag === 'Modal' ||
      props.tag === 'Image' ||
      props.tag === 'Input'),
)
const showOverflow = computed(
  () =>
    props.tag === 'LinearLayout' ||
    props.tag === 'RelativeLayout' ||
    props.tag === 'Swiper' ||
    props.tag === 'MultiWindow',
)

const overflowOptionsForTag = computed(() => {
  if (props.tag === 'Swiper' || props.tag === 'MultiWindow') {
    return OVERFLOW_OPTIONS.filter((item) => item.value !== 'scroll')
  }
  return OVERFLOW_OPTIONS
})

function parseSizeMode(value: string | undefined, fallbackValue: number) {
  if (!value || value === 'wrap_content') {
    return { mode: 'wrap_content', value: String(fallbackValue) }
  }
  if (value === 'match_parent') {
    return { mode: 'match_parent', value: String(fallbackValue) }
  }
  return {
    mode: 'fixed',
    value: String(value).replace(/px$/i, ''),
  }
}

function sizeToAttr(mode: string, value: number | string): string {
  if (mode === 'match_parent' || mode === 'wrap_content') return mode
  const raw = String(value ?? '').trim()
  if (!raw) return '0'
  if (/\{[^{}]+\}/.test(raw)) return raw
  const num = Number(raw.replace(/px$/i, ''))
  return Number.isFinite(num) ? String(num) : raw
}

function syncFromModel(styles: StyleOverrides) {
  const width = parseSizeMode(styles.width, 100)
  const height = parseSizeMode(styles.height, 40)
  form.widthMode = width.mode
  form.widthValue = width.value
  form.heightMode = height.mode
  form.heightValue = height.value
  form.margin = styles.margin ?? ''
  form.marginLeft = styles.marginLeft ?? ''
  form.marginRight = styles.marginRight ?? ''
  form.marginTop = styles.marginTop ?? ''
  form.marginBottom = styles.marginBottom ?? ''
  form.padding = styles.padding ?? ''
  form.paddingLeft = styles.paddingLeft ?? ''
  form.paddingRight = styles.paddingRight ?? ''
  form.paddingTop = styles.paddingTop ?? ''
  form.paddingBottom = styles.paddingBottom ?? ''
  form.background = styles.background ?? ''
  form.gravity = styles.gravity ?? ''
  form.borderRadius = styles.borderRadius ?? ''
  form.borderTopLeftRadius = styles.borderTopLeftRadius ?? ''
  form.borderTopRightRadius = styles.borderTopRightRadius ?? ''
  form.borderBottomRightRadius = styles.borderBottomRightRadius ?? ''
  form.borderBottomLeftRadius = styles.borderBottomLeftRadius ?? ''
  form.borderWidth = styles.borderWidth ?? ''
  form.borderColor = styles.borderColor ?? ''
  form.overflow = styles.overflow ?? ''
  form.zIndex = styles.zIndex ?? ''
  form.text = styles.text ?? ''
  form.textSize = styles.textSize ?? ''
  form.textColor = styles.textColor ?? ''
  form.value = styles.value ?? ''
  form.placeholder = styles.placeholder ?? ''
  form.color = styles.color ?? ''
}

function emitStyles() {
  const next: StyleOverrides = {}
  const set = (key: string, value: string) => {
    const trimmed = value.trim()
    if (trimmed) next[key] = trimmed
  }

  // wrap_content 表示「不覆盖尺寸」，不写入 overrides；Modal 永不写宽高 / margin
  if (showSizeProps.value) {
    if (form.widthMode === 'match_parent' || form.widthMode === 'fixed') {
      set('width', sizeToAttr(form.widthMode, form.widthValue))
    }
    if (form.heightMode === 'match_parent' || form.heightMode === 'fixed') {
      set('height', sizeToAttr(form.heightMode, form.heightValue))
    }
  }
  if (showMarginProps.value) {
    set('margin', form.margin)
    set('marginLeft', form.marginLeft)
    set('marginRight', form.marginRight)
    set('marginTop', form.marginTop)
    set('marginBottom', form.marginBottom)
  }
  set('padding', form.padding)
  set('paddingLeft', form.paddingLeft)
  set('paddingRight', form.paddingRight)
  set('paddingTop', form.paddingTop)
  set('paddingBottom', form.paddingBottom)
  set('background', form.background)
  if (props.tag !== 'Modal') set('gravity', form.gravity)
  set('borderRadius', form.borderRadius)
  set('borderTopLeftRadius', form.borderTopLeftRadius)
  set('borderTopRightRadius', form.borderTopRightRadius)
  set('borderBottomRightRadius', form.borderBottomRightRadius)
  set('borderBottomLeftRadius', form.borderBottomLeftRadius)
  set('borderWidth', form.borderWidth)
  set('borderColor', form.borderColor)
  set('overflow', form.overflow)
  set('zIndex', form.zIndex)
  set('text', form.text)
  set('textSize', form.textSize)
  set('textColor', form.textColor)
  set('value', form.value)
  set('placeholder', form.placeholder)
  set('color', form.color)

  emit('update:modelValue', next)
}

watch(
  () => props.modelValue,
  (value) => syncFromModel(value ?? {}),
  { immediate: true, deep: true },
)

function onFieldChange() {
  emitStyles()
}
</script>

<template>
  <div class="style-editor">
    <template v-if="showSizeProps">
      <div class="section-title">尺寸</div>
      <el-form label-position="top" size="small">
        <el-form-item label="宽度 width">
          <div class="size-row">
            <el-select v-model="form.widthMode" @change="onFieldChange">
              <el-option
                v-for="opt in SIZE_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
            <NumericInput
              v-if="form.widthMode === 'fixed'"
              v-model="form.widthValue"
              placeholder="数字或 {变量}"
              @change="onFieldChange"
            />
          </div>
        </el-form-item>
        <el-form-item label="高度 height">
          <div class="size-row">
            <el-select v-model="form.heightMode" @change="onFieldChange">
              <el-option
                v-for="opt in SIZE_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
            <NumericInput
              v-if="form.heightMode === 'fixed'"
              v-model="form.heightValue"
              placeholder="数字或 {变量}"
              @change="onFieldChange"
            />
          </div>
        </el-form-item>
      </el-form>
    </template>

    <div class="section-title">间距</div>
    <el-form label-position="top" size="small">
      <el-form-item label="padding">
        <NumericInput v-model="form.padding" @change="onFieldChange" />
      </el-form-item>
      <div class="quad-grid">
        <el-form-item label="上">
          <NumericInput v-model="form.paddingTop" @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="右">
          <NumericInput v-model="form.paddingRight" @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="下">
          <NumericInput v-model="form.paddingBottom" @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="左">
          <NumericInput v-model="form.paddingLeft" @change="onFieldChange" />
        </el-form-item>
      </div>
      <template v-if="showMarginProps">
        <el-form-item label="margin">
          <NumericInput v-model="form.margin" @change="onFieldChange" />
        </el-form-item>
        <div class="quad-grid">
          <el-form-item label="上">
            <NumericInput v-model="form.marginTop" @change="onFieldChange" />
          </el-form-item>
          <el-form-item label="右">
            <NumericInput v-model="form.marginRight" @change="onFieldChange" />
          </el-form-item>
          <el-form-item label="下">
            <NumericInput v-model="form.marginBottom" @change="onFieldChange" />
          </el-form-item>
          <el-form-item label="左">
            <NumericInput v-model="form.marginLeft" @change="onFieldChange" />
          </el-form-item>
        </div>
      </template>
    </el-form>

    <div class="section-title">外观</div>
    <el-form label-position="top" size="small">
      <el-form-item label="background">
        <ColorPicker v-model="form.background" @change="onFieldChange" />
      </el-form-item>
      <el-form-item label="层级 zIndex">
        <NumericInput
          v-model="form.zIndex"
          placeholder="如 10，越大越靠上"
          @change="onFieldChange"
        />
      </el-form-item>
      <el-form-item v-if="tag !== 'Modal'" label="gravity">
        <el-select
          v-model="form.gravity"
          clearable
          placeholder="默认"
          @change="onFieldChange"
        >
          <el-option
            v-for="opt in GRAVITY_OPTIONS"
            :key="opt.value || 'default'"
            :label="opt.label"
            :value="opt.value"
          />
        </el-select>
      </el-form-item>
      <template v-if="showBorder">
        <el-form-item label="borderRadius 统一圆角">
          <NumericInput
            v-model="form.borderRadius"
            placeholder="四角共用；分角优先"
            @change="onFieldChange"
          />
        </el-form-item>
        <div class="quad-grid">
          <el-form-item label="上左">
            <NumericInput
              v-model="form.borderTopLeftRadius"
              @change="onFieldChange"
            />
          </el-form-item>
          <el-form-item label="上右">
            <NumericInput
              v-model="form.borderTopRightRadius"
              @change="onFieldChange"
            />
          </el-form-item>
          <el-form-item label="下右">
            <NumericInput
              v-model="form.borderBottomRightRadius"
              @change="onFieldChange"
            />
          </el-form-item>
          <el-form-item label="下左">
            <NumericInput
              v-model="form.borderBottomLeftRadius"
              @change="onFieldChange"
            />
          </el-form-item>
        </div>
        <el-form-item label="borderWidth">
          <NumericInput v-model="form.borderWidth" @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="borderColor">
          <ColorPicker v-model="form.borderColor" @change="onFieldChange" />
        </el-form-item>
      </template>
      <el-form-item v-if="showOverflow" label="overflow 溢出">
        <el-select
          v-model="form.overflow"
          clearable
          placeholder="默认显示"
          @change="onFieldChange"
        >
          <el-option
            v-for="opt in overflowOptionsForTag"
            :key="opt.value"
            :label="opt.label"
            :value="opt.value"
          />
        </el-select>
      </el-form-item>
    </el-form>

    <template v-if="showTextProps">
      <div class="section-title">内容</div>
      <el-form label-position="top" size="small">
        <el-form-item label="text">
          <el-input v-model="form.text" clearable @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="textSize">
          <NumericInput
            v-model="form.textSize"
            :min="1"
            :max="200"
            @change="onFieldChange"
          />
        </el-form-item>
        <el-form-item label="textColor">
          <ColorPicker v-model="form.textColor" @change="onFieldChange" />
        </el-form-item>
      </el-form>
    </template>

    <template v-if="showInputProps">
      <div class="section-title">输入</div>
      <el-form label-position="top" size="small">
        <el-form-item label="value">
          <el-input v-model="form.value" clearable @change="onFieldChange" />
        </el-form-item>
        <el-form-item label="placeholder">
          <el-input
            v-model="form.placeholder"
            clearable
            @change="onFieldChange"
          />
        </el-form-item>
        <el-form-item label="textSize">
          <NumericInput
            v-model="form.textSize"
            :min="1"
            :max="200"
            @change="onFieldChange"
          />
        </el-form-item>
        <el-form-item label="textColor">
          <ColorPicker v-model="form.textColor" @change="onFieldChange" />
        </el-form-item>
      </el-form>
    </template>

    <template v-if="showIconColor">
      <div class="section-title">图标</div>
      <el-form label-position="top" size="small">
        <el-form-item label="color">
          <ColorPicker v-model="form.color" @change="onFieldChange" />
        </el-form-item>
      </el-form>
    </template>
  </div>
</template>

<style scoped>
.style-editor {
  min-width: 0;
}

.section-title {
  margin: 12px 0 8px;
  font-size: 12px;
  font-weight: 600;
  color: #909399;
}

.section-title:first-child {
  margin-top: 0;
}

.size-row {
  display: flex;
  gap: 8px;
  width: 100%;
}

.size-row > :first-child {
  flex: 1;
  min-width: 0;
}

.size-row > :last-child {
  width: 100px;
  flex-shrink: 0;
}

.quad-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 0 8px;
}

:deep(.el-form-item) {
  margin-bottom: 10px;
}
</style>
