// frontend/src/components/editor/TypeExprEditor.tsx
import { useMemo } from 'react'
import DataFieldTypeTreeSelect, {
  type TypeSelectPayload,
} from './DataFieldTypeTreeSelect'
import {
  isTypeExprCleared,
  type DataTypeLibrary,
  type TypeExpr,
} from '../../types/data-types'
import {
  selectPayloadToTypeExpr,
  TYPE_EXPR_EXCLUDE_TYPES,
  typeExprToSelectPayload,
} from '../../utils/type-expr-select'

export default function TypeExprEditor({
  value,
  onChange,
  library,
  genericNames,
  excludeNamedIds,
  allowNone = false,
  size = 'default',
  className,
}: {
  value: TypeExpr | null
  onChange?: (value: TypeExpr | null) => void
  library?: DataTypeLibrary | null
  genericNames?: string[]
  excludeNamedIds?: string[]
  allowNone?: boolean
  size?: 'large' | 'default' | 'small'
  className?: string
}) {
  const payload = useMemo(() => typeExprToSelectPayload(value), [value])

  const isEmpty = value == null || isTypeExprCleared(value)

  function handleChange(next: TypeSelectPayload) {
    if (next.cleared) {
      onChange?.(allowNone ? null : selectPayloadToTypeExpr(next))
      return
    }
    onChange?.(selectPayloadToTypeExpr(next))
  }

  return (
    <DataFieldTypeTreeSelect
      type={payload.cleared ? 'string' : payload.type}
      typeRef={payload.typeRef}
      itemType={payload.itemType}
      itemTypeRef={payload.itemTypeRef}
      itemItemType={payload.itemItemType}
      itemItemTypeRef={payload.itemItemTypeRef}
      empty={isEmpty}
      library={library}
      genericNames={genericNames}
      excludeNamedIds={excludeNamedIds}
      excludeTypes={TYPE_EXPR_EXCLUDE_TYPES}
      allowAny
      emptyOnClear
      clearable
      size={size}
      className={className}
      onChange={handleChange}
    />
  )
}

// frontend/src/components/editor/TypeExprEditor.vue
<script setup lang="ts">
import { computed } from 'vue'
import DataFieldTypeTreeSelect, {
  type TypeSelectPayload,
} from './DataFieldTypeTreeSelect.vue'
import {
  isTypeExprCleared,
  type DataTypeLibrary,
  type TypeExpr,
} from '../../types/data-types'
import {
  selectPayloadToTypeExpr,
  TYPE_EXPR_EXCLUDE_TYPES,
  typeExprToSelectPayload,
} from '../../utils/type-expr-select'

const props = withDefaults(
  defineProps<{
    modelValue: TypeExpr | null
    library?: DataTypeLibrary | null
    genericNames?: string[]
    excludeNamedIds?: string[]
    /** 允许选择「无约束」，值为 null */
    allowNone?: boolean
    size?: 'large' | 'default' | 'small'
  }>(),
  {
    allowNone: false,
    size: 'default',
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: TypeExpr | null]
}>()

const payload = computed(() => typeExprToSelectPayload(props.modelValue))

const isEmpty = computed(() => {
  if (props.modelValue == null) return true
  return isTypeExprCleared(props.modelValue)
})

function onChange(next: TypeSelectPayload) {
  if (next.cleared) {
    emit('update:modelValue', props.allowNone ? null : selectPayloadToTypeExpr(next))
    return
  }
  emit('update:modelValue', selectPayloadToTypeExpr(next))
}
</script>

<template>
  <DataFieldTypeTreeSelect
    :type="payload.cleared ? 'string' : payload.type"
    :type-ref="payload.typeRef"
    :item-type="payload.itemType"
    :item-type-ref="payload.itemTypeRef"
    :item-item-type="payload.itemItemType"
    :item-item-type-ref="payload.itemItemTypeRef"
    :empty="isEmpty"
    :library="library"
    :generic-names="genericNames"
    :exclude-named-ids="excludeNamedIds"
    :exclude-types="TYPE_EXPR_EXCLUDE_TYPES"
    allow-any
    empty-on-clear
    clearable
    :size="size"
    @change="onChange"
  />
</template>
