// frontend/src/components/editor/VisibilityConditionDialog.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button, Input, Modal, Radio, Select, Table } from 'antd'
import { DeleteOutlined, PlusOutlined } from '@ant-design/icons'
import { ElMessage } from '../../ui/feedback'
import DataFieldPathSelect from './DataFieldPathSelect'
import {
  STYLE_CONDITION_OP_OPTIONS,
  createEmptyCondition,
  createEmptyScenario,
  createEmptyVisibilityConfig,
  type StyleCondition,
  type StyleScenario,
  type VisibilityConditionConfig,
} from '../../types/dynamic-styles'
import type { DataField } from '../../types/page-data'
import type { ComponentPropDef } from '../../types/component'
import { findNearestRepeatListName } from '../../utils/data-field-paths'
import './VisibilityConditionDialog.css'

export default function VisibilityConditionDialog({
  open,
  onOpenChange,
  title,
  config,
  dataFields,
  componentProps,
  routeParams,
  selectedNodeId,
  xml,
  onSave,
}: {
  open: boolean
  onOpenChange?: (open: boolean) => void
  title: string
  config: VisibilityConditionConfig | null
  dataFields?: DataField[]
  componentProps?: ComponentPropDef[] | null
  routeParams?: Record<string, unknown> | null
  selectedNodeId?: string
  xml?: string
  onSave?: (config: VisibilityConditionConfig) => void
}) {
  const [scenarios, setScenarios] = useState<StyleScenario[]>([])
  const [activeSceneId, setActiveSceneId] = useState('')

  const repeatListName = useMemo(() => {
    if (!xml || !selectedNodeId) return null
    return findNearestRepeatListName(xml, selectedNodeId)
  }, [xml, selectedNodeId])

  const activeScene = scenarios.find((item) => item.id === activeSceneId) ?? null

  const needsValue = (op: StyleCondition['op']) =>
    op !== 'empty' && op !== 'notEmpty'

  useEffect(() => {
    if (!open) return
    const source = config?.scenarios?.length
      ? config
      : createEmptyVisibilityConfig()
    const next = source.scenarios.map((scene) => ({
      ...scene,
      conditions: scene.conditions.map((cond) => ({ ...cond })),
    }))
    const ensured = next.length ? next : [createEmptyScenario(1)]
    setScenarios(ensured)
    setActiveSceneId(ensured[0]?.id ?? '')
  }, [open, config])

  function addScenario() {
    const scene = createEmptyScenario(scenarios.length + 1)
    setScenarios((prev) => [...prev, scene])
    setActiveSceneId(scene.id)
  }

  function removeScenario(sceneId: string) {
    if (scenarios.length <= 1) {
      ElMessage.warning('至少保留一个场景')
      return
    }
    const next = scenarios.filter((item) => item.id !== sceneId)
    setScenarios(next)
    if (activeSceneId === sceneId) {
      setActiveSceneId(next[0]?.id ?? '')
    }
  }

  function patchScene(sceneId: string, patch: Partial<StyleScenario>) {
    setScenarios((prev) =>
      prev.map((item) => (item.id === sceneId ? { ...item, ...patch } : item)),
    )
  }

  function patchCondition(
    sceneId: string,
    index: number,
    patch: Partial<StyleCondition>,
  ) {
    setScenarios((prev) =>
      prev.map((item) => {
        if (item.id !== sceneId) return item
        return {
          ...item,
          conditions: item.conditions.map((cond, i) =>
            i === index ? { ...cond, ...patch } : cond,
          ),
        }
      }),
    )
  }

  function addCondition() {
    if (!activeScene) return
    patchScene(activeScene.id, {
      conditions: [...activeScene.conditions, createEmptyCondition()],
    })
  }

  function removeCondition(index: number) {
    if (!activeScene) return
    if (activeScene.conditions.length <= 1) {
      patchScene(activeScene.id, { conditions: [createEmptyCondition()] })
      return
    }
    patchScene(activeScene.id, {
      conditions: activeScene.conditions.filter((_, i) => i !== index),
    })
  }

  function handleSave() {
    onSave?.({
      scenarios: scenarios.map((scene, index) => ({
        id: scene.id,
        name: scene.name.trim() || `场景${index + 1}`,
        conditions: scene.conditions.map((cond) => ({ ...cond })),
      })),
    })
    onOpenChange?.(false)
  }

  function handleClear() {
    onSave?.({ scenarios: [] })
    onOpenChange?.(false)
  }

  return (
    <Modal
      open={open}
      title={title}
      width={720}
      destroyOnHidden
      maskClosable={false}
      keyboard={false}
      onCancel={() => onOpenChange?.(false)}
      footer={
        <>
          <Button onClick={handleClear}>清除</Button>
          <Button type="primary" onClick={handleSave}>
            保存
          </Button>
        </>
      }
    >
      <p className="block-hint">
        同一场景内条件为「且」；多个场景为「或」。字段支持树形选择；选中数组后可填下标。
        {repeatListName ? (
          <>
            {' '}
            当前在重复「{repeatListName}」内，可选 <code>index</code> /
            <code>item.xxx</code>。
          </>
        ) : null}
      </p>

      <div className="scene-tabs">
        <Radio.Group
          value={activeSceneId}
          size="small"
          optionType="button"
          onChange={(e) => setActiveSceneId(e.target.value)}
        >
          {scenarios.map((scene) => (
            <Radio.Button key={scene.id} value={scene.id}>
              {scene.name}
            </Radio.Button>
          ))}
        </Radio.Group>
        <Button type="link" icon={<PlusOutlined />} onClick={addScenario}>
          添加场景
        </Button>
      </div>

      {activeScene && (
        <div className="scene-panel">
          <div className="scene-header">
            <Input
              value={activeScene.name}
              size="small"
              placeholder="场景名称"
              style={{ maxWidth: 200 }}
              onChange={(e) =>
                patchScene(activeScene.id, { name: e.target.value })
              }
            />
            <Button
              type="link"
              danger
              icon={<DeleteOutlined />}
              disabled={scenarios.length <= 1}
              onClick={() => removeScenario(activeScene.id)}
            >
              删除场景
            </Button>
          </div>

          <Table
            className="cond-table"
            dataSource={activeScene.conditions}
            rowKey={(row) =>
              `${activeScene.id}-${activeScene.conditions.indexOf(row)}`
            }
            pagination={false}
            bordered
            size="small"
            columns={[
              {
                title: '字段',
                minWidth: 240,
                render: (_, row, index) => (
                  <DataFieldPathSelect
                    value={row.field}
                    fields={dataFields}
                    componentProps={componentProps}
                    routeParams={routeParams}
                    repeatListName={repeatListName}
                    onChange={(next) =>
                      patchCondition(activeScene.id, index, { field: next })
                    }
                  />
                ),
              },
              {
                title: '条件',
                width: 130,
                render: (_, row, index) => (
                  <Select
                    value={row.op}
                    style={{ width: '100%' }}
                    options={STYLE_CONDITION_OP_OPTIONS.map((opt) => ({
                      value: opt.value,
                      label: opt.label,
                    }))}
                    onChange={(next) =>
                      patchCondition(activeScene.id, index, { op: next })
                    }
                  />
                ),
              },
              {
                title: '值',
                minWidth: 120,
                render: (_, row, index) => (
                  <Input
                    value={row.value}
                    disabled={!needsValue(row.op)}
                    placeholder="比较值"
                    onChange={(e) =>
                      patchCondition(activeScene.id, index, {
                        value: e.target.value,
                      })
                    }
                  />
                ),
              },
              {
                title: '',
                width: 56,
                align: 'center',
                render: (_, __, index) => (
                  <Button
                    type="link"
                    danger
                    icon={<DeleteOutlined />}
                    onClick={() => removeCondition(index)}
                  />
                ),
              },
            ]}
          />
          <Button
            className="add-cond"
            type="link"
            icon={<PlusOutlined />}
            onClick={addCondition}
          >
            添加条件
          </Button>
        </div>
      )}
    </Modal>
  )
}

// frontend/src/components/editor/VisibilityConditionDialog.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { Delete, Plus } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import DataFieldPathSelect from './DataFieldPathSelect.vue'
import {
  STYLE_CONDITION_OP_OPTIONS,
  createEmptyCondition,
  createEmptyScenario,
  createEmptyVisibilityConfig,
  type StyleCondition,
  type StyleScenario,
  type VisibilityConditionConfig,
} from '../../types/dynamic-styles'
import type { DataField } from '../../types/page-data'
import type { ComponentPropDef } from '../../types/component'
import { findNearestRepeatListName } from '../../utils/data-field-paths'

const props = defineProps<{
  modelValue: boolean
  title: string
  config: VisibilityConditionConfig | null
  dataFields?: DataField[]
  /** 编辑组件时传入（含空数组），字段树展示 $props */
  componentProps?: ComponentPropDef[] | null
  /** 路由参数（含空对象），字段树展示 $route */
  routeParams?: Record<string, unknown> | null
  selectedNodeId?: string
  xml?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [visible: boolean]
  save: [config: VisibilityConditionConfig]
}>()

const draft = reactive<{
  scenarios: StyleScenario[]
}>({
  scenarios: [],
})

const activeSceneId = ref('')

const visible = computed({
  get: () => props.modelValue,
  set(value: boolean) {
    emit('update:modelValue', value)
  },
})

const repeatListName = computed(() => {
  if (!props.xml || !props.selectedNodeId) return null
  return findNearestRepeatListName(props.xml, props.selectedNodeId)
})

const activeScene = computed(() =>
  draft.scenarios.find((item) => item.id === activeSceneId.value) ?? null,
)

const needsValue = (op: StyleCondition['op']) =>
  op !== 'empty' && op !== 'notEmpty'

watch(
  () => [props.modelValue, props.config] as const,
  ([open, config]) => {
    if (!open) return
    const source = config?.scenarios?.length
      ? config
      : createEmptyVisibilityConfig()
    draft.scenarios = source.scenarios.map((scene) => ({
      ...scene,
      conditions: scene.conditions.map((cond) => ({ ...cond })),
    }))
    if (!draft.scenarios.length) {
      draft.scenarios = [createEmptyScenario(1)]
    }
    activeSceneId.value = draft.scenarios[0]?.id ?? ''
  },
)

function addScenario() {
  const scene = createEmptyScenario(draft.scenarios.length + 1)
  draft.scenarios.push(scene)
  activeSceneId.value = scene.id
}

function removeScenario(sceneId: string) {
  if (draft.scenarios.length <= 1) {
    ElMessage.warning('至少保留一个场景')
    return
  }
  draft.scenarios = draft.scenarios.filter((item) => item.id !== sceneId)
  if (activeSceneId.value === sceneId) {
    activeSceneId.value = draft.scenarios[0]?.id ?? ''
  }
}

function addCondition() {
  if (!activeScene.value) return
  activeScene.value.conditions.push(createEmptyCondition())
}

function removeCondition(index: number) {
  if (!activeScene.value) return
  if (activeScene.value.conditions.length <= 1) {
    activeScene.value.conditions = [createEmptyCondition()]
    return
  }
  activeScene.value.conditions.splice(index, 1)
}

function handleSave() {
  emit('save', {
    scenarios: draft.scenarios.map((scene, index) => ({
      id: scene.id,
      name: scene.name.trim() || `场景${index + 1}`,
      conditions: scene.conditions.map((cond) => ({ ...cond })),
    })),
  })
  visible.value = false
}

function handleClear() {
  emit('save', { scenarios: [] })
  visible.value = false
}
</script>

<template>
  <el-dialog
    v-model="visible"
    :title="title"
    width="720px"
    destroy-on-close
    append-to-body
    :close-on-click-modal="false"
    :close-on-press-escape="false"
  >
    <p class="block-hint">
      同一场景内条件为「且」；多个场景为「或」。字段支持树形选择；选中数组后可填下标。
      <template v-if="repeatListName">
        当前在重复「{{ repeatListName }}」内，可选 <code>index</code> /
        <code>item.xxx</code>。
      </template>
    </p>

    <div class="scene-tabs">
      <el-radio-group v-model="activeSceneId" size="small">
        <el-radio-button
          v-for="scene in draft.scenarios"
          :key="scene.id"
          :value="scene.id"
        >
          {{ scene.name }}
        </el-radio-button>
      </el-radio-group>
      <el-button type="primary" link :icon="Plus" @click="addScenario">
        添加场景
      </el-button>
    </div>

    <div v-if="activeScene" class="scene-panel">
      <div class="scene-header">
        <el-input
          v-model="activeScene.name"
          size="small"
          placeholder="场景名称"
          style="max-width: 200px"
        />
        <el-button
          type="danger"
          link
          :icon="Delete"
          :disabled="draft.scenarios.length <= 1"
          @click="removeScenario(activeScene.id)"
        >
          删除场景
        </el-button>
      </div>

      <el-table :data="activeScene.conditions" border size="small" class="cond-table">
        <el-table-column label="字段" min-width="240">
          <template #default="{ row }">
            <DataFieldPathSelect
              v-model="row.field"
              :fields="props.dataFields"
              :component-props="props.componentProps"
              :route-params="props.routeParams"
              :repeat-list-name="repeatListName"
            />
          </template>
        </el-table-column>
        <el-table-column label="条件" width="130">
          <template #default="{ row }">
            <el-select v-model="row.op" style="width: 100%">
              <el-option
                v-for="opt in STYLE_CONDITION_OP_OPTIONS"
                :key="opt.value"
                :label="opt.label"
                :value="opt.value"
              />
            </el-select>
          </template>
        </el-table-column>
        <el-table-column label="值" min-width="120">
          <template #default="{ row }">
            <el-input
              v-model="row.value"
              :disabled="!needsValue(row.op)"
              placeholder="比较值"
            />
          </template>
        </el-table-column>
        <el-table-column label="" width="56" align="center">
          <template #default="{ $index }">
            <el-button
              type="danger"
              link
              :icon="Delete"
              @click="removeCondition($index)"
            />
          </template>
        </el-table-column>
      </el-table>
      <el-button class="add-cond" type="primary" link :icon="Plus" @click="addCondition">
        添加条件
      </el-button>
    </div>

    <template #footer>
      <el-button @click="handleClear">清除</el-button>
      <el-button type="primary" @click="handleSave">保存</el-button>
    </template>
  </el-dialog>
</template>

<style scoped>
.block-hint {
  margin: 0 0 12px;
  font-size: 12px;
  color: #909399;
  line-height: 1.5;
}

.block-hint code {
  font-size: 11px;
  color: #606266;
}

.scene-tabs {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  margin-bottom: 10px;
  flex-wrap: wrap;
}

.scene-panel {
  margin-bottom: 8px;
  padding: 12px;
  border: 1px solid #ebeef5;
  border-radius: 8px;
  background: #fafbfc;
}

.scene-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
  gap: 8px;
}

.cond-table {
  width: 100%;
}

.add-cond {
  margin-top: 8px;
}
</style>
