// frontend/src/views/AiAssistantView.tsx
import { useEffect } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useProjectStore } from '../stores/project'
import { useAiAssistantStore } from '../stores/ai-assistant'
import AiAssistantPanel from '../components/editor/AiAssistantPanel'
import './AiAssistantView.css'

export default function AiAssistantView() {
  const [params] = useSearchParams()
  const navigate = useNavigate()
  const hasProject = useProjectStore((s) => s.hasProject)
  const setPanelOpen = useAiAssistantStore((s) => s.setPanelOpen)
  const sessionId = params.get('session')?.trim() || ''

  useEffect(() => {
    if (!hasProject) {
      void navigate('/', { replace: true })
      return
    }
    setPanelOpen(true)
    document.title = 'AI 助手'
  }, [hasProject, navigate, setPanelOpen])

  return (
    <div className="ai-window-page">
      <AiAssistantPanel
        open
        onOpenChange={() => {
          window.close()
          void navigate('/workspace')
        }}
        mode="window"
        initialSessionId={sessionId}
      />
    </div>
  )
}

// frontend/src/views/AiAssistantView.vue
<script setup lang="ts">
import { computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useProjectStore } from '../stores/project'
import { useAiAssistantStore } from '../stores/ai-assistant'
import AiAssistantPanel from '../components/editor/AiAssistantPanel.vue'

const route = useRoute()
const router = useRouter()
const projectStore = useProjectStore()
const aiAssistant = useAiAssistantStore()

const sessionId = computed(() => {
  const raw = route.query.session
  return typeof raw === 'string' && raw.trim() ? raw.trim() : ''
})

const panelVisible = computed({
  get: () => true,
  set: () => {
    // 独立窗口关闭面板即关闭窗口
    window.close()
    void router.push('/workspace')
  },
})

onMounted(() => {
  if (!projectStore.hasProject) {
    void router.replace('/')
    return
  }
  aiAssistant.setPanelOpen(true)
  document.title = 'AI 助手'
})
</script>

<template>
  <div class="ai-window-page">
    <AiAssistantPanel
      v-model="panelVisible"
      mode="window"
      :initial-session-id="sessionId"
    />
  </div>
</template>

<style scoped>
.ai-window-page {
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  background: #f5f7fa;
}
</style>
